### ISSUE TITLE
More alt columns in the Grid tab

### ISSUE THREAD

**Issue by RavenPrime** [teelolws/Altoholic-Retail#1]
Feature request now that we can more alts per server.

Please add more columns in the Grid tab to show more than 12 alts.

**Comment by teelolws** [comment]
Hi, I've just uploaded a build that allows for more characters on the Grid tab without just adding more columns. Instead I've added arrow buttons at the bottom that should let you scroll through them. Can you test it and let me know if theres any issues please.

**Comment by RavenPrime** [comment]
I have been using it for 2 days "ish" and haven't had any problems with it. Thank you very much.
I do wonder if the same fix can be applied to the achievement tab.

**Comment by teelolws** [comment]
Allright, just applied the same code to the Achievement tab. Let me know if it works.

**Comment by RavenPrime** [comment]
Both tabs work for me with no errors and look great. Thank you!
