### ISSUE TITLE
Profession colouring on vendors not correct.

### ISSUE THREAD

**Issue by teelolws** [teelolws/Altoholic-Retail#10]
This one should be green:

![image](https://user-images.githubusercontent.com/49792789/76282930-1ca4d080-62fe-11ea-8f3a-4a65509685ed.png)

**Comment by teelolws** [comment]
And it shouldn't be flagged "Already known".

Probably an issue with Datastore not saving the ranks correctly.

**Comment by teelolws** [comment]
Hmm. Its tracking the rank correctly on the character tab.

![image](https://user-images.githubusercontent.com/49792789/76283098-90df7400-62fe-11ea-8f27-ef69cdb78e1b.png)

**Comment by teelolws** [comment]
Allright, I have a rudimentary solution that will **only work if you game client is in English**.

It wasn't simple to get the "Rank #" out of an item link.

I have to:
1. Create a hidden game tooltip
2. Assign the recipe link to the game tooltip
3. Pull Line #2 out of the tooltip
4. Find "Rank (%d)"
5. Process the %d (being a digit) as the rank of the recipe
6. Compare it against whats stored in Datastore.

Other languages won't use "Rank 2" on the second line, so I expect it simply won't work, and will treat every recipe as if its Rank 1. I'd have to do the proper localisation process to handle this, which I don't know how to do.

**Comment by teelolws** [comment]
Also, I don't know if other addons will work nicely with this fix, so I'm **not** going to upload it to curseforge for a while. Give people a chance to test it here.

**Comment by Incandio** [comment]
It seems to be tracking ranks with this build, haven't been able to replicate the issue on a few toons at different vendors. I'm using it with quite a lot of other addons including ArkInventory / ELVUI / Autobar / AllTheThings / CanIMogIt.

The Red / Green colour is still erratic between professions the toon doesn't know. There are even Red and Green recipes within the same unknown profession for the same item. E.G. This is what my leatherworker / skinner sees at the 7th Legion vendor: Red Rank 2 Schematic for the AZ3-R1-T3 specs, as expected, but the Rank 3 schematic for the same item is green. You can also see the Jewelcrafting ring is a green recipe, even though the toon doesn't know JC.
![Annotation 2020-03-10 174715](https://user-images.githubusercontent.com/62014070/76305412-aef5a600-62f7-11ea-842a-dc81d19133a6.jpg)

**Comment by teelolws** [comment]
Okay, theres two different problems you're describing here.

The Rank 2 is Red because your alt already knows it, and your current character can't learn it. This is working as expected. The Rank 3 should not be Green, and I'll take a look into this.

The Jewelcrafting Ring is Green because your alt can learn it. This is the way Thaoky designed it originally: it should be green if an Alt has the skill required to learn it (ignoring rep requirements and everything else, just profession skill); yellow if it can learn it once it skills up higher; red if everything that could learn it already knows it.

**Comment by teelolws** [comment]
Can you mouse over the Rank 3 AZ3-R1-T3, screenshot it, and post it here?

**Comment by Incandio** [comment]
That's right, there are 2 different problems. Although, if the 2nd problem is behaving as expected, there is only one problem! I didn't realize that the colouring was based on what **all** alts know / don't know. If that is the case, then it's OK that the Rank 3 is green because my alt (Necrognome) does not know it yet but knows the Rank 2. The other recipes also make sense to me.

**Comment by teelolws** [comment]
Okay cool. I had an LUA error when I checked a rep vendor which I've fixed now.
