### ISSUE TITLE
Only 4 Reputations Showing

### ISSUE THREAD

**Issue by Strokelock** [teelolws/Altoholic-Retail#101]
All toons missing Rep. Seems to be a quick fix.

Date: 2020-09-11 04:10:50
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Altoholic_Grids\Grid_Reputations.lua line 501:
   attempt to concatenate field 'name' (a nil value)
Debug:
   [string "@Altoholic_Grids\Grid_Reputations.lua"]:501: RowSetup()
   [string "@Altoholic_Grids\TabGrids.lua"]:86: Update()
   [string "*:OnClick"]:6:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 GetSize = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:497
 OnEnter = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:565
 RowOnLeave = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:505
 RowOnEnter = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:504
 InitViewDDM = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:623
 OnLeave = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:620
 OnClick = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:605
 RowSetup = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:498
 OnUpdate = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:481
 ColumnSetup = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Reputations.lua:506
}
rowFrame = <unnamed> {
 0 = <userdata>
 Item39 = <unnamed> {
 }
 Item8 = <unnamed> {
 }
 Item30 = <unnamed> {
 }
 Item25 = <unnamed> {
 }
 Item26 = <unnamed> {
 }
 Item28 = <unnamed> {
 }
 Item22 = <unnamed> {
 }
 Item44 = <unnamed> {
 }
 Item15 = <unnamed> {
 }
 Item16 = <unnamed> {
 }
 Item4 = <unnamed> {
 }
 Item19 = <unnamed> {
 }
 Item5 = <unnamed> {
 }
 Item50 = <unnamed> {
 }
 Item42 = <unnamed> {
 }
 Item23 = <unnamed> {
 }
 Item40 = <unnamed> {
 }
 Item47 = <unnamed> {
 }
 Item1 = <unnamed> {
 }
 Item24 = <unnamed> {
 }
 Item29 = <unnamed> {
 }
 Item46 = <unnamed> {
 }
 Item33 = <unnamed> {
 }
 Item31 = <unnamed> {
 }
 Item45 = <unnamed> {
 }
 Item43 = <unnamed> {
 }
 Item18 = <unnamed> {
 }
 Item49 = <unnamed> {
 }
 Item41 = <unnamed> {
 }
 Item6 = <unnamed> {
 }
 Item17 = <unnamed> {
 }
 Item35 = <unnamed> {
 }
 Item36 = <unnamed> {
 }
 Item13 = <unnamed> {
 }
 Item32 = <unnamed> {
 }
 Item37 = <unnamed> {
 }
 Item34 = <unnamed> {
 }
 Item27 = <unnamed> {
 }
 Item12 = <unnamed> {
 }
 Item48 = <unnamed> {
 }
 Item21 = <unnamed> {
 }
 Item20 = <unnamed> {
 }
 Item14 = <unnamed> {
 }
 Item3 = <unnamed> {
 }
 Item11 = <unnamed> {
 }
 Name = <unnamed> {
 }
 Item10 = <unnamed> {
 }
 Item38 = <unnamed> {
 }
 Item7 = <unnamed> {
 }
 Item2 = <unnamed> {
 }
 Item9 = <unnamed> {
 }
}
dataRowID = 5
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'name' (a nil value)"
currentFaction = <table> {
 icon = "inv_faction_akoan"
}
view = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
colors = <table> {
 cyan = ""
 recipeOrange = ""
 Horde = ""
 Alliance = ""
 gold = ""
 common = ""
 classMage = ""
 orange = ""
 red = ""
 epic = ""
 rare = ""
 recipeGreen = ""
 battleNetBlue = ""
 heirloom = ""
 teal = ""
 uncommon = ""
 lightBlue = ""
 classHunter = ""
 legendary = ""
 grey = ""
 green = ""
 darkred = ""
 yellow = ""
 recipeGrey = ""
 white = ""
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AccountantClassic, vv2.12.01
  Ace3, v
  AceGUI30SFXWidgets, v1.0.1
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, v8.3-006
  AltoholicGrids, vr192
  AltoholicSummary, vr192
  ArkInventory, v30935
  ArkInventoryRules, v30932
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v30932
  AtlasLoot, vv8.12.00
  AtlasLootBattleforAzeroth, vv8.12.00
  AzeritePowerWeights, v8.3.12
  AzeriteTooltip, v2.0.8
  BigWigs, vv184.4
  BonusRollPreview, v80100.47-Release
  CamelSpotter, v1.5.5
  ClassOrderHallsComplete, v1.35
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.34
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v11.0.0
  DejaCharacterStats, v800r103
  Details, v
  DetailsEncounterDetails, v
  GatherMate2, v1.45.6
  GTFO, v4.56
  GuildRosterManager, v1.893
  HandyNotes, vv1.5.10
  HandyNotesArgus, vv0.16
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesCamelFigurines, v1.3
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesMechagonAndNazjatar, v13
  HandyNotesVisionsOfNZoth, v38
  HandyNotesWarfrontRares, v0.5.0
  Hekili, vv8.3.7-01
  Masque, v8.3.0
  MasterPlanA, vA
  Pawn, v2.3.35
  PersonalLootHelper, v2.21
  PetBattleTeams, v3.3.11
  PetTracker, v8.3.8
  PetTrackerConfig, v
  PetTrackerJournal, v
  Postal, vv3.6.2
  Quartz, v3.5.2
  Rematch, v4.10.5
  RematchTSMPetValues, v1.1.17
  SellableItemDrops, v1.4.18
  ShadowedUnitFrames, vv4.2.9
  SilverDragon, vv80300.2
  SilverDragonBattleForAzeroth, vv80300.2
  SilverDragonBurningCrusade, vv80300.2
  SilverDragonCataclysm, vv80300.2
  SilverDragonLegion, vv80300.2
  SilverDragonMists, vv80300.2
  SilverDragonVanilla, vv80300.2
  SilverDragonWarlords, vv80300.2
  SilverDragonWrath, vv80300.2
  Simulationcraft, v1.12.5
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SubSpec, v2.2.0.1
  TheUndermineJournal, v5.5.20200908
  TomTom, vv80300-1.1.4
  TransmogTokens, v1.4.9
  WorldQuestTracker, v
  WowDings, vv1.3.3.4
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=9a9)

**Comment by teelolws** [comment]
You have a **very** outdated version of my addon installed.

**Comment by Strokelock** [comment]
It updated from Twitch this Morning. I literally update everything from there every morning. Maybe Twitch is not updating. I will check versions.
    On Friday, September 11, 2020, 04:45:45 AM CDT, teelolws <notifications@github.com> wrote:  
 
 


You have a very outdated version of my addon installed.

**Comment by teelolws** [comment]
Uninstall it off the twitch client. Reinstall it from: https://www.curseforge.com/wow/addons/altoholic-retail
