### ISSUE TITLE
Enhancement request: Sort by armour type

### ISSUE THREAD

**Issue by SFFCorgi** [teelolws/Altoholic-Retail#103]
Perhaps this could be more radio buttons added to the class filter pick-list?  I've been using Altoholic to far-more-easily determine who gets the armour tokens from Black Empire drops.  If I could, say, show everybody of the right level who wear leather, all at the same time, instead of skipping back and forth between classes, it would save a little bit of aggravation.

With pre-patch and other occasions in the future with more of these BoA armour tokens, it might be pretty handy.

**Comment by teelolws** [comment]
In which section?

**Comment by SFFCorgi** [comment]
At the top of the window, there's a drop-down picklist using a pink-haired Gnome as the button image; it lets you sort your Summary results by class.  Adding four more radio buttons for Cloth, Leather, Mail and Plate would let you group your alts in a helpful way.

**Comment by teelolws** [comment]
Yeah okay.
![image](https://user-images.githubusercontent.com/49792789/93307062-b2dd2480-f854-11ea-8a20-7fcc4b00aa3d.png)

Added for Classic: https://github.com/teelolws/Altoholic-Classic/commit/cc5caf10d07e5068606a7ba25968306123511363

Retail will be coming in the Shadowlands update: 
![image](https://user-images.githubusercontent.com/49792789/93308396-50852380-f856-11ea-8f06-95082952e5d6.png)
https://github.com/teelolws/Altoholic-Retail/commit/ee4aea46c72b5034c4183ee85aaaa3efb871fabb

**Comment by SFFCorgi** [comment]
Wow, nice!  Thank you!
