### ISSUE TITLE
Enhancement Request: Separate Reputation-Section

### ISSUE THREAD

**Issue by Mcdrowd** [teelolws/Altoholic-Retail#104]
Hello,

it would be great, if Altoholic could be enhanced by an separate reputation-section, where some configurations should be possible.

- Overview of all Reputations with their values of progress
- Paragon-Support incl. the possibilty to track the values between 10.000 and 19.999
- Display of paragon-rewards, that hasn't been collected
- Disable Toons and/or Reputations via savable Project-Profiles

Background: I request to get help to organize some projects of getting specific class- , armorclass- or profession updates, which require specific reputations, but it is nearly not possible with doubled classes and multiple servers / factions.

kind regards
Mcdrowd

**Comment by teelolws** [comment]
Seems like the part thats important to you here is being able to see the Paragon caches of your characters next to each other. I could look into adding another section to Grids that functions similarly to the Reputation section but for Paragon?

Some users would want the Paragon in % form, some would want to see the actual number. I can make a toggle. If there is a cache waiting to collect, highlight it differently. And add a right-click menu to hide a reputation.

**Comment by Mcdrowd** [comment]
Hello Teelolws,

I took a look into the Grids section and this won't fullfil, what I had in mind.

At the time I have wrote the Request, I had in mind that a complete new section of reputation may be set to the summary-section. I like the profession-sction with its mouse-overs values for each Addon to plan for example something like how much cooking materials I need before I reached Legion-Cooking to 100 on every toon. The best way to bring the Legion-cooking to 100 is to get a revered reputation with the wardens.

Battle for Azeroth was for me a total Alt-Friendly Addon for collecting things from specific contents. After I had reached the goal to level all classes on both factions and all allied races to max Level, I have lost the overview.

Currently with the 100% reputation buff I work on getting all Legion-Order-Hall-Transmog-Sets for all missing 12 Classes and I am on ~2/3 to reach this goal. I ddidn't wanted only to login on toons (or use the App), looking for BOA-missions for nightfallen-reputation, so I decided to push all possible Legion-Reputations to get more BOA-Items from missions. Beside this I play some of the toons for example for killing worldbosses/emissary or get other collections. Then I lost the overview about how far the paragon-progress is to to send speific amount of BOA-Item and/or play a specific emissary-quest to this toon to get another Paragon-reward.

Side-Note: The plan to work on specific reputation projects has been born at the time, Blizzard announced the permanent 50% buff for Time-Walking events.

All in all I request a way to create specific projects (individual savable/deletable profiles) with specific toons and specific reputations (Check-boxes) with its reputation/paragon to see the values at one look.

**Comment by teelolws** [comment]
The summary section has a fixed number of columns: 5. If you only ever want to look at five paragons at a time, I can whip something up?

**Comment by Mcdrowd** [comment]
This sound good

It would be great, if I can for example save two profiles for Legion, two profiles for Battle for Azeroth or consolidate them, if have got the half of all Paragon-rewards from of specific reputations.
--> Quickly switch the profiles via a Dropdown would be great too.

And it should be possible, to "hide /show" toons for a specific project, meaning "Altoholic" should gather data in the background and if I don't need them for this project, they should be invisible, but not deleted.

**Comment by teelolws** [comment]
"Profiles" isn't really something that I can add to Altoholic. Its just not built for that.

If I add it to Summary, I can give you a dropdown to change which reputations are shown in each column. If I add it to Grids, I can give you a dropdown to switch between Legion and BFA (and then Shadowlands).

**Comment by Mcdrowd** [comment]
ok - In this case, we may have to move to the Grids-Section.

Before I made my last post here, I tested something in the "Grids-Section": My "toons", which I use less than others for reputation, are shown first. This causes, that I have to scroll to the right. If I deactivate "Toons" I still have to scroll and when I reach the first "Toon" everything is reset after deactivation.

An arrangement or really working hide/show function in the "Grids-Section" for both "Toons" and "reputation" would be great.

**Comment by teelolws** [comment]
So the deal with Grids is you can move the characters around. Just mouseover the class icon and you'll get a list of all your other characters on your account. Then you can change what you want on each column!

**Comment by Mcdrowd** [comment]
This sounds good.

Let's see how it turns out in the end.

I imagine it will be a good expansion for Altoholic, especially for the time Time-Walking-Events where there is more motivation for players to push the reputation and of cource for the paragontopic (please remeber to track values bewtween 10.000 --> 19999 too - the Blizzard-Interface can't show it, but there must be some code in the background)

**Comment by teelolws** [comment]
Hows this?

![image](https://user-images.githubusercontent.com/49792789/94208100-2a7a1600-ff1d-11ea-972e-7295394c57c0.png)

The first character is one I copied from live. It had various paragon reps. Valarjar is just 9000/10000. The Wardens is 15000/10000, with a cache waiting to collect, so its icon shows behind it.
The second+fourth+fifth characters are all Beta template characters. Their reps are all exactly 0/10000 Paragon.
The third is one I copied from live that doesn't have any of those factions at Exalted, so it shows no entry for them at all.

I had to round all the amounts down from "9333" to "9K" to make it fit in the small space while still being readable.

**Comment by Mcdrowd** [comment]
The approach with the Paragon and the symbol for the additional cache is great.

It would be good if we didn't limit ourselves to Paragon. Currently, the existing reputation section does contain Paragon, but I think it's very confusing.

Can you please leave the values as a shortened version (good idea), but include the reputation levels under Paragon and put the numbers (like 5K) with the colors of the reputation levels, as well as include a mouse-over with the used reputation level with its exact values? This would have the effect that we have everything at a glance.

**Comment by teelolws** [comment]
Whats the point of that? If you want all the full reputation details, why not just use the Reptuation section?

**Comment by Mcdrowd** [comment]
The point is that no section in "Altoholic" fulfills all wishes/requests.

Summery: No Reputation-display possible with more than 5 columns as discussed or in profiles for Projects.
Achievments-Section: highlighted symbols only at Exalted and only for available Reputation-Achievments.
Grid-Reputation: Numbers in the overview too small, no paragon-cache-support, highlighted symbols without recognizable benefit

And last but not least it is not possible to show/hide the characters and the reputation in a freely configurable way.

Of course you could also customize the grid reputation section, but maybe someone will use it in this form. I find it totally confusing.

**Comment by teelolws** [comment]
What if I just update Grids/Reputations to have bigger numbers (in the 13K form) and highlight paragon caches that are waiting for collection?

**Comment by teelolws** [comment]
This is what I'm thinking: 

![image](https://user-images.githubusercontent.com/49792789/94328242-ecf0b800-0004-11eb-8e4d-c700769f6979.png)

All of those are Paragon levels. The one with a "!" behind it means theres a Cache waiting for collection. Compare to reputations that aren't paragon levels:
![image](https://user-images.githubusercontent.com/49792789/94328254-009c1e80-0005-11eb-9f2a-131a1fac1b4b.png)
The checkmark meaning its Exalted and the rep doesn't have Paragon.

**Comment by Mcdrowd** [comment]
That goes into the right his goes in the direction I had imagined.

I still have a few questions about the pictures/descriptions.

1. Does a "red X" mean that this character has not yet discovered the respective faction?

2. Does the "percentage value" mean a progress per reputation level or the entire progress from hateful to exalted?

3. I generally conclude that if a Paragon has not yet been reached, a "Percentage value" is displayed - correct?

4. Will there be a mouseover showing the exact reputation level and the exact values?

Questions 3. and 4. are intended to ease the transition from non-Paragon to Paragon (if poosible), so that I can decide, for example, that I'd rather do an additonal world quest or use a small BOA reputation insignia than waste parts of an emissary quest or a large BOA reputation insignia in the 95-99% direction.

Note: I don't think the "percentage value" should be in gray color. A white color would be better here too. Before I had in mind that the number per reputation level should still be colored, but some colors of the currently used reputation levels rather worsen the overview. The symbol not highlighted in color is a good idea in this context.

**Comment by teelolws** [comment]
1. Yup!

2. Good question. Its actually the percentage through the current bracket. Its hard to notice on the picture I showed, but the colour of the text is different based on the rank. Neutral is a yellow colour, while friendly is greener. This is the list, but it can be hard to tell the difference when its text on top of a background picture:
![image](https://user-images.githubusercontent.com/49792789/94336542-24c52300-0038-11eb-95f1-98e0e47da617.png)

3. Yup. Percentage through the current bracket, if its exalted then a "tick", and if its paragon it shows the raw amount.

4. Yeah, this is the mouseover on Classic (I can't log onto the beta right now):
![image](https://user-images.githubusercontent.com/49792789/94336588-7c638e80-0038-11eb-8e72-b9f7a5016a42.png)

**Comment by Mcdrowd** [comment]
Very good.

Everything stands and falls with a good overview and all my wishes/requests should be a support for collection projects related to reputation.

I think, now we can dedicate ourselves to my last wish: Free configurable character and faction view.

Currently the following is possible in the "Grid-Reputation-Section":

- Display of all factions per addon or the guild or all factions
- Hiding a character, but then with a question mark column. You cannot hide the first character, because there is only a reset option.

I would like to have a real hide option with the possibility to show/reset everything again. In my opinion this can be done in two ways:
- Separate configuration menu with checkboxes to influence the whole "Grid-Reputation-Section". The factions and Characters are then automatically moved together, so no gaps. Reset-Option in the Configuration menu.
- Hide factions for each existing selection (Addon/Guild/All). Right click on a faction --> Menu --> Hide. The factions are then automatically moved together, so there are no gaps. Hide characters and they should be automatically moved together, so no gaps. Automatic saving of the current view and resetting by selecting the selection option again (Addon/Guild/All).


Examples:

- When I'm done collecting all four armor sets from the Chromie faction, this should be hideable. The same would be the case for the armor set parts that need certain factions in Burning Crusade.
- If I have all the extra rewards from a Paragon faction, then I want to decide whether to hide it or not.

**Comment by teelolws** [comment]
A way to change up which reputations are shown would be nice, but it is a bit out of the scope of the project. I can add it to a "wishlist" for the future, but might be a long time before I implement it, as it would take a significant overhaul to how Grids works.

My suggestion for you, is you change the data file. If you open up AddOns\Altoholic_Grids\Grid_Reputations.lua, you'll see a bit that looks like this:
![image](https://user-images.githubusercontent.com/49792789/94339998-6b277b80-0052-11eb-9cb3-914a0620647c.png)

If you delete the line you no longer want to track anymore, it'll be gone until you update the addon again.

A bit annoying but thats the best I can offer for now.

**Comment by teelolws** [comment]
I'll look into making it so when you set a column to "None" it moves all the ones to its right left a column.

**Comment by Mcdrowd** [comment]
All right. I thank you for your time and that I could contribute to the expansion of "Altholic".

I'm excited to see the currently possible changes in the live environment.

Reputation projects are mostly long term projects, especially if they are planned with 9-12 different classes depending on the addon or in a time walking event with the 50% buff.So please add the change option to show factions in a different way to the wish list.

**Comment by teelolws** [comment]
Rather than messing with the Reputations Grid, I came up with a better idea: add Paragons to Grids/Tasks.

This is a section I created a while back where you can customize what gets listed. Pick Grids/Tasks with this button:
![image](https://user-images.githubusercontent.com/49792789/94625635-b7561280-0315-11eb-80c5-46d49f8a7d8d.png)

Then customize your tasks list with:
![image](https://user-images.githubusercontent.com/49792789/94625664-cb9a0f80-0315-11eb-958f-acf60c4e49c1.png)

And reputations can be setup like this:
![image](https://user-images.githubusercontent.com/49792789/94625715-eb313800-0315-11eb-9152-f3f333c29d55.png)

Tracking it across your characters will look like this:
![image](https://user-images.githubusercontent.com/49792789/94625566-84138380-0315-11eb-8f38-41904995b95e.png)
The top two are rare spawns, and the third is tracking one of my paragon reputations. As before, the "0K" are all 0/10000 Paragon, while the one with an X isn't Exalted yet. The one with an icon behind it has a chest waiting for collection.

As you can see in one of the pictures above, the Tasks section also supports profiles.

**Comment by Mcdrowd** [comment]
This is an interesting alternative

Do I understand that you tested with the Paragon theme first, but the system would be applicable to all factions in all addons? The described %-value indicates this.

And one more question: How may I understand the "profiles"? Something like this?

1. different tasks with the same characters and hiding the characters you don't need in "all" profiles including the theme that no gaps should appear after hiding.

or

2. different sets of characters with individual tasks

If I could decide, I would take the second point, simply because there are collection projects where you need all twelve main classes (spread over alliance/horde and/or different realms) or only the four armor classes or only chakters with certain professions where reputation is needed for recipes.

My situation is that I have all classes at max level on both Alliance and Horde, but my main classes for reputation are spread over two realms.

**Comment by teelolws** [comment]
I'm going to leave it for Paragon, only. Because regular reputations to exalted is a one-and-done thing, but people generally keep farming Paragon caches for their low droprate stuff. If you want to track regular reputations, just use Grids/Reputations instead.

The profile is just a basic implementation. That dropdown menu will swap out all your tasks for an empty set that you can populate. Its for the rows, only.

Remember: you can use these buttons at the bottom:
![image](https://user-images.githubusercontent.com/49792789/94631886-8978ca00-0325-11eb-86ff-d41ab77b8dbd.png)
to check more than 12 characters. And the dropdown on the left defaults to your account, but you can narrow it down to a server:
![image](https://user-images.githubusercontent.com/49792789/94631904-9c8b9a00-0325-11eb-9b25-c69a1ce567da.png)

**Comment by Mcdrowd** [comment]
I am a bit disillusioned at the moment, but let's see how it turns out in the end.

Using a scrollbar on 31 max-level characters, which are also distributed across Horde and Alliance and various servers, is no added value for me. Focusing on a realm is not sufficient for my case.

**Comment by teelolws** [comment]
The window is now resizable which should help you with your scrollbar problem.
