### ISSUE TITLE
No played time on any character?

### ISSUE THREAD

**Issue by SarahT89** [teelolws/Altoholic-Retail#106]
This issue appeared for me a few weeks ago - I've tried reinstalling the addon multiple times and I am stuck, but it appears altoholic is no longer tracking my played time on any character. They are all listed as 0d, 0h and 0m. This doesn't seem to be happening with any other data and other users are reporting they don't have this issue. What do I need to delete and reset so that it can start telling me my played time again?

**Comment by teelolws** [comment]
Did you accidentally right-click on one of the played times? Another player wanted the option to turn played time off, so right-clicking it hides it:

On:
![image](https://user-images.githubusercontent.com/49792789/93640690-1c288780-fa4f-11ea-88d0-77e7274121c1.png)

Right click the played time, off:
![image](https://user-images.githubusercontent.com/49792789/93640716-23e82c00-fa4f-11ea-9c56-3e51dffabd0c.png)

**Comment by SarahT89** [comment]
Oh amazing, thank you - that fixed it! 👍
