### ISSUE TITLE
Grids - Guild reputation not working

### ISSUE THREAD

**Issue by RaidriDE** [teelolws/Altoholic-Retail#107]
Choosing the Guild reputation in the drop-down-menu under Grids - Reputations doesn't work and gives this Lua error:

Altoholic_Grids\Grid_Reputations.lua:402: attempt to call method 'GetRealm' (a nil value)
[string "@Altoholic_Grids\Grid_Reputations.lua"]:402: in function `func'
[string "@Altoholic\Templates\DropDownMenu.lua"]:49: in function `OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 checked = false
 func = <function> defined @Altoholic_Grids\Grid_Reputations.lua:396
 ColorSwatch = <unnamed> {
 }
 ExpandArrow = <unnamed> {
 }
 value = 8
 OnClick = <function> defined @Altoholic\Templates\DropDownMenu.lua:13
 InvisibleButton = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 GetName = <function> defined @Altoholic\Templates\DropDownMenu.lua:58
 GetButtonWidth = <function> defined @Altoholic\Templates\DropDownMenu.lua:61
 GetChecked = <function> defined @Altoholic\Templates\DropDownMenu.lua:55
 NormalText = <unnamed> {
 }
 arg1 = 8
 Check = <unnamed> {
 }
 Icon = <unnamed> {
 }
 UnCheck = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = AltoholicTabGrids {
 Corruption = <unnamed> {
 }
 SetViewDDMText = <function> defined @Altoholic_Grids\TabGrids.lua:176
 Tasks = <unnamed> {
 }
 SelectAccount = <unnamed> {
 }
 currentGridID = 2
 Label1 = <unnamed> {
 }
 Archeology = <unnamed> {
 }
 TextView = <unnamed> {
 }
 Essences = <unnamed> {
 }
 Sets = <unnamed> {
 }
 Equipment = <unnamed> {
 }
 Emissaries = <unnamed> {
 }
 Update = <function> defined @Altoholic_Grids\TabGrids.lua:46
 GarrisonArchitect = <unnamed> {
 }
 SelectView = <unnamed> {
 }
 Status = <unnamed> {
 }
 Dailies = <unnamed> {
 }
 InitializeGrid = <function> defined @Altoholic_Grids\TabGrids.lua:40
 0 = <userdata>
 GetAccount = <function> defined @Altoholic_Grids\TabGrids.lua:179
 TradeSkills = <unnamed> {
 }
 RegisterGrid = <function> defined @Altoholic_Grids\TabGrids.lua:37
 OnBind = <function> defined @Altoholic_Grids\TabGrids.lua:12
 SetStatus = <function> defined @Altoholic_Grids\TabGrids.lua:173
 UpdateMenuIcons = <function> defined @Altoholic_Grids\TabGrids.lua:132
 Dungeons = <unnamed> {
 }
 Tokens = <unnamed> {
 }
 GarrisonFollowers = <unnamed> {
 }
 ContextualMenu = <unnamed> {
 }
 BuildingLevelTooltip = <unnamed> {
 }
 OrderHallFollowers = <unnamed> {
 }
 FollowerAbilities = <unnamed> {
 }
 ClassIcons = <unnamed> {
 }
 Factions = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'GetRealm' (a nil value)"
dropDownFrame = <unnamed> {
 0 = <userdata>
 SetText = <function> defined @Altoholic\Templates\DropDownMenu.lua:1027
 GetCurrentOpenMenuValue = <function> defined @Altoholic\Templates\DropDownMenu.lua:1099
 SetSelectedValue = <function> defined @Altoholic\Templates\DropDownMenu.lua:1059
 AddButtonInfo = <function> defined @Altoholic\Templates\DropDownMenu.lua:675
 GetText = <function> defined @Altoholic\Templates\DropDownMenu.lua:1030
 AddCloseMenu = <function> defined @Altoholic\Templates\DropDownMenu.lua:961
 ClearAll = <function> defined @Altoholic\Templates\DropDownMenu.lua:655
 Middle = <unnamed> {
 }
 GetSelectedName = <function> defined @Altoholic\Templates\DropDownMenu.lua:1056
 SetButtonWidth = <function> defined @Altoholic\Templates\DropDownMenu.lua:1019
 AddTitle = <function> defined @Altoholic\Templates\DropDownMenu.lua:971
 Initialize = <function> defined @Altoholic\Templates\DropDownMenu.lua:520
 IsEnabled = <function> defined @Altoholic\Templates\DropDownMenu.lua:994
 noResize = 1
 AddButtonWithArgs = <function> defined @Altoholic\Templates\DropDownMenu.lua:942
 Close = <function> defined @Altoholic\Templates\DropDownMenu.lua:981
 SetSelectedID = <function> defined @Altoholic\Templates\DropDownMenu.lua:1069
 displayMode = "MENU_NO_BORDERS"
 Toggle = <function> defined @Altoholic\Templates\DropDownMenu.lua:563
 Icon = <unnamed> {
 }
 initialize = <function> defined @Altoholic_Grids\Grid_Reputations.lua:428
 GetSelectedID = <function> defined @Altoholic\Templates\Dro

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/29c887fb0117c66bacb197d0b5aaf2b19f352506

**Comment by RaidriDE** [comment]
Thanks
