### ISSUE TITLE
Feature Request: Rare kill tracking in Tasks for mounts and toys

### ISSUE THREAD

**Issue by MollaneGreed** [teelolws/Altoholic-Retail#109]
In the same way there are custom tasks for daily quests and world bosses, would it be possible to add a new type that would allow the tracking of daily rare kills? An example of this would be Rustfeather for the Junkheap Drifter.

**Comment by teelolws** [comment]
Yeah this was something I originally wanted to add but theres no built-in way to track rare kills. I'd have to create a new DataStore module to track rares, and only ones that have Daily Quests attached would even work, from Legion onwards. Its on my list, just not a priority.

**Comment by MollaneGreed** [comment]
Thanks for the quick reply, and the explanation. I've been manually tracking my kills, so  can easily wait for the priorities to be taken care of.

**Comment by teelolws** [comment]
If you've got Beta or PTR access, its partially implemented now: https://github.com/teelolws/Altoholic-Retail/tree/Badowlands

![image](https://user-images.githubusercontent.com/49792789/94384944-4f31f000-01a0-11eb-8d7b-2f4fef69bc0c.png)

![image](https://user-images.githubusercontent.com/49792789/94384958-578a2b00-01a0-11eb-83a2-8bbaf8249c45.png)

It takes a while to add each batch of rare data. So far I've added the Arathi Warfront, Uldum, and Vale rares. I'll aim to have the rest ready before 9.0 prepatch.

**Comment by MollaneGreed** [comment]
That's fantastic! I do have access to the PTR so I'll be sure to get in there and check it out as soon as I can.

**Comment by teelolws** [comment]
Finished. Made a section in grids for it, too:

![image](https://user-images.githubusercontent.com/49792789/94527221-25a5c100-0293-11eb-8385-0c6e915625d9.png)

Though it doesn't look to good; theres no icons I can use for them all.

I mostly used various handynotes plugins to make the list of rares. So I'll add one for Shadowlands when theres a handynotes for it out there.

![image](https://user-images.githubusercontent.com/49792789/94527377-5ede3100-0293-11eb-91eb-2c6e3dc06eed.png)

Added in: https://github.com/teelolws/Altoholic-Retail/commit/7d16e512749e7646fdac9e10f7ec0b93f2e3e89b
