### ISSUE TITLE
Error with Pre-Release

### ISSUE THREAD

**Issue by MetalHeadSeven** [teelolws/Altoholic-Retail#11]
I only get this error on login and when changing realms.  I don't get it when switching characters on the same realm.

1x ...eDataStore_Inventory\DataStore_Inventory-r55.lua:196: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@DataStore_Inventory\DataStore_Inventory-r55.lua"]:196: in function <...eDataStore_Inventory\DataStore_Inventory.lua:180>
[string "@DataStore_Inventory\DataStore_Inventory-r55.lua"]:212: in function <...eDataStore_Inventory\DataStore_Inventory.lua:207>
[string "@DataStore_Inventory\DataStore_Inventory-r55.lua"]:313: in function <...eDataStore_Inventory\DataStore_Inventory.lua:312>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by teelolws** [comment]
Are you getting this on the most recent pre-release? I made a change to it yesterday because I was having this issue. It seems to be fixed for me now.

**Comment by MetalHeadSeven** [comment]
I'm using the version I got the notification about testing.

DataStore_Inventory Version: r55

**Comment by MetalHeadSeven** [comment]
I just updated to your latest version and issue is gone.

**Comment by teelolws** [comment]
Okay, cool. Yeah that was an issue I realised after I uploaded the prerelease.
