### ISSUE TITLE
Problem with Altoholic and Datastore - Characters Module

### ISSUE THREAD

**Issue by Anni101** [teelolws/Altoholic-Retail#113]
I've been having a consistent error with the game.

With the data store characters module enabled, if you access a vendor, one of the items tooltip (generally the 1st one that gets hovered over) remains stuck on the screen covering everything.  Only a reload UI will get rid of it.  The following error accompanies it.

Date: 2020-10-06 02:30:18
ID: 4
Error occured in: Global
Count: 1
Message: ...AddOns\DataStore_Characters\DataStore_Characters.lua line 168:
   attempt to index field '?' (a nil value)
Debug:
   [string "@DataStore_Characters\DataStore_Characters.lua"]:168:
      ...AddOns\DataStore_Characters\DataStore_Characters.lua:167
   [string "=(tail call)"]: ?
   [string "@Altoholic\Tooltip.lua"]:517: GetRecipeOwners()
   [string "@Altoholic\Altoholic.lua"]:298: MerchantFrame_UpdateMerchantInfo()
   [string "@..\FrameXML\MerchantFrame.lua"]:135: MerchantFrame_Update()
   [string "@..\FrameXML\MerchantFrame.lua"]:97:
      ..\FrameXML\MerchantFrame.lua:87
   [string "=[C]"]: Show()
   [string "@..\FrameXML\UIParent.lua"]:2740: SetUIPanel()
   [string "@..\FrameXML\UIParent.lua"]:2585: ShowUIPanel()
   [string "@..\FrameXML\UIParent.lua"]:2453:
      ..\FrameXML\UIParent.lua:2449
   [string "=[C]"]: SetAttribute()
   [string "@..\FrameXML\UIParent.lua"]:3307: ShowUIPanel()
   [string "@..\FrameXML\MerchantFrame.lua"]:34:
      ..\FrameXML\MerchantFrame.lua:26
Locals:
character = <table> {
 lastUpdate = 1601944206
 played = 2920084
 playedThisLevel = 280706
 lastLogoutTimestamp = 1601944206
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.7 
  Altoholic, v8.3.7.043
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Bartender4, v4.9.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Coordinates, v2.03
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreKeystones, vv8.3-008
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.34
  DBMDefaultSkin, v
  DBMSpellTimers, vr124
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  GatherMate2, v1.45.6
  Gladius, v6.2.1
  HandyNotes, vv1.5.2
  Informant, v8.2.6508 (SwimmingSeadragon)
  OmniBar, vv10.8
  Postal, vv3.6.0
  SaySapped, v2013-10-01
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.14.1.80000
  TitanBag, v5.14.1.80000
  TitanClock, v5.14.1.80000
  TitanGold, v5.14.1.80000
  TitanGoldTracker, v4.3.7.30300
  TitanLocation, v5.14.1.80000
  TitanLootType, v5.14.1.80000
  TitanPerformance, v5.14.1.80000
  TitanRepair, v5.14.1.80000
  TitanVolume, v5.14.1.80000
  TitanXP, v5.14.1.80000
  VuhDo, v3.113
  VuhDoOptions, v3.113
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=843)

I've been disabling the datastore characters module to fix it... but kind of defeats the purpose.  Hope you can shed a light on the mystery.

**Comment by teelolws** [comment]
It looks like you have corrupted or outdated data. You should probably just delete all the altoholic and datastore files you'll find in the _retail_\WTF\Account\ACCOUNT\SavedVariables folder and start again. Make sure you close WoW first.

![image](https://user-images.githubusercontent.com/49792789/95146365-1fa36900-07da-11eb-918d-d0ac30170035.png)

**Comment by Anni101** [comment]
That did the trick.  Thanks, it has been vexing me for sometime.

**Comment by teelolws** [comment]
Yeah it was probably a deleted character or something with bad data.
