### ISSUE TITLE
Dropdown error (Character tab)

### ISSUE THREAD

**Issue by swampers** [teelolws/Altoholic-Retail#114]
I get an error on hovering over the Exclamation Mark icon (quest icon) on the Characters tab, and no dropdown menu. (That's the third one over, between Containers and Talents) - none of the other hovers cause this behaviour.

I think this may be due to only having one character on the Beta at the moment (quite the edge case for 'Altoholic'!)

Lua Error:

Message: ...erface\AddOns\Altoholic_Characters\TabCharacters.lua:505: bad argument #1 to 'pairs' (table expected, got no value)
Time: Tue Oct  6 07:50:10 2020
Count: 8
Stack: ...erface\AddOns\Altoholic_Characters\TabCharacters.lua:505: bad argument #1 to 'pairs' (table expected, got no value)
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\Altoholic_Characters\TabCharacters.lua"]:505: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:1055: in function `ToggleDropDownMenu'
[string "@Interface\AddOns\Altoholic_Characters\TabCharacters.lua"]:874: in function `Icon_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "table expected, got no value"
 = <function> defined =[C]:-1

**Comment by teelolws** [comment]
Does it still do this after a relog?

**Comment by teelolws** [comment]
Same issue as https://github.com/teelolws/Altoholic-Retail/issues/115 - DataStore_Quests not installed or enabled.
