### ISSUE TITLE
Grids tab issues

### ISSUE THREAD

**Issue by swampers** [teelolws/Altoholic-Retail#115]
I've brought up the currency tab on the character pane in-game, but Altoholic isn't updating the currency option on its Grids tab.

Again, only one character on Beta at the moment, so that might be part of the issue?  Seems to be working for most of the other options on Grids tab.

Dungeon Finder tab comes up with the following Lua Error: 

> Message: Interface\AddOns\Altoholic_Grids\Grid_Dungeons.lua:492: bad argument #1 to 'pairs' (table expected, got no value)
> Time: Tue Oct  6 08:02:55 2020
> Count: 2
> Stack: Interface\AddOns\Altoholic_Grids\Grid_Dungeons.lua:492: bad argument #1 to 'pairs' (table expected, got no value)
> [string "=[C]"]: in function `pairs'
> [string "@Interface\AddOns\Altoholic_Grids\Grid_Dungeons.lua"]:492: in function `ColumnSetup'
> [string "@Interface\AddOns\Altoholic_Grids\TabGrids.lua"]:109: in function `Update'
> [string "*:OnClick"]:6: in function <[string "*:OnClick"]:1>
> 
> Locals: (*temporary) = "table expected, got no value"
>  = <function> defined =[C]:-1

Callings gets a similar error: 

> Message: Interface\AddOns\Altoholic_Grids\Grid_Callings.lua:38: bad argument #1 to 'pairs' (table expected, got no value)
> Time: Tue Oct  6 08:04:13 2020
> Count: 1
> Stack: Interface\AddOns\Altoholic_Grids\Grid_Callings.lua:38: bad argument #1 to 'pairs' (table expected, got no value)
> [string "=[C]"]: in function `pairs'
> [string "@Interface\AddOns\Altoholic_Grids\Grid_Callings.lua"]:38: in function <Interface\AddOns\Altoholic_Grids\Grid_Callings.lua:29>
> [string "@Interface\AddOns\Altoholic_Grids\Grid_Callings.lua"]:89: in function `OnUpdate'
> [string "@Interface\AddOns\Altoholic_Grids\TabGrids.lua"]:58: in function `Update'
> [string "*:OnClick"]:6: in function <[string "*:OnClick"]:1>
> 
> Locals: (*temporary) = "table expected, got no value"
>  = <function> defined =[C]:-1

And Rare Spawns gets a far stranger one:

> Message: Interface\AddOns\Altoholic_Grids\Grid_Rares.lua:114: attempt to index a nil value
> Time: Tue Oct  6 08:05:00 2020
> Count: 1
> Stack: Interface\AddOns\Altoholic_Grids\Grid_Rares.lua:114: attempt to index a nil value
> [string "@Interface\AddOns\Altoholic_Grids\Grid_Rares.lua"]:114: in function `InitViewDDM'
> [string "@Interface\AddOns\Altoholic_Grids\TabGrids.lua"]:41: in function `InitializeGrid'
> [string "*:OnClick"]:5: in function <[string "*:OnClick"]:1>
> 
> Locals: frame = <unnamed> {
>  0 = <userdata>
>  SetText = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1027
>  GetCurrentOpenMenuValue = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1099
>  SetSelectedValue = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1059
>  AddButtonInfo = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:675
>  GetText = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1030
>  AddCloseMenu = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:961
>  ClearAll = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:655
>  Middle = <unnamed> {
>  }
>  GetSelectedName = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1056
>  SetButtonWidth = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1019
>  AddTitle = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:971
>  Initialize = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:520
>  IsEnabled = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:994
>  noResize = 1
>  AddButtonWithArgs = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:942
>  Close = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:981
>  SetSelectedID = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1069
>  displayMode = "MENU_NO_BORDERS"
>  Toggle = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:563
>  Icon = <unnamed> {
>  }
>  initialize = <function> defined @Interface\AddOns\Altoholic_Grids\Grid_Archeology.lua:15
>  GetSelectedID = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1075
>  SetMenuWidth = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1004
>  Text = <unnamed> {
>  }
>  AddCategoryButton = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:953
>  DisableDropDown = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:984
>  Refresh = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:567
>  CreateInfo = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:671
>  Right = <unnamed> {
>  }
>  Left = <unnamed> {
>  }
>  SetSelectedName = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1050
>  Button = <unnamed> {
>  }
>  AddButton = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:932
>  EnableDropDown = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:989
>  SetAnchor = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:997
>  GetSelectedValue = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1066
>  JustifyText = <function> defined @Interface\AddOns\Altoholic\Templates\DropDownMenu.lua:1033
> }
> title = <unnamed> {
>  0 = <userdata>
> }
> currentRareSet = "ArathiWarfront"
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = <table> {
>  SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
>  ToggleOption = <function> defined @Interface\AddOns\DataStore\Options.lua:153
>  DeleteCharacter = <function> defined @Interface\AddOns\DataStore\DataStore.lua:547
>  EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
>  modules = <table> {
>  }
>  baseName = "

**Comment by teelolws** [comment]
Did you, perhaps, just install Altoholic then hit /reload? Altoholic doesn't gather data when you reload the UI, only when you first login. These errors all look like "can't find any data" errors.

**Comment by teelolws** [comment]
Okay, I was able to recreate your Rares error by disabling one of the DataStore modules:

![image](https://user-images.githubusercontent.com/49792789/95170423-e4705c80-0810-11eb-82d4-540ae83d1648.png)


![image](https://user-images.githubusercontent.com/49792789/95170440-ec300100-0810-11eb-9adb-3c70d6c22d05.png)

I'll just throw in some checks to make sure you have them turned on.

**Comment by swampers** [comment]
Relogging got rid of all the errors except the Rares one.

Datastore_Rares isn't present to be enabled.  I'm using WoWup.io to install the beta branch of the addon (rather than copying over from Retail to Beta) and it looks like it's not part of the package there.

That explains the issue. I think you can close this now.

**Comment by teelolws** [comment]
Oh. Yes, DataStore_Rares is missing from the .zip. I'd better fix that.

**Comment by teelolws** [comment]
Fixes released in: https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.1-000-BETA-B
And on curseforge: https://www.curseforge.com/wow/addons/altoholic-retail/files/3073146
