### ISSUE TITLE
Set Default Realm filter, on Achievements & Grids tabs, to "current realm"

### ISSUE THREAD

**Issue by Ruffz** [teelolws/Altoholic-Retail#117]
Hi,

Could you set default filter to "current realm" (like Thaoky's version) or, at least, make it remember user choice ?

As an Altoholic, I have many Alliance alts on one realm and many Horde alts on another, default filter "This account" mix them all.

**Comment by teelolws** [comment]
Yeah thats coming in the Shadowlands patch. https://github.com/teelolws/Altoholic-Retail/commit/556dc3ecaaefe79ff0341453c3c5c993e660867a
