### ISSUE TITLE
Instance reset is an hour early

### ISSUE THREAD

**Issue by DoctorShades24** [teelolws/Altoholic-Retail#119]
Instance reset is an hour early.
<img width="1792" alt="Screen Shot 2020-10-09 at 8 49 37 AM" src="https://user-images.githubusercontent.com/72614391/95591648-31208700-0a0d-11eb-8f31-7b7e3b0d53e5.png">

**Comment by teelolws** [comment]
Latest patch should solve this. Please confirm its sorted now.
