### ISSUE TITLE
Feature Request: Ability to resize the window

### ISSUE THREAD

**Issue by panoplybez** [teelolws/Altoholic-Retail#122]
Would it be possible to allow resizing of the altoholic window? When you have a lot of alts on a server, it would be nice to be able to make the window taller, for example. Or wider for when you're looking at the Grids pane. I didn't see any way to drag the bottom corner of the window to fiddle with size.

**Comment by teelolws** [comment]
I've got a work in progress ready for testing in the latest release.

To try it, run this code:

`/run AltoholicFrameResizeButton:Show()`

**Comment by panoplybez** [comment]
so it works great!
I know its WIP - so I saw it has a cap on size, and also that most of the other tabs don't resize to fit it yet :) But, the slider was there and I could drag it around and see it resize!

**Comment by teelolws** [comment]
> also, when you first click the resizer, before you even start dragging, just a single click, makes the window jump to the widest setting

Yeah it can be a bit weird sometimes. It uses the same code from Chat Frames, which do the same thing. So maybe one day Blizzard will fix it...

**Comment by teelolws** [comment]
The latest beta has this fully ready for testing. If theres any issues with it, create a new ticket.
