### ISSUE TITLE
9.0.1-002  Beta Errors

### ISSUE THREAD

**Issue by MetalHeadSeven** [teelolws/Altoholic-Retail#123]
Getting these errors on Beta.

1x Altoholic\Tooltip.lua:12: Cannot find a library instance of "LibGatheringNodes-1.0".
[string "=[C]"]: in function `error'
[string "@DataStore\libs\libstub\libstub.lua"]:23: in function `LibStub'
[string "@Altoholic\Tooltip.lua"]:12: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibGatheringNodes-1.0"."

1x Altoholic\Altoholic-9.0.1-002.lua:349: attempt to call method 'InitTooltip' (a nil value)
[string "@Altoholic\Altoholic-9.0.1-002.lua"]:349: in function <Altoholic\Altoholic.lua:342>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

4x Couldn't open Altoholic\libs\LibGatheringNodes-1.0\LibGatheringNodes-1.0.xml

**Comment by teelolws** [comment]
Good catch. Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/cf9c70ab2112ca488216d85f91191c7290d7a170
