### ISSUE TITLE
Error in the grids tab when the cursor hover on a class icon 

### ISSUE THREAD

**Issue by Daedrias** [teelolws/Altoholic-Retail#125]
![image](https://user-images.githubusercontent.com/13920212/96008309-6eba5100-0e0d-11eb-81f7-5aafe5f4ec93.png)

Message: Interface\AddOns\Altoholic\Templates\ClassIcon.lua:170: bad argument #3 to 'format' (number expected, got no value)
Time: Wed Oct 14 10:58:40 2020
Count: 1
Stack: Interface\AddOns\Altoholic\Templates\ClassIcon.lua:170: bad argument #3 to 'format' (number expected, got no value)
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\Altoholic\Templates\ClassIcon.lua"]:170: in function `DrawTooltip'
[string "@Interface\AddOns\Altoholic\Templates\ClassIcon.lua"]:102: in function `Icon_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "Average iLevel: %s%.1f"
(*temporary) = ""
(*temporary) = "number expected, got no value"

**Comment by teelolws** [comment]
Thats happening because you disabled DataStore_Inventory:
![image](https://user-images.githubusercontent.com/49792789/96033533-ab915100-0ebc-11eb-9307-4e5465d1de42.png)

Added a check for that in: https://github.com/teelolws/Altoholic-Retail/commit/d49cb4a64bf2af6aa27069f203b3ab21d16411d5
