### ISSUE TITLE
Empty window on login?

### ISSUE THREAD

**Issue by panoplybez** [teelolws/Altoholic-Retail#126]
Honestly I am a bit unclear who or where this is coming from since its an invisible window, but the error that I get when I close it is the following:

Message: ...c\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua:31: attempt to call method 'Fire' (a nil value)
Time: Wed Oct 14 15:30:52 2020
Count: 1
Stack: ...c\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua:31: attempt to call method 'Fire' (a nil value)
[string "=[C]"]: in function `Fire'
[string "@Interface\AddOns\Altoholic\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:31: in function <...c\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua:30>
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\Altoholic\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:87: in function `Hide'
[string "@Interface\AddOns\Altoholic\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:36: in function <...c\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua:34>

Locals: 

![2020-10-14_15-30-41](https://user-images.githubusercontent.com/52841691/96036531-9bcd2a80-0e32-11eb-84df-ca7dd38287cb.jpg)
Could this be from Altoholic?

**Comment by teelolws** [comment]
There are a lot of addons that use AceGUI that haven't been updated yet. It'll just be a coincidence that Altoholic is the first to load, putting Altoholic in your error message.

Try turning off "Load Out Of Date Addons" and check that the issue has gone away. If it has, you know its one of those out-dated addons.

**Comment by panoplybez** [comment]
Sadly, it wasn't one of those. Unchecking that box didn't change the behavior. Its something else :( I will poke around and see.

**Comment by panoplybez** [comment]
I figured it out! What was happening is that Gnosis was trying to open a window telling me I had no config, but then Elvui was trying to skin that window (not sure why, I don't use skins) which turned into an invisible wall. Jeez. I was mind blown that this was only happening on some, not all toons.  Anyway, thanks for the pointer.
