### ISSUE TITLE
LUA error when hovering over Missions column on Activity Tab

### ISSUE THREAD

**Issue by nearlysober80** [teelolws/Altoholic-Retail#127]
Version 9.0.1-007 installed, I'm still seeing a DataStore error with DataStore_Garrison.lua whenever I mouse over the Missions column on the Activity tab.

Message: ...e\AddOns\DataStore_Garrisons\DataStore_Garrisons.lua:978: attempt to get length of field '?' (a nil value)
Time: Wed Oct 14 21:28:46 2020
Count: 15
Stack: ...e\AddOns\DataStore_Garrisons\DataStore_Garrisons.lua:978: attempt to get length of field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore_Garrisons\DataStore_Garrisons.lua"]:978: in function <...e\AddOns\DataStore_Garrisons\DataStore_Garrisons.lua:977>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Altoholic_Summary\AccountSummary.lua"]:1598: in function <...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:1541>

Locals:

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/d9dd7473142da7f1618a7bd246c4d90529f0d7a9

It'll be released in a future patch. I'm currently working on a few other issues.
