### ISSUE TITLE
Remove guild I have no characters in

### ISSUE THREAD

**Issue by alwaysladyred** [teelolws/Altoholic-Retail#129]
I cannot figure out how to remove a guild's inventory from showing when I mouseover items in my bags.  This is a guild that I am no longer a member of.  I DO want to be able to see what my other guilds have, so I don't want to select the options that do not show guilds at all.  Just delete the one I am no longer a member of.  Does that make sense?  Help, please!

**Comment by teelolws** [comment]
Like this:

![image](https://user-images.githubusercontent.com/49792789/96193262-4f096100-0fa4-11eb-88a8-8fc3dd2d51c4.png)

**Comment by alwaysladyred** [comment]
It worked!  Now I know what to click on.  Thank you!!
