### ISSUE TITLE
[Feature Request] Include mail backlog count in the Summary/Activity tab

### ISSUE THREAD

**Issue by fzarr** [teelolws/Altoholic-Retail#13]
Currently, the mailbox mail count in the Altoholic window is limited to 100 mails. However, TSM can query for the number of mails that are 'hidden' in the backlog. It would be great if Altoholic could also query this count and use it instead of the count of 'visible' mails.

**Comment by teelolws** [comment]
I don't use TSM. Does it just know the "quantity" in the backlog or does it somehow actually know whats in them all?

**Comment by teelolws** [comment]
Scratch that. Should be pretty simple to do. I don't have a mailbox full of a hundred mail to test it with. Can you please grab the updated DataStore_Mails.lua from the main page here and test if it works?

![image](https://user-images.githubusercontent.com/49792789/77272429-19560f80-6d16-11ea-9359-9010e42a3c0a.png)

**Comment by fzarr** [comment]
Hi @teelolws - thank you, I tested it in the new Altoholic and it now displays the count correctly.

It might be an idea to set the text to something like 'Backlogged mail, no details'. The expiry time being set to 30 days is also a bit misleading, but i guess there's not much you can do about it. The most you could do is set it to be the same as the last readable mail in the inbox as it will probably expire before that one.

**Comment by teelolws** [comment]
Yeah I can do that. The days left of the last readable mail is still visible, so its simple enough:

![image](https://user-images.githubusercontent.com/49792789/77794891-84fefa80-70d1-11ea-8b4e-9c0fc4cd3310.png)
