### ISSUE TITLE
https://www.curseforge.com/wow/addons/altoholic-retail

### ISSUE THREAD

**Issue by Vragen1** [teelolws/Altoholic-Retail#131]
Altoholic not working and give the above site BUT ace keeps attempting to update repeatedly. I tink I cleaned my cash. IBB 
![altoholic addon](https://user-images.githubusercontent.com/33770891/96300232-0ce31e00-0faa-11eb-84de-3fef0b3ea190.jpg)

**Comment by teelolws** [comment]
Uninstall both versions, then reinstall this one.

**Comment by Aloysius69** [comment]
I had the same screen so I uninstalled both versions and reinstall the retail version.
Then I had this:
![Image1](https://user-images.githubusercontent.com/7192306/96334750-53e91600-1073-11eb-9d51-5adf83fac9ad.png)

So, I deactivate all addons and it worked again. And then, I reactivate all addons and it still worked.
Only remaining glitch: I can't add any name in the drop down character list on achievement and grids tab (so basically, these 2 tabs doesn't work).

**Comment by teelolws** [comment]
Got all the DataStore modules installed and enabled?

**Comment by Aloysius69** [comment]
As far as i know, yes. 19

**Comment by teelolws** [comment]
You might have to just clear out your Altoholic and DataStore saved variables.

If the data is important to you, .zip them up and upload them. But I won't be able to investigate until tomorrow.

**Comment by Aloysius69** [comment]
You were right, it fixed it. thanks.
