### ISSUE TITLE
"DataStore_Rares/DataStore_Rares.toc" contains unrendered variable

### ISSUE THREAD

**Issue by torkus** [teelolws/Altoholic-Retail#133]
Altoholic `9.0.1-stub` downloaded from Curseforge today has a bundled addon `DataStore_Rares` whose `.toc` file looks like this:

```
0 ✓ (1.168s) 11:50:54 baz $ cat DataStore_Rares/DataStore_Rares.toc 
## Interface: 90001
## Title: DataStore_Rares
## Notes: Stores information about rare spawns killed
## Author: Teelo (Jubei'thos - US)
## Version: @project-version@
## Dependencies: DataStore
## OptionalDeps: Ace3
## SavedVariables: DataStore_RaresDB
## X-Category: Interface Enhancements
## X-Embeds: Ace3
## X-Curse-Project-ID: 411494

DataStore_Rares.lua

Data/ArathiWarfront.lua
Data/Argus.lua
Data/BFABase.lua
Data/BrokenShore.lua
Data/DarkshoreWarfront.lua
Data/LegionBase.lua
Data/Mechagon.lua
Data/Nazjatar.lua
Data/ValeUldum.lua
```

The line `## Version: @project-version@` is flagging this addon as being 'in development' (and thus ignored) in my addon manager.

I checked the recent `9.x.x` releases but couldn't find any problems there.

I've attached the addon that was downloaded here:

[altoholic--9-0-stub.zip](https://github.com/teelolws/Altoholic-Retail/files/5394837/altoholic--9-0-stub.zip)

**Comment by teelolws** [comment]
Looking in the .zip downloaded from: https://www.curseforge.com/wow/addons/datastore_rares/files/3079054

`## Version: 9.0.1-001`
