### ISSUE TITLE
Grid page needs to have its server re-selected

### ISSUE THREAD

**Issue by Thorrson** [teelolws/Altoholic-Retail#134]
I think this is an issue that has been worked on recently, so I won't go into detail. I did want to post an observation that may help squash the bug:  It seems to only affect servers with 2 word names.  For me, I have characters on DUrotan, Ysera, Khaz Modan, Azjol-Nerub, and Twisting Nether.  On KM, AN, and TN, when I log in and open up the the grid page, the display is blank (even though the selection says it's suposed to be showing THis Account:Khaz Modan.  On Durotan and Ysera, it functions just fine.  I think there may be a bad variable reference for two word server names.

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/377c039413097eecabe403d185cb8852a222976d
