### ISSUE TITLE
Notice to load "retail" when it's already loaded

### ISSUE THREAD

**Issue by linda535** [teelolws/Altoholic-Retail#135]
On one of my alts, I click on Altoholic and I get the blank Altoholic box with the notice inside for your Curse site. I have already installed it. Any idea why I'm getting a non-functioning Altoholic?
Okay, after checking addons, verifying your Altoholic is loaded and reloading ui several times, I now show my alts, but I still get the BIG notice in the middle of the Altoholic window.
Unchecked it in Addons, reloaded and rechecked it. Now again, I have no alts and only the Altoholic window.
thanks much and going to DONATE now! I LOVE ALTOHOLIC and tyvm for updating this!!

**EDITED: Apparently, something happened this morning because it doesn't work on any of my alts now.** :-(

**Comment by linda535** [comment]
Noooo! It's NOT closed - see above issue - and I can't get it to reopen.
thanks for any help!

**Comment by teelolws** [comment]
If you're still getting that notice then you haven't uninstalled the old version properly. Make sure its completely removed in whatever addon manager you have. Then reinstall the one named "Altoholic Retail - Teelos Fork"

**Comment by linda535** [comment]
Uninstalling and reinstalling did the trick, thanks so much!
