### ISSUE TITLE
Installed... but app says not installed?

### ISSUE THREAD

**Issue by thewombatone** [teelolws/Altoholic-Retail#137]
Hi! Big fan of altoholic. I use it all the time. I recently installed the altoholic-retail version. I was very careful to be certain I installed it and loaded it on all of my toons. It works great.
Unfortunately, on my baby alliance toons, when I open it, I get a message saying I need to install altoholic-retail and it provides a link. I double-checked and re-installed and reloaded and refreshed, but nothing has resolved the problem.
I am attaching an in-game screenshot of the problem.
![altoholic issue](https://user-images.githubusercontent.com/73071389/96373146-2dd57b80-1130-11eb-918b-fb999b039a80.jpg)

**Comment by teelolws** [comment]
You haven't installed it properly. Completely uninstall both versions off whatever addon manager you use (twitch?) then reinstall Altoholic-Retail.

**Comment by alwaysladyred** [comment]
But the link sends us to Twitch......... ????

**Comment by teelolws** [comment]
Yes, just make sure when you reinstall it, you reinstall the second one:
![image](https://user-images.githubusercontent.com/49792789/96378726-823d3180-11ea-11eb-8aa4-5ec077e9673c.png)

**Comment by alwaysladyred** [comment]
Got it.  All data from my other characters is gone, but its not difficult to reload all the characters.  Thank you!
