### ISSUE TITLE
Beta Issue: Resize window error

### ISSUE THREAD

**Issue by panoplybez** [teelolws/Altoholic-Retail#138]
I'm back!

So the feature in beta is great and each pane resizes wonderfully. I've noticed though that the whole blizzard snapping of the pane to a certain size, after playing with the resize a few times, this becomes kind of an issue, because it just won't let you resize cleanly, and when you click and HOLD to drag, and the window snaps super wide, when you drag its no longer in sync with where the cursor is on the screen because it has snapped since you held down the button.

Update: if you want to wait this out, you have to click once (snaps wide), click again (snaps high), then use the third click to hold and resize, though there seems to be some choppiness/lag when doing it. 

Also, as soon as I clicked to resize, some conflict with ElvUI threw this at me - no idea why it even cares what I do with Altoholic, but reporting just in case:

Error occured in: Global
Count: 1
Message: ..\AddOns\ElvUI\Modules\Chat\Chat.lua line 981:
   attempt to index a nil value
Debug:
   [string "=[C]"]: ?
   [string "@ElvUI\Modules\Chat\Chat.lua"]:981: UpdateChatTab()
   [string "@ElvUI\Modules\Chat\Chat.lua"]:1075: PositionChat()
   [string "@ElvUI\Modules\Chat\Chat.lua"]:1047:
      ElvUI\Modules\Chat\Chat.lua:1039
   [string "=(tail call)"]: ?
   [string "=[C]"]: FCF_SavePositionAndDimensions()
   [string "*:OnMouseUp"]:7:
      [string "*:OnMouseUp"]:1

**Comment by teelolws** [comment]
This should fix that ElvUI error: https://github.com/teelolws/Altoholic-Retail/commit/515aac35e7521b13fb062b0b4806cfbfd9cbaf82

I can't do much about the resizing snapping around. Thats on Blizzard to fix.

**Comment by panoplybez** [comment]
Nice, thanks for the fix! Yea no worries, once I can get the size I want, hopefully don't have to touch it too often :) Really appreciate you putting that feature in.
