### ISSUE TITLE
Subtotal Average iLvl on Account Summary

### ISSUE THREAD

**Issue by NYCITGuy** [teelolws/Altoholic-Retail#141]
Not a bug - but feature request. The Account Summary has some subtotals at the bottom of the window, and one of those is Total Levels of the characters being filtered. In addition, having "Average Level" would be great, because I like to see where my total alts levels are balanced.  Being able to filter say: less than 60, what is the average level of all my lower leveled alts? Very nice ;)

**Comment by teelolws** [comment]
For your first request, it looks like it already does that? 101.1 is the average between 91.9 and 128.4, no?
![image](https://user-images.githubusercontent.com/49792789/96661238-17d1f000-13a8-11eb-875d-0c7029aeb69f.png)


For your second request, use the level filter:
![image](https://user-images.githubusercontent.com/49792789/96660933-6763ec00-13a7-11eb-86ae-fb9dd5117f8e.png)
I could be convinced to add custom ranges to that. A button to prompt custom ranges or something. A job for another day.

Until then, you can set them with:
```
/run Altoholic:SetOption("UI.Tabs.Summary.CurrentLevelsMin", 1)
/run Altoholic:SetOption("UI.Tabs.Summary.CurrentLevelsMax", 120)
```

Change the 1 and 120 to whatever level range you want. You might have to re-open Altoholic after.

**Comment by NYCITGuy** [comment]
I am refering to the number at the very bottom. That appears to be a SUM of total levels from the filtered characters in the list. That number at the bottom does adjust the SUM of the filtered records, but instead of SUM, AVG is something more meaningful to me than seeing a 2k+ number
![image](https://user-images.githubusercontent.com/20760236/96661431-0a6e2480-131a-11eb-98f1-ce5eb882ac66.png)

**Comment by teelolws** [comment]
Eh, I don't want to overload that bottom right status text with too much information. The average is at the bottom of the column.

**Comment by NYCITGuy** [comment]
Just as an FYI - I actually don't have any aggregated data at the bottom of the column. Do you have to have the list filtered to see those aggregates? The last line of my summary is a character line, and I do not see the average of that data anywhere on the unfiltered list.

**Comment by teelolws** [comment]
Looks like the aggregates don't show is you pick "All Realms/accounts (Hide Realms)" as the person who requested that mode wanted their characters and nothing else.

**Comment by NYCITGuy** [comment]
Yup, that looks correct. Oddly enough though, my aggregates still show total, despite yours showing average of the realm. Is that a setting somewhere?
![image](https://user-images.githubusercontent.com/20760236/96662322-1b1f9a00-131c-11eb-82d9-720c9a8a5440.png)

**Comment by teelolws** [comment]
Oh you want average level, not average item level. Hmm. I'll have to think about how to work that in.

**Comment by teelolws** [comment]
Okay, done: https://github.com/teelolws/Altoholic-Retail/commit/1fb0e9999a4b16e354420a3b50ab89f3fc545372

Clicking the total level will now toggle between total and average:
![image](https://user-images.githubusercontent.com/49792789/96922313-2802e000-150c-11eb-8ad4-7ea481c66192.png)

click

![Uploading image.png…]()
