### ISSUE TITLE
GUI/Lua error in Characters/Mail overview grid

### ISSUE THREAD

**Issue by chasaya** [teelolws/Altoholic-Retail#142]
When opening the mail overview from Summary -> Activity -> Mail Count Indicator/number, the mail list is extended with empty rows over the actual addon window (screenshot attached). Mousing over the entries throws the below LUA error. I tested this with all other addons disabled (only Altoholic and Bug Grabber/Bug Sack), and with a fresh Altoholic/Datastore install (only freshly generated datastore data for some chars to test).

2x Altoholic_Characters\Frames\Mails.lua:173: attempt to compare number with nil
[string "@Altoholic_Characters\Frames\Mails.lua"]:173: in function `OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
self = <table> {
 BuildView = <function> defined @Altoholic_Characters\Frames\Mails.lua:53
 OnEnter = <function> defined @Altoholic_Characters\Frames\Mails.lua:152
 Sort = <function> defined @Altoholic_Characters\Frames\Mails.lua:147
 view = <table> {
 }
 Update = <function> defined @Altoholic_Characters\Frames\Mails.lua:78
 OnClick = <function> defined @Altoholic_Characters\Frames\Mails.lua:180
}
self = AltoholicFrameMailItem {
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:411
 SetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:348
 IconOverlay = <unnamed> {
 }
 OnItemContextChanged = <function> defined @FrameXML\ItemButtonTemplate.lua:249
 showMatchHighlight = true
 icon = AltoholicFrameMailItemIconTexture {
 }
 LevelLinkLockTexture = <unnamed> {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:262
 SetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:415
 SetItemInternal = <function> defined @FrameXML\ItemButtonTemplate.lua:353
 ItemContextOverlay = <unnamed> {
 }
 PostOnEvent = <function> defined @FrameXML\ItemButtonTemplate.lua:266
 GetItemID = <function> defined @FrameXML\ItemButtonTemplate.lua:392
 SetItemSource = <function> defined @FrameXML\ItemButtonTemplate.lua:332
 itemContextMatchResult = 3
 0 = <userdata>
 IconOverlay2 = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:280
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:300
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:253
 SetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:336
 GetItemLink = <function> defined @FrameXML\ItemButtonTemplate.lua:407
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:285
 GetItemInfo = <function> defined @FrameXML\ItemButtonTemplate.lua:379
 SetAlpha = <function> defined @FrameXML\ItemButtonTemplate.lua:423
 GetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:419
 Count = AltoholicFrameMailItemCount {
 }
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:289
 Stock = AltoholicFrameMailItemStock {
 }
 searchOverlay = AltoholicFrameMailItemSearchOverlay {
 }
 GetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:403
 Reset = <function> defined @FrameXML\ItemButtonTemplate.lua:323
}
DS = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 ToggleOption = <function> defined @DataStore\Options.lua:153
 DeleteCharacter = <function> defined @DataStore\DataStore.lua:547
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "DataStore"
 IsCharacterBasedMethod = <function> defined @DataStore\DataStore.lua:435
 GetModules = <function> defined @DataStore\DataStore.lua:707
 UnregisterComm = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DeleteGuild = <function> defined @DataStore\DataStore.lua:615
 GetCurrentCharacterKey = <function> defined @DataStore\DataStore.lua:475
 GetCurrentGuildKey = <function> defined @DataStore\DataStore.lua:479
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 GetModuleLastUpdateByKey = <function> defined @DataStore\DataStore.lua:739
 IsEnabled = <function> defined @DataStore\libs\AceAddo

![alto_mail-grid](https://user-images.githubusercontent.com/73228932/96712328-3ed7f400-139f-11eb-9ee5-573352b6d409.PNG)

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/65a6dfe0d75d0e603ae2e63d75376ff3d97a7a3d
