### ISSUE TITLE
Lua error on Skill main page when clicking on Skill

### ISSUE THREAD

**Issue by Tannx1980** [teelolws/Altoholic-Retail#143]
Here is the error messaage
Message: ...terface\AddOns\Altoholic_Characters\Frames\Mails.lua:105: attempt to index field 'view' (a nil value)
Time: Wed Oct 21 22:36:05 2020
Count: 1
Stack: ...terface\AddOns\Altoholic_Characters\Frames\Mails.lua:105: attempt to index field 'view' (a nil value)
[string "@Interface\AddOns\Altoholic_Characters\Frames\Mails.lua"]:105: in function `Update'
[string "*:OnLoad"]:34: in function `event'
[string "*:OnLoad"]:50: in function `TriggerResizeEvents'
[string "@Interface\AddOns\Altoholic\Core.lua"]:393: in function <Interface\AddOns\Altoholic\Core.lua:389>
[string "@Interface\AddOns\Altoholic\Core.lua"]:447: in function `OnClick'
[string "@Interface\AddOns\Altoholic_Summary\AccountSummary.lua"]:225: in function <...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:204>
[string "@Interface\AddOns\Altoholic_Summary\AccountSummary.lua"]:1118: in function <...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:1114>

Locals: self = <table> {
 BuildView = <function> defined @Interface\AddOns\Altoholic_Characters\Frames\Mails.lua:53
 OnEnter = <function> defined @Interface\AddOns\Altoholic_Characters\Frames\Mails.lua:153
 Sort = <function> defined @Interface\AddOns\Altoholic_Characters\Frames\Mails.lua:148
 Update = <function> defined @Interface\AddOns\Altoholic_Characters\Frames\Mails.lua:78
 OnClick = <function> defined @Interface\AddOns\Altoholic_Characters\Frames\Mails.lua:181
}
frame = "AltoholicFrameMail"
scrollFrame = AltoholicFrameMailScrollFrame {
 0 = <userdata>
 rowPrefix = "Entry"
 GetOffset = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:63
 Update = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:160
 ScrollChildFrame = <unnamed> {
 }
 OnVerticalScroll = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:150
 SetOffset = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:66
 offset = 0
 OnMouseWheel = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:140
 Bottom = <unnamed> {
 }
 OnBind = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:14
 Top = <unnamed> {
 }
 GetRow = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:219
 ScrollBar = <unnamed> {
 }
 rowHeight = 41
 OnScrollRangeChanged = <function> defined @Interface\AddOns\Altoholic\Templates\ScrollFrames.lua:69
 numRows = 8
}
VisibleLines = 8
entry = "AltoholicFrameMailEntry"
DS = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 ToggleOption = <function> defined @Interface\AddOns\DataStore\Options.lua:153
 DeleteCharacter = <function> defined @Interface\AddOns\DataStore\DataStore.lua:547
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "DataStore"
 IsCharacterBasedMethod = <function> defined @Interface\AddOns\DataStore\DataStore.lua:435
 GetModules = <function> defined @Interface\AddOns\DataStore\DataStore.lua:707
 UnregisterComm = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DeleteGuild = <function> defined @Interface\AddOns\DataStore\DataStore.lua:615
 GetCurrentCharacterKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:475
 GetCurrentGuildKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:479
 Printf = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 GetModuleLastUpdateByKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:739
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterModul

**Comment by teelolws** [comment]
I can't seem to replicate your issue.

Are you on the latest version? I released a fix for a similar issue about 12 hours ago.

And if so, what are you doing to make this problem happen?

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/e3bd8021417665a40b0913c9fbf0677282d49b27

I probably won't be pushing the patch until tomorrow. Until then, just click into the Character tab and navigate to your profession the long way.

**Comment by Tannx1980** [comment]
Thank you for the quick reply, You are awesome keep up the great work
