### ISSUE TITLE
Rare kills isn't updating

### ISSUE THREAD

**Issue by raysmith59** [teelolws/Altoholic-Retail#144]
I've never checked this functionality before so it may have never worked but I had a toon kill Rustfeather today but it doesn't show as a kill in the UI.

In that vein, does Datastore_Rares count number of kills and if so, is there a way to get at that info in Altoholic?  Really curious how many Rustfeather kills I have across toons but I'm not aware of any of my add-ons that will count it.

**Comment by teelolws** [comment]
DataStore_Rares doesn't count your number of kills, just whether or not you've killed it today, or this week for ones on weekly resets.

I haven't done much testing with the Rare Spawns section. I'll look into it.

**Comment by raysmith59** [comment]
Any interest in adding a counter to Altoholic?  I may just try to make my own add-on otherwise but it would probably make more sense as part of an existing one.

**Comment by teelolws** [comment]
I'll see if I can work it in. The data, of course, will only start counting from the point where I update DataStore_Rares.

**Comment by teelolws** [comment]
Well its showing my Rustfeather kill, so not sure why it isn't showing for you. You might have to click into another tab then back to Grids again to get it to update:

![image](https://user-images.githubusercontent.com/49792789/96946747-bf345b80-153d-11eb-9017-7d63674d1447.png)

**Comment by teelolws** [comment]
I've pushed a DataStore_Rares update to track number of times you've killed a rare. I'll have a change to Grids in a future Altoholic update to display it.

DataStore updated in: https://github.com/teelolws/DataStore_Rares/commit/3f6475de3d95eea5675f97aa7c06c1054e91fbbe
Released in: https://github.com/teelolws/DataStore_Rares/releases/tag/9.0.2-002

Grids updated in: https://github.com/teelolws/Altoholic-Retail/commit/9a21af234a8fcc809e63636c3345b31e6348a194

**Comment by raysmith59** [comment]
Many thanks.  I realize it'll only work going forward but I'm sure there'll be other rares in the future where I'm pretty sure but not entirely positive that I've killed it 1000+ times and still haven't seen the damned mount.  I like to be accurate when I complain.  :)

**Comment by Tequima** [comment]
Perhaps integrate with SilverDragaon and Rarity? Both of these have extensive Kill Data
