### ISSUE TITLE
Missing tabard slot in grids

### ISSUE THREAD

**Issue by WoLf-** [teelolws/Altoholic-Retail#145]
Hello! loving the ability to resize the window!

After the change, it seems we've lost the Tabard slot, probably along the time the obsolete Ranged slot was removed.
Would it be possible to add it back? it serves as much purpose as the Shirt slot to be fair, but it's current and at least for me useful.

Thanks for keeping the addon alive!

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/aa27466ec5d99f09eec915c23cb203f7be165ec9

It wasn't removed; the resizing code was inadvertently hiding the bottom row in grids.

**Comment by WoLf-** [comment]
Thanks for the quick fix! It added back the Ranged slot tho =)

**Comment by teelolws** [comment]
I don't see a Ranged slot?

**Comment by teelolws** [comment]
Oh, I see. Its showing Ranged data instead of the Tabard.

**Comment by teelolws** [comment]
When Blizzard removed the Ranged slot, they left a hole in Slot 18 instead of moving Tabard to it. So it broke my nicely lined up array. Reeeee. https://github.com/teelolws/Altoholic-Retail/commit/953d71416cb021b2560d53d984bc0bcbe0359320
