### ISSUE TITLE
currency tab doesnt appear to work cross realm

### ISSUE THREAD

**Issue by cereally** [teelolws/Altoholic-Retail#147]
Hello!. all of my tooltips from my inventory work cross realm AND when i type "/alto show" I can see everything on my characters from both realms.  But when i press "c" in game, and then select the "currency" tab, when highlighting those currency items, it will only show the current realm, not both of them.

**Comment by teelolws** [comment]
Use the Grids->Currencies section. The tooltip is limited to same account + same server because if players have lots of characters it'd scroll off the screen.
