### ISSUE TITLE
Achievements > Reputation > BfA shows incorrect data

### ISSUE THREAD

**Issue by th3b1gb4d4sh** [teelolws/Altoholic-Retail#148]
Reputation view in the Achievements tab, specifically for BfA, shows incorrect and identical data for all characters on account. Azerothian Diplomat achievement shows identical quantity of reputation for all characters, individual reputation achievements listed below do not reflect actual progress by each character. Data displayed does *not* change depending on the logged in character.

Rep view for other expansions working as expected.

**Comment by teelolws** [comment]
Can you show me a screenshot or two

**Comment by th3b1gb4d4sh** [comment]
![Capture2](https://user-images.githubusercontent.com/67055169/97106539-44447f80-16ba-11eb-9fa9-540c1faf1dbb.PNG)

Have just cleared Datastore and Altoholic lua files, issue persists. Both Druid and Priest show data which applies to Druid character (first character logged on to after clearing datastore).

**Comment by teelolws** [comment]
Can you try mousing over the first character and click the Reset button:

![image](https://user-images.githubusercontent.com/49792789/97106656-efd7e900-1727-11eb-8eb6-356ce46eac4f.png)

**Comment by th3b1gb4d4sh** [comment]
Have logged on as all three characters and attempted to reset individually;  arrangement of character icons at top of window changed once (not after further reset attempts), data displayed for each individual character unchanged (duplicated as before).
![Capture3](https://user-images.githubusercontent.com/67055169/97106875-06e0f180-16bc-11eb-8be9-1cf9a6439e1a.PNG)

Data in Altoholic shows 20300/21000 Order of Embers, yet character sheet shows "Neutral" (240/3000) for logged in character.

**Comment by teelolws** [comment]
Any change if you switch the account dropdown?

![image](https://user-images.githubusercontent.com/49792789/97107025-231b7780-172a-11eb-9f65-8a08b7cd5062.png)

**Comment by th3b1gb4d4sh** [comment]
None. Hitting "Reset" while changed to realm-only also has no effect.

**Comment by teelolws** [comment]
I think you might be getting an addon error, but have something suppressing the errors from showing. I need to see what the error is.

Can you turn them on by running:
/console scriptErrors 1

And if you're running an addon that hides addon errors, disable it.

**Comment by th3b1gb4d4sh** [comment]
Upon reloading UI I get only one error; MinimapButtonFrame attempt to call method 'SetBackdropColor' (a nil value). Interacting with Altoholic does not generate errors.

**Comment by th3b1gb4d4sh** [comment]
Have just uninstalled addon and cleared all Altaholic and Datastore files from /WTF/Account/{Account}/SavedVariables/ then reinstalled addon. Loaded into a different initial character. Data for character is incorrect, and is the same as that shown in my above screenshot (20300/21000 for Order of Embers etc). No lua errors that I can see. I'm loading the addon from the Twitch client, but verified version is same as on Curseforge.

![Capture4](https://user-images.githubusercontent.com/67055169/97108799-aeafec80-16c7-11eb-9b2c-a19bd58d2c40.PNG)

**Comment by teelolws** [comment]
Are you sure you're not just mistaken about how the Azerothian Diplomat achievement works? I've already completed it, so I can't check it myself. What reputations is it showing in your Achievement journal on each of your characters? Its an account-wide achievement and I suspect its just showing the highest reputation you have on each of your characters.

**Comment by th3b1gb4d4sh** [comment]
That is exactly what has happened... What I was *really* looking for was my rep for each faction in BfA to find highest contributions to that shared achievement, which I've just found in Grids > Reputations > BfA (Alliance).

I should have RTFM. Sorry for wasting your time!
