### ISSUE TITLE
Errors on bug grabber (tomtom related?)

### ISSUE THREAD

**Issue by addonaddict** [teelolws/Altoholic-Retail#150]
Hello. Getting the following error constantly on bug grabber addon
I posted this on TomTom page as well as I can see both tomtom and altoholic are mentioned in the code (no idea about coding so im sorry if this isnt altoholic related)

Error:

20x TomTom\TomTom_POIIntegration.lua:77: attempt to call global 'GetQuestIndexForWatch' (a nil value)
[string "@TomTom\TomTom_POIIntegration.lua"]:77: in function <TomTom\TomTom_POIIntegration.lua:29>
[string "@TomTom\TomTom_POIIntegration.lua"]:258: in function `EnableDisablePOIIntegration'
[string "@TomTom\TomTom_Config.lua"]:40: in function <TomTom\TomTom_Config.lua:20>
[string "=[C]"]: ?
[string "@Altoholic\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Altoholic\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Altoholic\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceAltoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Altoholic\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Altoholic\libs\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ic\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

**Comment by teelolws** [comment]
Looks like TomTom has been updated to fix that bug recently.

**Comment by addonaddict** [comment]
Awesome. Really appreciate the fast response there, keep up the good work 👍
