### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by Qwakos** [teelolws/Altoholic-Retail#151]
Since uppdating to ***022 i get this error when i log in .. 

Message: ...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:225: attempt to index field '?' (a nil value)
Time: Thu Oct 29 12:34:26 2020
Count: 6
Stack: ...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:225: attempt to index field '?' (a nil value)

Locals: 

deleted all folders from altoholic and it goes away ..then  install the *****019 version all fine no errors .. try the 022 version and the ui error comes back.

**Comment by DiscordGregory** [comment]
I got this as well Teelo! And I did what Qwakos did and rolled back my Datastore_Keystones to 019 and the error went away but I was on a level 29 and was curious if I'd get the error on a level 50. So I reinstalled 020 and got on a 50 and no error, so I wanted to see if the error was still there on my 29 and it wasn't.

**Comment by Qwakos** [comment]
only hav elvl 50 chars atm and error on all of them .. tried using the *22 installation and replaced the Datastore_Keystone library from **19 and now it works .. so something in the new library messing up with me :) thx for super addon funktions .. really helps out with all the chars )

**Comment by teelolws** [comment]
Lesson learned: Blizzard_ChallengesUI doesn't like being invoked during login.

It was only erroring for the first login after closing the game. I was testing my changes by swapping characters, which didn't trigger the error.

https://github.com/teelolws/DataStore_Keystones/commit/e1db6957f74b2aba58a5c0df57815528be9f8a3c
