### ISSUE TITLE
Duplicate Tooltip Item Counts

### ISSUE THREAD

**Issue by wadergirl** [teelolws/Altoholic-Retail#152]
Character's item count listed twice in some tooltips:
![image](https://user-images.githubusercontent.com/72587392/97785803-6126fa00-1b75-11eb-8aa2-fa20be5a5a5e.png)

But not in others:
![image](https://user-images.githubusercontent.com/72587392/97785905-db577e80-1b75-11eb-822b-a45b90f2868c.png)

Did a little bit of testing by logging in to an alt, deleting this character from Altoholic, and then logging back in to this character.  Also noticed as I was taking screenshots that it only appears to be happening with herbs (of all levels, from Liferoot shown above to Green Tea Leaf).

Logged back into the alt and did some herbing on the Liferoot for screenshot purposes, showing item count listed twice for both characters:
![image](https://user-images.githubusercontent.com/72587392/97787096-0645d080-1b7e-11eb-9638-1eb0db53d578.png)

**Comment by teelolws** [comment]
Er, yeah. Its doing it on Classic, too. First time mousing over a herb.

![image](https://user-images.githubusercontent.com/49792789/97789305-3778dc00-1c24-11eb-99f5-c705295c3179.png)

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/684cdb77983e0be313439eb7ea174adc58227bee
