### ISSUE TITLE
Missing CountHider

### ISSUE THREAD

**Issue by Sodalicious** [teelolws/Altoholic-Retail#153]
This is the error I am getting. Please help! I have found this add on so VERY VERY useful, considering I have 11 toons total. That's a LOT of alt leveling. 

Thanks so much,
SODA

Message: AceLocale-3.0: Altoholic: Missing entry for 'CountHider'
Time: Sun Nov  1 01:34:09 2020
Count: 1
Stack: AceLocale-3.0: Altoholic: Missing entry for 'CountHider'
[string "@Interface\AddOns\Altoholic\SetupTabs.lua"]:22: in function <Interface\AddOns\Altoholic\SetupTabs.lua:16>
[string "@Interface\AddOns\Altoholic\SetupTabs.lua"]:31: in function `GetNumTotalTabs'
[string "@Interface\AddOns\Altoholic\SetupTabs.lua"]:95: in function `SetupTabs'
[string "*:OnLoad"]:3: in function <[string "*:OnLoad"]:1>

Locals: <none>

**Comment by teelolws** [comment]
[Uninstall this addon "Altoholic Count Hider". ](https://www.curseforge.com/wow/addons/altoholic-count-hider/files/2683580)Its not compatible and everything it does in built into Altoholic now.
