### ISSUE TITLE
Weapon enchant

### ISSUE THREAD

**Issue by mmmmmmorten** [teelolws/Altoholic-Retail#154]
Error on off hand weapon enchant check on my new Kul Shaman....  (ps love the addon)

Lua error:

1 of 2
Message: ...nterface\AddOns\PowerAuras\PowerAurasAuraClasses.lua:2527: attempt to perform arithmetic on local 'offHandExpiration' (a boolean value)
Time: Sun Nov  1 10:49:57 2020
Count: 1
Stack: ...nterface\AddOns\PowerAuras\PowerAurasAuraClasses.lua:2527: attempt to perform arithmetic on local 'offHandExpiration' (a boolean value)
[string "@Interface\AddOns\PowerAuras\PowerAuras.lua"]:678: in function `OnUpdate'
[string "@Interface\AddOns\PowerAuras\PowerAurasEvents.lua"]:46: in function <Interface\AddOns\PowerAuras\PowerAurasEvents.lua:45>

Locals: self = <table> {
 InitialiseAllAuras = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:530
 FlagsChanged = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:795
 UPDATE_SHAPESHIFT_FORMS = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:909
 ModelCategoryList = <table> {
 }
 SecondaryFrames = <table> {
 }
 AnimationEndFactory = <function> defined @Interface\AddOns\PowerAuras\PowerAurasAnimationsOld.lua:583
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:365
 DiscoverLinkedAuras = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:172
 GetBaseCameraTarget = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:1420
 InspectedRoles = <table> {
 }
 SetupDone = true
 CopyTable = <function> defined @Interface\AddOns\PowerAuras\PowerAurasBase.lua:1315
 PLAYER_TOTEM_UPDATE = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:741
 MemorizeActions = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:556
 RangeType = <table> {
 }
 IconSource = "Interface\Icons\"
 VersionGreater = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:109
 VersionPattern = "(%d+)%.(%d+)%.(%d+)"
 WeAreMounted = false
 NextInspectTimeOut = 0
 SetAuraHideRequest = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:886
 INSPECT_TALENT_READY = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:356
 ShowAuraForFirstTime = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:1653
 NextCheck = 0.200000
 PowaGlobalMiscDefault = <table> {
 }
 AuraFactory = <function> defined @Interface\AddOns\PowerAuras\PowerAurasAuraClasses.lua:4812
 Pending = <table> {
 }
 Backdrop = <table> {
 }
 TableEmpty = <function> defined @Interface\AddOns\PowerAuras\PowerAurasBase.lua:1273
 RedisplayAuras = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:537
 MoveEffect = 0
 RelativeToParent = <table> {
 }
 UpdatePreviewRandomColor = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:1463
 WeAreInCombat = false
 WeAreInVehicle = false
 SecondaryModels = <table> {
 }
 ResetSecondaryUnit = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:1401
 PET_BAR_UPDATE = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:1078
 UNIT_NAME_UPDATE = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:1069
 Spells = <table> {
 }
 WeAreInParty = false
 WeAreInPetBattle = false
 InspectRole = <function> defined @Interface\AddOns\PowerAuras\PowerAurasRole.lua:102
 Colors = <table> {
 }
 DisplaySecondaryAura = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:2247
 UpdateSecondaryAuraVisuals = <function> defined @Interface\AddOns\PowerAuras\PowerAuras.lua:1993
 FixRoles = <table> {
 }
 MergeTables = <function> defined @Interface\AddOns\PowerAuras\PowerAurasBase.lua:1343
 TableSize = <function> defined @Interface\AddOns\PowerAuras\PowerAurasBase.lua:1283
 TalentChangeSpells = <table> {
 }
 Debug = <function> defined @Interface\AddOns\PowerAuras\PowerAurasBase.lua:1236
 ModTest = false
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\PowerAuras\PowerAurasEvents.lua:530
 DebugEvents = false
 NextDebugCheck = 0
 AnimationBeginFactory = <function> defined @Interface\AddOns\PowerAuras\PowerAurasAnimationsOld.lua:575
 BlendModeList = <table> {
 }
 LoadAuras = <function> define

2 of 2
Message: ...nterface\AddOns\PowerAuras\PowerAurasAuraClasses.lua:2527: attempt to perform arithmetic on local 'offHandExpiration' (a boolean value)
Time: Sun Nov  1 10:50:13 2020
Count: 1
Stack: ...nterface\AddOns\PowerAuras\PowerAurasAuraClasses.lua:2527: attempt to perform arithmetic on local 'offHandExpiration' (a boolean value)

Locals:

**Comment by teelolws** [comment]
Thats some other addon causing that.
