### ISSUE TITLE
Search doesn't find certain things

### ISSUE THREAD

**Issue by panoplybez** [teelolws/Altoholic-Retail#155]
So I wanted to search for the Honorbound Scouting Map because I know one character has it. However, typing in 'map' and hitting search finds nothing. To find this, I had to type 'honor'.  Can we not do partial (not the first word) name searches or somethin?

**Comment by teelolws** [comment]
Hmm. Well its working for me:

![image](https://user-images.githubusercontent.com/49792789/97813492-76bf2f80-1ced-11eb-89e6-389c289ef12b.png)

Can you upload your altoholic + datastore saved variables?

**Comment by panoplybez** [comment]
So, the first time I searched, it found nothing. I checked the box for 'also search description' and it found stuff, then I unchecked that box, hit the 'reset' button, then searched again, and this time it finds the map. Maybe I had to initialize or something? That's strange. Strange. sorry bout that.

**Comment by panoplybez** [comment]
If I can make that happen on another toon I'll grab the info you asked for (didn't see it initially!)

**Comment by panoplybez** [comment]
It did happen again on an alt, but I just clicked Search 2 more times, and on the third time, it found something. On the third toon, I didn't click more than once, and see this: 

![image](https://user-images.githubusercontent.com/52841691/97815553-d02b4e00-1c5c-11eb-8001-42317c7d3d8b.png)

That said, I can get used to just clicking a few times if that's what my install needs heh. For saved variables, from which level? I didn't see either within the toon folder, only at the server folder level.

**Comment by teelolws** [comment]
Yeah I think its an issue with items not being loaded in yet when you first click the Search button. I'll see if I can do anything about that.

**Comment by panoplybez** [comment]
Much appreciated!

**Comment by teelolws** [comment]
This should make the search results "refresh" when item data is loaded in: https://github.com/teelolws/Altoholic-Retail/commit/bf3ecbfead7b6d2c3781bd9519814e1c21855462

Leaving this ticket open as I'm expecting some issues with this fix. Probably going to get errors in some cases I didn't think to test.

**Comment by panoplybez** [comment]
Sure, if I can help test in some way, let me know. Happy to help.

**Comment by teelolws** [comment]
Yeah v26 will be up for testing when Curseforge approves it.

**Comment by panoplybez** [comment]
So I updated, and its working great! From what I can tell. However, I did get this error, but I'm not 100% sure what caused it. I was toggling between the tabs when it happened. I had just finished deleting some guilds/marking some as 'ignore in tooltip', on the guild tab and was going back through the tabs, and I think the Search one triggered this. I have been trying to reproduce but once I triggered it the first time, it seems to pop up every time I change any tab now (the first time). 

Date: 2020-11-01 20:54:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Altoholic_Search\Search.lua line 62:
   bad argument #2 to 'format' (string expected, got nil)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: format()
   [string "@Altoholic_Search\Search.lua"]:62: Update()
   [string "@Altoholic_Search\Search.lua"]:273:
      Altoholic_Search\Search.lua:254
   [string "@Altoholic_Search\Search.lua"]:280: ?()
   [string "@Altoholic_Search\Search.lua"]:17: Update()
   [string "@Altoholic_Search\Search.lua"]:1040: Update()
   [string "*:OnLoad"]:34: event()
   [string "*:OnLoad"]:50: TriggerResizeEvents()
   [string "@Altoholic\Core.lua"]:394:
      Altoholic\Core.lua:390
   [string "@Altoholic\Core.lua"]:448: OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

**Comment by teelolws** [comment]
Do you remember what the last thing was you searched for before the error started?

**Comment by panoplybez** [comment]
yea it was 'anvil'. then I noticed that it was including guild banks I didn't want it to, so went into investigate that and started ignoring a bunch.

**Comment by teelolws** [comment]
Okay yeah we've found the error. Search results from a deleted guild throwing errors. Not sure if I can do anything about that.

**Comment by panoplybez** [comment]
No worries that's good to know! Is it safe to assume that after a reload or something this will go away on its own once the references to the deleted guild are gone?

**Comment by teelolws** [comment]
Seems to, yeah.

**Comment by panoplybez** [comment]
Great thanks so much. Besides that the search was working first try!

**Comment by teelolws** [comment]
The fix for this is actually crashing the game for users with lots and lots of characters and items. I'm going to have to revert it and try something else.

My new approach is to store the names and descriptions of items in DataStore_Containers. This means the searches won't work properly first time, like before, until you've logged into that character again since the next update and checked its bank.

**Comment by panoplybez** [comment]
No problem, I appreciate you lookin at it. I'm alright clicking it a few times to make it work. I'll log into everyone and see what's what.
