### ISSUE TITLE
Altoholic Keeps Reporting Mails About to Expire at Login

### ISSUE THREAD

**Issue by Ric0chet-GitHub** [teelolws/Altoholic-Retail#156]
When I log onto my Bank Alt, the addon pops-up that my Main toon has "mail about to expire"  The addon, itself, then shows 122 mails for that Main toon.  I have emptied all of my toons' mailboxes.  I still get the pop-up about once per day.
The chat window reports that DataStore_Mails is making this call:  "[Toon] has expired (or about to expire) mails." 

Oddly, when I open the Altoholic app on my Main toon, it shows Zero mail for all toons, as expected.

Thanks.

[SavedVariables.zip](https://github.com/teelolws/Altoholic-Retail/files/5478273/SavedVariables.zip)

**Comment by teelolws** [comment]
I need your DataStore.lua saved variables, too.

**Comment by Ric0chet-GitHub** [comment]
That makes sense.   Sorry.

Let me know if you need more.  I didn't see any individual files in the
various toons' folders.

**Comment by teelolws** [comment]
Is the problem with your character "Læthal" on "Silvermoon"? And are those names spelled correctly?

**Comment by Ric0chet-GitHub** [comment]
Correct.  I saw the "UNKNOWNs" in the file.

**Comment by teelolws** [comment]
And have you recently logged onto Læthal-Silvermoon, and opened+closed the mailbox? These files are showing it was last logged in back in October 14.

**Comment by Ric0chet-GitHub** [comment]
Just about daily. That file should show yesterday as the most recent.

Opened the mailbox this weekend on that toon.

**Comment by teelolws** [comment]
Do you, possibly, have DataStore_Mails disabled on that character? Can you check your addon settings while in-game on that character.

**Comment by Ric0chet-GitHub** [comment]
Good call!  they're almost all disabled on that toon.  Not sure why.
Maybe the pre-patch disabled them, since you said Oct 14th.

I should've checked that!  I feel stupid.

**Comment by teelolws** [comment]
All good. Glad we figured that out!

**Comment by Ric0chet-GitHub** [comment]
Yes! Thank you for taking a look.  I'll check my other toons for similar
status enabled/disabled.
