### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by 1701NCC** [teelolws/Altoholic-Retail#157]
When searching for things in my inventory my WoW seems to lock up for a couple minutes and tosses me this error. I was searching for the Breath of the Everlasting item to see which alts needed to do the vision to get the 3 parts that combine for the rank 2 essence and it just locked up my screen and gave me this error.  When i searched for netherweave, a fairly common cloth, it did the same thing where my screen froze for about 2 minutes before finally giving search results. This is new behavior and quite uncommon for such lag when searching. 

`1x FrameXML\ObjectAPI\AsyncCallbackSystem.lua:55: script ran too long
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:55: in function `AddCallback'
[string "@FrameXML\ObjectAPI\Item.lua"]:236: in function `ContinueOnItemLoad'
[string "@Altoholic\ItemFilters.lua"]:188: in function `SetSearchedItem'
[string "@Altoholic_Search\Search-Search.lua"]:664: in function <Altoholic_Search\Search.lua:647>
[string "@Altoholic_Search\Search-Search.lua"]:719: in function <Altoholic_Search\Search.lua:691>
[string "@Altoholic_Search\Search-Search.lua"]:790: in function <Altoholic_Search\Search.lua:787>
[string "@Altoholic_Search\Search-Search.lua"]:932: in function `FindItem'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 AddCancelableCallback = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:58
 Init = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:24
 callbacks = <table> {
 }
 AddCallback = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:47
 FireCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:70
 api = <table> {
 }
 GetCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:91
 GetOrCreateCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:95
 ClearCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:87
}
id = 109160
callbackFunction = <function> defined @Altoholic\ItemFilters.lua:188
callbacks = <table> {
}
needsAccessorCall = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"
`

**Comment by teelolws** [comment]
Can you upload your Altoholic and DataStore saved variables? You'll find them in your WoW folder, under _retail_\WTF\Account\Account\SavedVariables

**Comment by 1701NCC** [comment]
Tried again just now to see if it was an isolated error and searched for Netherweave. Game froze for just under 2 minutes and produced the same error.

```
2x FrameXML\ObjectAPI\AsyncCallbackSystem.lua:55: script ran too long
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:55: in function `AddCallback'
[string "@FrameXML\ObjectAPI\Item.lua"]:236: in function `ContinueOnItemLoad'
[string "@Altoholic\ItemFilters.lua"]:188: in function `SetSearchedItem'
[string "@Altoholic_Search\Search-Search.lua"]:664: in function <Altoholic_Search\Search.lua:647>
[string "@Altoholic_Search\Search-Search.lua"]:719: in function <Altoholic_Search\Search.lua:691>
[string "@Altoholic_Search\Search-Search.lua"]:790: in function <Altoholic_Search\Search.lua:787>
[string "@Altoholic_Search\Search-Search.lua"]:932: in function `FindItem'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 AddCancelableCallback = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:58
 Init = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:24
 callbacks = <table> {
 }
 AddCallback = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:47
 FireCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:70
 api = <table> {
 }
 GetCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:91
 GetOrCreateCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:95
 ClearCallbacks = <function> defined @FrameXML\ObjectAPI\AsyncCallbackSystem.lua:87
}
id = 109160

callbackFunction = <function> defined @Altoholic\ItemFilters.lua:188
callbacks = <table> {
}
needsAccessorCall = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"
```
[SavedVariables.zip](https://github.com/teelolws/Altoholic-Retail/files/5499279/SavedVariables.zip)

**Comment by teelolws** [comment]
Looks like the problem is you have so many characters and so many items that the search just takes a very very long time. When I remove all your guild banks, it still takes about 90 seconds.

I'll see what I can do, but no guarantees I'll actually be able to improve it.

**Comment by 1701NCC** [comment]
Its very odd, i didn't seem to have this search lag until somewhat recently. I hadn't encountered this issue when doing searches before the pre-patch, and i used the search function fairly frequently since its hard to remember where things are with that many alts.

**Comment by teelolws** [comment]
No, I know whats happened. I made some changes recently to solve an issue another user had where searches weren't working properly the first time the button was clicked. But I see now my changes cause massive lag with lots of items. I'm trying another approach.

**Comment by teelolws** [comment]
It still tied up the game for about three seconds but thats better than three minutes:
![image](https://user-images.githubusercontent.com/49792789/98334853-b62ca980-2068-11eb-9ba2-84bebca334b2.png)

**Comment by teelolws** [comment]
Version 027 going up now, should solve this problem.

**Comment by 1701NCC** [comment]
Updated this morning and logged onto a few alts. Searched for netherweave and timed the results.  Average result time was about one and a half  seconds every test no matter what i searched for. Even things with large numbers of results like various crafting materials never seemed to surpass 2 seconds.  I think its quicker than prior to the update that causes the lag

Now what do i click to mark this as solved?
