### ISSUE TITLE
Summary tab

### ISSUE THREAD

**Issue by Spike0007** [teelolws/Altoholic-Retail#16]
I have an empty window for Summary, Activity, Skills and Bag usage. It has been like this since I install ver. 1.13.2-013, it is also happening with ver. 1.13..4-014. Any idea what I can do? I have reinstalled it twice already.

Thanks for keeping this updated.
Spike0007

**Comment by Spike0007** [comment]
![image](https://user-images.githubusercontent.com/42614631/78051577-80da1380-7343-11ea-99b3-638ca7115352.png)

**Comment by teelolws** [comment]
Can you upload your Altoholic saved variables file:

![image](https://user-images.githubusercontent.com/49792789/78065290-8c831400-73ef-11ea-917f-1cde633c7c8a.png)

**Comment by PaulKBSR** [comment]
I'm having a similar problem.  It says "Altoholic_Characters-diabled" and "Altoholic_Summary-disabled".

**Comment by PaulKBSR** [comment]
Here is my altoholic.lua
[Altoholic.lua,txt](https://github.com/teelolws/Altoholic-Retail/files/4415244/Altoholic.lua.txt)

**Comment by teelolws** [comment]
PaulKBSR: you have the filters set to Alliance only. Intended?

If it says Altoholic_Summary is disabled then you haven't installed the addon properly.

**Comment by Spike0007** [comment]
teelws,

Sorry this has taken me a while to upload. I have deleted addons thinking they were the problem but it hasn't worked. Should I delete the WTF file ??

Thank for taking on the project. I have alts and already contemplating 4 more even with the little time I have avail.

Spike

[SavedVariables - Copy.zip](https://github.com/teelolws/Altoholic-Retail/files/4446818/SavedVariables.-.Copy.zip)

**Comment by teelolws** [comment]
Spike0007: You have your filters set to only show characters with a specific profession.

**Comment by teelolws** [comment]
Mouse over these buttons, the filters, and change them: 
![image](https://user-images.githubusercontent.com/49792789/78716957-ed709600-7973-11ea-9bc8-9fa96236ae4c.png)

**Comment by Spike0007** [comment]
Teelolws,

Thank you very much. I can't believe it was something so simple.
