### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thedude79** [teelolws/Altoholic-Retail#162]
Message: Interface\AddOns\Altoholic\ItemFilters.lua:183: attempt to index local 'itemInfo' (a nil value)
Time: Sun Nov  8 11:51:42 2020
Count: 1
Stack: Interface\AddOns\Altoholic\ItemFilters.lua:183: attempt to index local 'itemInfo' (a nil value)
[string "@Interface\AddOns\Altoholic\ItemFilters.lua"]:183: in function `SetSearchedItem'
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:661: in function <Interface\AddOns\Altoholic_Search\Search.lua:647>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:724: in function <Interface\AddOns\Altoholic_Search\Search.lua:685>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:784: in function <Interface\AddOns\Altoholic_Search\Search.lua:781>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:890: in function `FindItem'
[string "*:OnEnterPressed"]:2: in function <[string "*:OnEnterPressed"]:1>

Locals: self = <table> {
 SetFilterValue = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:114
 TryFilter = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:162
 ItemPassesFilters = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:132
 ClearSearchedItem = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:192
 ClearFilters = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:158
 SetSearchedItem = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:169
 GetFilterValue = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:118
 GetSearchedItemInfo = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:188
 EnableFilter = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:124
}
itemID = 139
itemLink = "[]"
isBattlePet = nil
s = <table> {
 itemID = 139
}
_ = nil
itemInfo = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 ToggleOption = <function> defined @Interface\AddOns\DataStore\Options.lua:153
 DeleteCharacter = <function> defined @Interface\AddOns\DataStore\DataStore.lua:547
 EnableModule = <function> defined @Interface\AddOns\CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "DataStore"
 IsCharacterBasedMethod = <function> defined @Interface\AddOns\DataStore\DataStore.lua:435
 GetModules = <function> defined @Interface\AddOns\DataStore\DataStore.lua:707
 UnregisterComm = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DeleteGuild = <function> defined @Interface\AddOns\DataStore\DataStore.lua:615
 GetCurrentCharacterKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:475
 GetCurrentGuildKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:479
 Printf = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 GetModuleLastUpdateByKey = <function> defined @Interface\AddOns\DataStore\DataStore.lua:739
 IsEnabled = <function> defined @Interface\AddOns\CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @Interface\AddOns\CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterModule = <function> defined @Interface\AddOns\DataStore\DataStore.lua:366
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 IsGuildBasedMethod = <function> defined @Interface\AddOns\DataStore\DataStore.lua:448
 SetupInfoPanel = <function> defined @Interface\AddOns\DataStore\Options.lua:102
 SendCommMessage = <function> defined @Interface\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:87
 GetGuildMemberAlts = <function> defined @Interface\AddOns\DataStore\DataStore.lua:826

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Retail/commit/894b9010b0c5e0100b7c560bfecdee7b88fa6032
