### ISSUE TITLE
Expired Auction Handling

### ISSUE THREAD

**Issue by SkrybeGH** [teelolws/Altoholic-Retail#164]
At the moment altoholic tracks auctions you've posted, but it doesn't seem to handle them when they expire (other than reducing the auction count). This is problematic when you have a lot of alts on multiple servers, and it's even worse when you have multiple accounts and you're sharing data. Without effective tracking of expired auctions you need to login to every toon on every server on every account in order to check for sold/expired auctions.

For example;

On my priest I have 2 mail and I post 4 auctions for 24 hours then log out.
I log on to my druid and check altoholic. It shows my priest has two mail and 4 auctions.
I log out for a few days.
I log on to my druid and check altoholic. It shows my priest has two mail and zero auctions.

Ideally it should either show my priest as having six mail - the two original mail and four expired (or sold) auctions, or it should show 4 auctions, but when you hover over them it says "4 expired auctions".

Possibly there is another (better) way to deal with expired auctions, but at the moment there doesn't seem to be anything and it's problematic. Possibly a popup warning on login that "auctions have expired on characters X, Y & Z"?

**Comment by teelolws** [comment]
So, if I understand you correctly, you want it to update the number of mail waiting when an auction expires?

The problem with this is there is no way to know if the auction actually sold. I won't be able to put the gold amount or the item into the Mail database. All I can do is save a blank mail with "AH" as the sender. That will at least show that there is mail waiting to be checked, but you won't know whats in it until you check it. Is that okay with you?

**Comment by teelolws** [comment]
https://github.com/teelolws/DataStore_Auctions/commit/233f456f82d2c00d00159c87ccfd293ac549d79c

**Comment by SkrybeGH** [comment]
I understand that there's no way to determine whether it's sold or simply expired until you check mail on that character. The problem though is with a lot of characters it's possible to miss sold/expired auctions since they aren't indicated in any way in altoholic.

My thinking is that the mail handler is the most elegant solution since auctions turn into mail, and altoholic tracks mail, and more importantly displays a warning once mail is within five days of expiration. This means we'd be able to see that we need to check a particular alt.

As for whether the mail should be blank, I'd suggest instead making it the auctioned item. Since altoholic already tracks the items being auctioned I'd imagine it'd be possible to add a mail item with the corresponding auction item. If it's actually sold then obviously when we opened the mail it'd be gold not a gem/herb/pet/etc. This would make it easier to track the importance of checking it too. If it's "one linen cloth" you could conceivably ignore it. But if it's an expensive mount you'd want to check.

The main drawback I could see with this approach is that there is some margin for error in when the mail from the AH will expire. If you list an auction for 48 hours and it sells almost immediately then the mail with the gold would expire 40+ hours before a mail where the auction failed and was returned to you. I can't see a way around that without some convoluted calculations and it'd still be a guess anyway.

The other solution that comes to mind is not purging items from the auction list until you actually visit that character. So instead when you look at the activity list it still shows that you have auctions. On the activity tab the number could be changed from green to red to indicate that they've expired. And if you check the auctions tab for that character it could still show the list of auctions but where it normally shows the duration eg: "Short (Less than 30 mins)" it could show "Auction ended". This solution lacks the warning that the mail one provides. But it'd probably be easier to implement, and it's still be useful since the auctions would be visible on the activity tab.

**Comment by teelolws** [comment]
Nah I don't want to mislead players with their item availability. I prefer a stance of "if I'm not sure if they have it, presume they don't have it". So I've gone with the route of when auctions expire, it'll be replaced by unknown mail with "Auctioneer" as the sender. At least that will let you know and give you a timer to log that character and check its mailbox.

**Comment by SkrybeGH** [comment]
No worries, no matter what solution is taken there's always risk of it being misleading since it's an unknown whether an auction sold or expired. If they turn into "unnknown" mails that's certainly sufficient.

Thanks

**Comment by SkrybeGH** [comment]
Just wanted to say I've had a chance to check out the new expired auction handling and it works like a charm. Could see my rogue had 5 mail and when I clicked on them it showed as being from the auctioneer. Thanks again.
