### ISSUE TITLE
bad argument #2 to 'strsplit' (string expected, got table)

### ISSUE THREAD

**Issue by Ookami313** [teelolws/Altoholic-Retail#165]
Updated to 029 earlier and upon logging into one of my characters I received the following error. Thanks.

1x DataStore_Mails\DataStore_Mails-9.0.1-027.lua:446: bad argument #2 to 'strsplit' (string expected, got table)
[string "=[C]"]: in function `strsplit'
[string "@DataStore_Mails\DataStore_Mails-9.0.1-027.lua"]:446: in function `func'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
(*temporary) = "."
(*temporary) = <table> {
 lastUpdate = 1604815636
 Auctions = <table> {
 }
 Bids = <table> {
 }
}
(*temporary) = "string expected, got table"

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/DataStore_Auctions/commit/a51754510738e75d8758c0361a2eb82a4fd9b427
