### ISSUE TITLE
DataStore: PLAYER_PET_CHANGED

### ISSUE THREAD

**Issue by FuxieDK** [teelolws/Altoholic-Retail#166]
This appears in my BugSack

1x DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_PET_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@ClassTimer\ClassTimer-2.4.90001.1-1-g253eaec.lua"]:342: in function <ClassTimer\ClassTimer.lua:338>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by teelolws** [comment]
Some other addon that uses AceEvent is causing that.
