### ISSUE TITLE
Summary > Garrison Followers - Level Issue

### ISSUE THREAD

**Issue by Daveo7** [teelolws/Altoholic-Retail#167]
It's still expects garrison followers to be level 100 when since the level squish they are now level 40.

This needs to be updated so it counts the number of level 40 followers you have correctly instead of looking for level 100 followers.

**Comment by teelolws** [comment]
Oh did they finally change them? When I was testing that on the PTR they still had them all with their old levels.

**Comment by Daveo7** [comment]
Yes they did change them, along with the followers from other expansions.

WoD - Level 40
Legion - Level 45
BfA - Level 50

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Retail/commit/da1cf38ee1518161800710ae5e28363ed39019c5
