### ISSUE TITLE
Instance reset times wonky

### ISSUE THREAD

**Issue by FuxieDK** [teelolws/Altoholic-Retail#168]
Why are 2 toons (Garthog and Quixx) 1 minute early (or to be precise, 2 toons 46 seconds early and 2 toons 14 seconds late)?

[07:57:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 2 minutes (Garthog on Draenor)
[07:57:14] Altoholic: Dragon Soul 25 Player (Heroic) will be unlocked in 2 minutes (Quixx on Draenor)
[07:57:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 3 minutes (Grusme on Draenor)
[07:57:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 3 minutes (Zalistra on Draenor)

[07:58:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 1 minutes (Garthog on Draenor)
[07:58:14] Altoholic: Dragon Soul 25 Player (Heroic) will be unlocked in 1 minutes (Quixx on Draenor)
[07:58:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 2 minutes (Grusme on Draenor)
[07:58:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 2 minutes (Zalistra on Draenor)

[07:59:14] Altoholic: Icecrown Citadel 25 Player (Heroic) is now unlocked (Garthog on Draenor)
[07:59:14] Altoholic: Dragon Soul 25 Player (Heroic) is now unlocked (Quixx on Draenor)
[07:59:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 1 minutes (Grusme on Draenor)
[07:59:14] Altoholic: Icecrown Citadel 25 Player (Heroic) will be unlocked in 1 minutes (Zalistra on Draenor)

**Comment by teelolws** [comment]
DataStore_Agenda has some rather unusual code as it was built in a time when functions like     C_DateAndTime.GetSecondsUntilWeeklyReset() didn't exist.

I'll add it to the list for investigation. It can probably use some... modernisation.

**Comment by FuxieDK** [comment]
I know, it's a minor problem, but it still looks silly..

Also, while at it, maybe it can be made to take up less space, something like:
[08:00:00] Altoholic: Icecrown Citadel 25 Player (Heroic) is now unlocked (Garthog@Draenor, Grusme@Draenor, Zalistra@Draenor)
[08:00:00] Altoholic: Dragon Soul 25 Player (Heroic) is now unlocked (Quixx@Draenor)


I.e. All toons for one instance in one line.

**Comment by teelolws** [comment]
Okay, in an upcoming fix, the time-to-reset should be a bit more accurate. They will still differ by a few seconds on each character. This is simply because C_DateAndTime.GetSecondsUntilWeeklyReset() + time() always returns slightly different results every time.

As for collapsing all the alerts, that would require a significant rewrite of Events.lua. There are options in the settings to reduce the amount of alerts you get:

![image](https://user-images.githubusercontent.com/49792789/99866409-cff7f000-2c15-11eb-854a-d87844080d15.png)

**Comment by FuxieDK** [comment]
I'm afraid it's not completely fixed :(

1: I didn't get any warnings for ZG was about to reset
2: Reset message came at 8:12 when I opened Altoholic
3: It's still listed in the agenda after reset

![WoWScrnShot_112720_081319](https://user-images.githubusercontent.com/44226521/100421485-bc6ede00-3088-11eb-93af-2a4c1ec717a8.jpg)

**Comment by teelolws** [comment]
That yellow-text message "Zul'Gurub has been reset." isn't from Altoholic. Its a system-generated message by Blizzard, and it popped up because you changed dungeon difficulty from Heroic to Mythic. The lockout still remains, its just a loot lockout, not a dungeon lockout.

**Comment by FuxieDK** [comment]
> That yellow-text message "Zul'Gurub has been reset." isn't from Altoholic. Its a system-generated message by Blizzard, and it popped up because you changed dungeon difficulty from Heroic to Mythic. The lockout still remains, its just a loot lockout, not a dungeon lockout.

True.. I switched, because I wanted to go Karazhan too, but the instance WAS reset, as it resets at 8:00 this time of year.

I went into ZG again at 8:20 , where it was still in agenda, killed one boss (for mount) and went out... Still the same reset date (today @ 8:00) in agenda.
Not until I reloaded UI did it switch to tomorrow.

**Comment by teelolws** [comment]
Sounds like Agenda just isn't refreshing when a lockout resets. The data is updating in the background but the Agenda tab isn't refreshing until a reload / logout. I'll see what I can do.

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Retail/commit/06d73689b6d88b20361836f555922df9055f5cd3
https://github.com/teelolws/DataStore_Agenda/commit/61861e163a4e2d5e530add05543d17f22aef7b20

These should force the Agenda tab to refresh its display when your dungeon lockouts change. Can you let me know if this works? Dungeon resets at 4am for me and I'm never online at that time.

**Comment by FuxieDK** [comment]
> [06d7368](https://github.com/teelolws/Altoholic-Retail/commit/06d73689b6d88b20361836f555922df9055f5cd3)
> [teelolws/DataStore_Agenda@61861e1](https://github.com/teelolws/DataStore_Agenda/commit/61861e163a4e2d5e530add05543d17f22aef7b20)
> 
> These should force the Agenda tab to refresh its display when your dungeon lockouts change. Can you let me know if this works? Dungeon resets at 4am for me and I'm never online at that time.

Can try... But I won't be online tomorrow at reset.

**Comment by FuxieDK** [comment]
It's 30/11 8:16, and message got printed, but Agenda still shows dungeons as locked.
![image](https://user-images.githubusercontent.com/44226521/100579389-6eeead00-32e4-11eb-86b0-4b859575aa2c.png)

**Comment by teelolws** [comment]
Its also got the reset time as November 30... what the hell

**Comment by teelolws** [comment]
Without /reloading, if you immediately logout and into another character, is it fixed?

**Comment by FuxieDK** [comment]
You are in luck... 👍 
I was just DC'ed, and have logged back in, and it's cleared from Agenda.

**Comment by teelolws** [comment]
Eh. I'm not going to worry too much about the display not updating straight away. You're logged in and you know the dungeons reset. When you switch characters the display will be updated.
