### ISSUE TITLE
Transparent addon

### ISSUE THREAD

**Issue by monne55** [teelolws/Altoholic-Retail#169]
I hope this is the right way to do this, I got an issue with Altoholic being transparent, it may have to do with me running ElvUI. 

Is this a known issue, and can it be fixed?

Let me know if further info is needed.

**Comment by teelolws** [comment]
Shrug. I don't use ElvUI. If you turn ElvUI off is it still a problem?

**Comment by monne55** [comment]
No, if ElvUI is off, the issue is gone and altoholic looks like its own self

**Comment by monne55** [comment]
![alto](https://user-images.githubusercontent.com/73218396/99729117-c0b05f80-2aba-11eb-8b1b-4b1470f08554.png)
Added image for reference.

**Comment by teelolws** [comment]
I installed ElvUI to test it and it looks fine. I can't help you debug problems caused by other addons.

![image](https://user-images.githubusercontent.com/49792789/99730642-af4e6e00-2b21-11eb-924f-6fc0fc1e0b08.png)

**Comment by monne55** [comment]
I seem to have found the culprit.. 
..\AddOns\Tukui_UIPackages_Skins\Altoholic.lua (Part of ElvUI which i completely reinstalled) I removed that file, and i now have same skin as you. Maybe it's a long lost plugin from way back.

CLosing it, :)

**Comment by teelolws** [comment]
Its this addon here: https://www.curseforge.com/wow/addons/addonskins

This is what it looks like with the window stretched out: 

![image](https://user-images.githubusercontent.com/49792789/99732546-8c718900-2b24-11eb-93be-5bcfa4e520ec.png)

Looks like you just hadn't updated that one in a while.

**Comment by monne55** [comment]
Awesome man, thank you!

//Mønne
________________________________
Fra: teelolws <notifications@github.com>
Sendt: Thursday, November 19, 2020 11:37:31 PM
Til: teelolws/Altoholic-Retail <Altoholic-Retail@noreply.github.com>
Cc: monne55 <dominix@outlook.com>; State change <state_change@noreply.github.com>
Emne: Re: [teelolws/Altoholic-Retail] Transparent addon (#169)


Its this addon here: https://www.curseforge.com/wow/addons/addonskins

This is what it looks like with the window stretched out:

[image]<https://user-images.githubusercontent.com/49792789/99732546-8c718900-2b24-11eb-93be-5bcfa4e520ec.png>

Looks like you just hadn't updated that one in a while.
