### ISSUE TITLE
Currency tab

### ISSUE THREAD

**Issue by cwwood0322** [teelolws/Altoholic-Retail#17]
When you switch to the currency tab, the window freezes with the exception of only two lines being scrollable to go though alts and their currencies.

**Comment by teelolws** [comment]
Can you upload your DataStore_Currencies saved variables:
![image](https://user-images.githubusercontent.com/49792789/78213199-6bfdab80-750e-11ea-851a-e4176d3eb45b.png)

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/f7714e9d441b0253274550ab2ef35a62b46669eb

While I was there I updated that tab to track Coalescing Visions and Titan Residuum instead of  the Warfront War Supplies, and rich azerite fragment (whatever that is).

**Comment by cwwood0322** [comment]
![image](https://user-images.githubusercontent.com/30670064/78306718-b0d31380-7509-11ea-9525-d24ba806ea26.png)

This image shows you what I am seeing when go to currency in the addon.

**Comment by teelolws** [comment]
Looks like you're getting an addon error while its trying to load your seal currency for Elvarnia.

Grab the latest addon files from the main page here. I made a fix for that yesterday.

**Comment by cwwood0322** [comment]
How do you apply that fix, I usually update addons through twitch.

**Comment by teelolws** [comment]
Here: 

![image](https://user-images.githubusercontent.com/49792789/78411129-1be82b80-766b-11ea-8f3e-105e6e66c5cd.png)
