### ISSUE TITLE
thaokyaltoholic's version still show up in Twitch and CurseForge apps

### ISSUE THREAD

**Issue by PowerYuppie** [teelolws/Altoholic-Retail#171]
It's not really an issue, but more of an annoyance and curiosity.
I think the reason for it is that this version uses the same folder as thacky's which makes the Twitch and CurseForge apps believe that both versions are installed.

I don't really know what the structure of the plugins are, but isn't there somewhere in one of the files that the apps uses to identify the correct plugin?
Or perhaps use a different folder name?

![Capture](https://user-images.githubusercontent.com/52123539/99880135-d7b59580-2c11-11eb-9f57-3d79ad243990.PNG)

**Comment by teelolws** [comment]
I don't have access to remove thaoky's (outdated) version, and if I change the folder name nobody will switch.

**Comment by PowerYuppie** [comment]
What an odd answer.
Players don't look for addons based on folder name. We find addons based on
what they do.
And because your version is already called Altoholic-retail, is it really
that big of a leap to store the addon in such a folder?

Den lör 21 nov. 2020 20:51teelolws <notifications@github.com> skrev:

**Comment by teelolws** [comment]
Yes, it is. Peoples addon managers won't pick it up if I change the folder name.

**Comment by PowerYuppie** [comment]
Ok. But isn't that something that can be done in an update?

Den lör 21 nov. 2020 21:04teelolws <notifications@github.com> skrev:

**Comment by teelolws** [comment]
The other project should no longer be prompting for an Update in Twitch/Curseforge.

**Comment by PowerYuppie** [comment]
Thank you.

Den lör 21 nov. 2020 21:18teelolws <notifications@github.com> skrev:
