### ISSUE TITLE
Expiring Mail Notification

### ISSUE THREAD

**Issue by Faecat** [teelolws/Altoholic-Retail#172]
Every time I log in I get the notification that I have mail that is about to expire but the altoholic window doesn't show any mail.  I have logged in and checked every character I have.  This has been going on since the new version of altoholic that split off from classic.  Thank you.

**Comment by teelolws** [comment]
Go to your Saved Variables folder and delete DataStore_Mails.lua

World of Warcraft\_retail_\WTF\Account\ACCOUNTNAME\SavedVariables

**Comment by Faecat** [comment]
Thank you!  That worked.
