### ISSUE TITLE
Error when using Shift+Click

### ISSUE THREAD

**Issue by azeda** [teelolws/Altoholic-Retail#174]
When trying to Shift+Click on an item, I'm given an error.

Steps I took:

Opened AH
Opened Recipe from Profession
Selected Text Box on AH
Shift+Clicked item in Recipe
Got LUA

`Message: Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua:260: attempt to concatenate a nil value
Time: Sat Dec  5 17:31:22 2020
Count: 4
Stack: Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua:260: attempt to concatenate a nil value
[string "@Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua"]:260: in function <Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua:254>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Altoholic\Tooltip.lua"]:727: in function <Interface\AddOns\Altoholic\Tooltip.lua:725>
[string "=[C]"]: in function SetRecipeReagentItem'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:757: in function OnReagentMouseEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>`

**Comment by teelolws** [comment]
These two steps: "Selected Text Box on AH + Shift+Clicked item in Recipe" are not things you can normally do with the Auction House. Look to whatever addon you're using that is allowing this as the problem. From your error log, looks like its Tukui.
