### ISSUE TITLE
Incorrect Profession Skill Level Reported for Shadowlands Alchemy

### ISSUE THREAD

**Issue by Chh2tx** [teelolws/Altoholic-Retail#175]
When using the 'Skills' function to show all characters skills, filtered to show only the Shadowlands skill level, the addon incorrectly reports my Alchemist as having 175 skill when he only has 75 skill for Shadowlands. Not seeing this same issue with other professions.

![image](https://user-images.githubusercontent.com/47042057/101680171-ee3b5980-3a25-11eb-8bd6-855fcc28c229.png)

**Comment by teelolws** [comment]
For some reason, Blizzard gave "Shadowlands Alchemy - Header" the same Order Index as "Alchemy of the Broken Isles", which was throwing my sorting algorithm out.

You can see it here: https://wow.tools/dbc/?dbc=tradeskillcategory&build=9.0.2.36839#page=1&colFilter[0]=alchemy

Legion and Shadowlands Alchemy all with Order Index 940, when Shadowlands should be 920, to make it be listed first.

I've done a manual override: https://github.com/teelolws/Altoholic-Retail/commit/b39e9edb652624630b8e94afb6e8481752c6f8a1

As this is relatively minor, it'll be saved for a future release.
