### ISSUE TITLE
No Tooltip for Fishing on Skills View for main toon

### ISSUE THREAD

**Issue by Chh2tx** [teelolws/Altoholic-Retail#176]
![image](https://user-images.githubusercontent.com/47042057/101696086-2c8f4380-3a3b-11eb-9722-d03174942cad.png)

Extremely minor tooltip issue.

I only get the issue on my main, where there is no tooltip that shows all the relevant expansions fishing skill when you hover over the skill. Doesn't matter how it's sorted, it's always that toon. Occurred before hitting 200 fishing as well.

Works just fine with other professions, for example -- cooking.
![image](https://user-images.githubusercontent.com/47042057/101696271-7ed06480-3a3b-11eb-9264-ef27fdc669f1.png)

**Comment by teelolws** [comment]
Your characters fishing details just aren't registered yet. Open the fishing spellbook:

![image](https://user-images.githubusercontent.com/49792789/101698357-3322c700-3ade-11eb-86a0-3e8121d1fc05.png)

**Comment by Chh2tx** [comment]
Done that many times, to no affect. I do understand how the skills get loaded. I do it across each alt to ensure they have updated as I level them/train.

Here's a screenshot of it opened just now...
![image](https://user-images.githubusercontent.com/47042057/101700688-1be2cb80-3a43-11eb-8f08-15774b7fee17.png)

And in this picture with my cursor hovered over the skill, just as is done for every other toon. (Cursor doesn't show in the screenshot)
![image](https://user-images.githubusercontent.com/47042057/101700774-3f0d7b00-3a43-11eb-9ee0-414d4398e3b8.png)

Running latest Altoholic
![image](https://user-images.githubusercontent.com/47042057/101700855-65331b00-3a43-11eb-8671-7b41b141a231.png)

And this happens even when it's the only addon loaded. Again it's a minor issue, but was noting it nevertheless.

Anything else I can try?

**Comment by teelolws** [comment]
Can you upload your Altoholic and DataStore saved variables

**Comment by Chh2tx** [comment]
[Altoholic.zip](https://github.com/teelolws/Altoholic-Retail/files/5669314/Altoholic.zip)
[DataStore.zip](https://github.com/teelolws/Altoholic-Retail/files/5669315/DataStore.zip)

**Comment by teelolws** [comment]
Would have been more helpful if you had your error messages enabled and displayed:
![image](https://user-images.githubusercontent.com/49792789/101701756-6b2d0880-3ae4-11eb-991d-b18ef0cc6487.png)

This is due to a bug I discovered earlier with professions being too high causing a rounding error. It was fixed in: https://github.com/teelolws/Altoholic-Retail/commit/cbe4de213cc41490b6ebb95741870d02f49eafb0

![image](https://user-images.githubusercontent.com/49792789/101701836-9b74a700-3ae4-11eb-85d3-d854fba0c0d3.png)

**Comment by Chh2tx** [comment]
Apologies, I didn't realize I had them suppressed.
