### ISSUE TITLE
Local Lua error

### ISSUE THREAD

**Issue by MagicOfDobby** [teelolws/Altoholic-Retail#181]
Unfortunately, I have yet been able to figure out how to replicate it. I'll report back if I do.

4x Altoholic\Tooltip.lua:501: attempt to index local 'nodeName' (a nil value)
[string "@Altoholic\Tooltip.lua"]:501: in function <Altoholic\Tooltip.lua:494>
[string "@Altoholic\Tooltip.lua"]:658: in function <Altoholic\Tooltip.lua:654>

Locals:
nodeName = nil
(*temporary) = GameTooltipTextLeft1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'nodeName' (a nil value)"
gatheringNodeWasShown = true
addon = <table> {
 UnbindViewFromController = <function> defined @Altoholic\libs\LibMVC-1.0\LibMVC.lua:150
 GetEnglishTabList = <function> defined @Altoholic\SetupTabs.lua:93
 ToggleOption = <function> defined @Altoholic\Frames\TabOptions.lua:158
 GetLocalTabList = <function> defined @Altoholic\SetupTabs.lua:89
 Loots = <table> {
 }
 GetMoneyString = <function> defined @Altoholic\Altoholic.lua:542
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 UnregisterComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetLastAccountSharingInfo = <function> defined @Altoholic\Altoholic.lua:94
 GetSpellIcon = <function> defined @Altoholic\Altoholic.lua:515
 GetRecipeLink = <function> defined @Altoholic\Altoholic.lua:519
 Helpers = <table> {
 }
 Item_OnClick = <function> defined @Altoholic\Altoholic.lua:450
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DATASTORE_GLOBAL_MAIL_EXPIRY = <function> defined @Altoholic\Comm.lua:515
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetClassExtensions = <function> defined @Altoholic\Templates\ClassExtensions.lua:49
 SendCommMessage = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 TradeSkills = <table> {
 }
 ItemFilters = <table> {
 }
 DeleteItemFromHiddenHearthstones = <function> defined @Altoholic\Frames\TabOptions.lua:231
 Icons = <table> {
 }
 OnEnable = <function> defined =[C]:-1
 Version = "9.0.2-012"
 DATASTORE_MAIL_EXPIRY = <function> defined @Altoholic\Comm.lua:545
 GetCharacterIcon = <function> defined @Altoholic\Altoholic.lua:732
 DATASTORE_CS_TIMEGAP_FOUND = <function> defined @Altoholic\Comm.lua:552
 Tasks = <table> {
 }
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 BindViewToController = <function> defined @Altoholic\libs\LibMVC-1.0\LibMVC.lua:110
 GetCharacterTable = <function> defined @Altoholic\Altoholic.lua:69
 ToggleUI = <function> defined @Altoholic\Altoholic.lua:392
 GetRecipeLevel = <function> defined @Altoholic\Altoholic.lua:631
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "Altoholic"
 DDM_Initialize = <function> defined @Altoholic\Altoholic.lua:715
 InitTooltip = <function> defined @Altoholic\Tooltip.lua:753
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Altoholic\Frames\TabOptions.lua:129
 Service = <function> defined @Altoholic\libs\LibMVC-1.0\LibMVC.lua:98
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 AddItemToHiddenHearth

**Comment by teelolws** [comment]
I fixed this about 2 hours before you posted this report in version -013.
