### ISSUE TITLE
[addon packaging] alpha builds of Datastore modules without equivalent Altoholic alpha builds cause breakage in Curseforge app

### ISSUE THREAD

**Issue by R-Adrian** [teelolws/Altoholic-Retail#182]
i set my Curseforge app to install alpha builds of addons, (this is mostly because of the DBM release style)...

when you publish on Curseforge an alpha version of a Datastore_* sub-addon / module but without publishing an equivalent Altoholic alpha build, as it happened today, this causes breakage in the Curseforge app ...

e.g. when v9.0.2-002 (alpha) of Datastore_Mails was published today... if i apply the alpha update i get this....

![image](https://user-images.githubusercontent.com/16319504/102712280-9673dc80-42c8-11eb-861e-ecaa51fe0110.png)

and when i try to fix the breakage by reinstalling the latest available alpha build of Altoholic... (which... there isn't one...so it reinstalls the only possible thing.. the latest release)... then Datastore_Mails starts showing as broken/modified.

![image](https://user-images.githubusercontent.com/16319504/102712375-89a3b880-42c9-11eb-8179-8f46a3ea7327.png)

anything i do causes either one or the other to show as broken/modified and the app has already started to permanently show all the Datastore_* modules as separate addons - some of which it doesn't even consider as installed even if they are obviously installed as part of the main Altoholic addon.

**I'm not sure if it's possible to stop publishing the Datastore modules as separate files on Curseforge, but it would be nice if there was an equivalent alpha build of Altoholic published each time there's an alpha Datastore build published too, so that we can avoid such version conflicts between addons.**

![image](https://user-images.githubusercontent.com/16319504/102712550-cae89800-42ca-11eb-98f6-8bcd3f950bd9.png)

P.S. i always keep disabled the setting to install libraries separately.... but i still cannot make those Datastore modules to stop showing up in my Curseforge app.

**Comment by R-Adrian** [comment]
note: the breakage might not be immediately visible in the Curseforge/Overwolf app even after presing the Refresh button multiple times. Wait about 2..3 minutes after pressing the refresh button or exit the app and re-start it, it will show up then.

**Comment by teelolws** [comment]
I will upload changes to DataStore modules but not update Altoholic when the changes are so minor they don't warrant a full Altoholic patch. I suggest you just stop watching for Alpha builds of DataStore as they're intended for **other developers** only.
