### ISSUE TITLE
Errors with 9.0.2-013

### ISSUE THREAD

**Issue by Fringetastic** [teelolws/Altoholic-Retail#183]
I installed the update from 2 days ago, 9.0.2-013.zip. On login since then, I get a bunch of errors. 

![image](https://user-images.githubusercontent.com/23005790/102717498-57359380-42a8-11eb-82f6-7d6cde042a11.png)

Maybe they are all related to the first error that bugsack grabs:

```
1x DataStore\DataStore-9.0.1-033.lua:17: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
[string "=[C]"]: ?
[string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:189: in function `EmbedLibrary'
[string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:171: in function `EmbedLibraries'
[string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:138: in function `NewAddon'
[string "@DataStore\DataStore-9.0.1-033.lua"]:17: in main chunk

Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0"."
```

I can provide information on others if it will help.

Edit: I initially said it  happened on the first login of each day but that's not true, it is happening even on /reload, so not just first login of a day.

**Comment by teelolws** [comment]
Theres something wrong with your install. Its missing files. Uninstall all the Altoholic and DataStore folders and reinstall it.

**Comment by Fringetastic** [comment]
You were right on. I had the addon manager re-install Altoholic and have had a reload and a relog with no further problems. Thanks!
