### ISSUE TITLE
Missing 1 column of bags

### ISSUE THREAD

**Issue by SjoerdvanhetSchip** [teelolws/Altoholic-Retail#185]
![image](https://user-images.githubusercontent.com/4532064/102767253-8c60e500-437f-11eb-866c-9f3b399850aa.png)
As vissible in the image, the right most column of the bags is missing.
I did nothing strange, just loaded into my character, opened my bags and Altoholic and took the screenshot.
Though maybe some other addon can interfere here, but the odds are not that big with no bag addons...

**Comment by teelolws** [comment]
Whoops: https://github.com/teelolws/Altoholic-Retail/commit/0f6f9fc3ed55856830d4fbda5a15f0238fc09b98

**Comment by SjoerdvanhetSchip** [comment]
💋
