### ISSUE TITLE
Activity column doesn't show expiring emails

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Retail#186]
I'm getting the "mail is expiring on some character" warning, and I can see it's Camillus in chat. But if I open the main panel to look at the mail column in the activity pane, his count doesn't include the expiring mails, and is not in red.

In the attached data file, he's got two messages expiring in 3 days and one that's relatively new. The panel shows 1 in green, not 3 in red as expected.

[DataStore_Mails.lua.txt](https://github.com/teelolws/Altoholic-Retail/files/5742344/DataStore_Mails.lua.txt)

**Comment by SpareSimian** [comment]
I just looked at the data file and see it's not showing the older, expiring messages. So it's whatever's populating that data that's broken.

**Comment by teelolws** [comment]
Should fix: https://github.com/teelolws/DataStore_Mails/commit/fa808f04eb2a4ab90898231080217ee7a845830a

**Comment by SpareSimian** [comment]
This seems to have cured it. Thanks!
