### ISSUE TITLE
Missing Characters/Skills

### ISSUE THREAD

**Issue by roweboy1974** [teelolws/Altoholic-Retail#187]
I'm missing some toons and some of the toons that are tracked are missing their prof skills.

**Comment by teelolws** [comment]
Screenshots? Saved Variable files? Any disabled Altoholic or DataStore modules? Opened your profession books on those characters?

**Comment by roweboy1974** [comment]
I reset the filters (toons were still not there) and then closed the game and relaunched it and the toons were there. Not sure what happened but it is working now.
