### ISSUE TITLE
Change Repository Owner/Permissions

### ISSUE THREAD

**Issue by jfwowmods** [teelolws/Altoholic-Retail#189]
Would it be possible to come up with some small changes in how the Altoholic codebase is managed?  My sense is that the #188 is probably going to continue to create some mistrust for users and any potential contributors.  My initial thoughts were to fork the repository and get it under new ownership, but I think the first option might be to give the current owner the opportunity to add just a little bit of oversight to the commit/tag/release process.  Like getting at least one other approver / thumbs up on a new tag?  What is the easiest way to insert a lightweight review step?

Any other suggestions on how to keep this project healthy?  There's a ton of value for the community and people make mistakes it's fine, wipe it up, rebuff, next pull.

The intention here is not to address any outstanding issues with TRP, if that's a root cause then please sort that out in a different channel, hopefully we can stay focused on keeping this mod in good shape.

**Comment by teelolws** [comment]
Yeah I'm not going to do that. The code changes I've made belong to me, and I'm not going to be bullied into giving them away.

If you do not like this, direct your complaints towards Thaoky, the makers of TRP3 who have been harassing me lately, and the WoWAce Moderators who removed my project off Curseforge in violation of the software license I had the project under.
