### ISSUE TITLE
[Feature Request] HoA Essence unlock tracking

### ISSUE THREAD

**Issue by Garnthrax** [teelolws/Altoholic-Retail#19]
It would be great if unlocked Heart of Azeroth essences and their level could be tracked via its own tab in Grids. Maybe including Echoes of Nya'lotha currency and Heart level at top too. Ideally ordered: spec shared-DPS-tank or heal-other

**Comment by teelolws** [comment]
Yeah I thought about doing this, but so late in the expansion its not really worth the time. Its just going to become obsolete when Shadowlands rolls around. I'd rather make a tracker for the new system.

As for Echoes of Nya'lotha, they're tracked with all the other currencies in Grids.
