### ISSUE TITLE
How do I get my alts to show in the user interface dealy

### ISSUE THREAD

**Issue by fedup2020** [teelolws/Altoholic-Retail#190]
I have a bunch of alts on MoonGuard, but every time I log into one, it only shows that stuff in my bags on that current character and my main.  Also, when I open up the interface thing that is supposed to have list, it only lists my one main character.  I have gone onto all my alts and loaded the addon, but that didn't seem to work.  HELP!

**Comment by teelolws** [comment]
Try clicking the "Reset Filters" button
