### ISSUE TITLE
Track Dark Moon Faire monthly quests

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Retail#192]
I try to do the four profession quests each month at the Dark Moon Faire on all my alts, for both the XP and rep. With a full suite of alts on both factions on three realms, it's hard to remember which ones I've left to do as the week progresses. I thought the daily quest tracking on the Grid tab did this, but I don't see the quests listed there.

**Comment by teelolws** [comment]
This should be possible with Grids/Tasks, though it takes some setup on your part:

1. Look up the quest ID for the DMF quest. For this example, I'm using the engineering quest Talkin' Tonks: https://www.wowhead.com/quest=29511/talkin-tonks#

2. Go to interface options -> DataStore_Quests -> write that quest ID per this picture, then press enter:
![image](https://user-images.githubusercontent.com/49792789/103876128-25da1600-5138-11eb-809a-15cd5bdf06ab.png)

3. Now, after you've completed that quest on the character you're logged in on, when managing Grids/Tasks, that quest should appear under Daily Quests:
![image](https://user-images.githubusercontent.com/49792789/103876452-8a957080-5138-11eb-8996-e913c40eff6a.png)

Now its tracked on Grids/Tasks!
![image](https://user-images.githubusercontent.com/49792789/103876499-9719c900-5138-11eb-9404-b7b6a74683a3.png)

**Comment by teelolws** [comment]
Also, please keep in mind: Thaoky has recently removed me from the project on Curseforge, and intends to release a version of Altoholic that removes most of the features I have added over the last year.

My Fork will continue to be available here on Github, so the choice is yours which version you want to use going forward. If you choose to use my fork, make sure to setup your Addon Manager to ignore any projects on Curseforge or WoWInterface!

**Comment by SpareSimian** [comment]
I discovered that [Saved Instances](https://www.curseforge.com/wow/addons/saved_instances) does this. I just couldn't remember what I'd used in the past.
