### ISSUE TITLE
'Not Found' on Curseforge

### ISSUE THREAD

**Issue by JinxLuckless** [teelolws/Altoholic-Retail#193]
I was trying to install the addon on my laptop, and it doesn't show up in Overwolf's Curseforge client. In fact, I tried searching your name, and other addons show up-- but not altoholic. 

Even the Curseforge website doesn't work for me right now:
https://www.curseforge.com/wow/addons/altoholic-classic/
returns:
Not found

We were unable to find the page or file you were looking for.

**Comment by teelolws** [comment]
Unfortunately: Thaoky has recently removed me from the project on Curseforge, and intends to release a version of Altoholic that removes most of the features I have added over the last year.

My Fork will continue to be available here on Github, so the choice is yours which version you want to use going forward. If you choose to use my fork, make sure to setup your Addon Manager to ignore any projects on Curseforge or WoWInterface!

**Comment by JinxLuckless** [comment]
I would definitely rather use yours, then... thanks! I use Curseforge (via Overwolf) for my addon managing... do you know how I would set that to ignore the Thaoky version?

Thanks for all your hard work!

**Comment by teelolws** [comment]
Not sure, sorry. I update my addons manually.

**Comment by JinxLuckless** [comment]
Okay, thanks!

I just updated the previous comment with this right as your reply came in: Oh, and an update to ask, will yours continue to be updated for new versions? I completely understand if not, obviously.

**Comment by JinxLuckless** [comment]
(And for anyone who reads this after me... if you already have altoholic installed via Curseforge, it's really easy to set it to not update-- right click on it, choose Install Settings, and set to Ignored. You're able to do it per addon.)

**Comment by teelolws** [comment]
> Oh, and an update to ask, will yours continue to be updated for new versions? I completely understand if not, obviously.

I'm not sure at this stage, sorry. I'll reassess based on anything new in 9.1, and what Thaoky changes. I'm not going to compete with him if he ends up releasing a better version.

**Comment by JinxLuckless** [comment]
Yeah, that's fair. Thanks! :)

**Comment by Razertongue** [comment]
Not to add fuel to the fire, but Id like to hear out your side of the story on what he proposed.

I felt your coding brought some good life back to the addon, not a single lua error (aside from that one rogue one) lol 

I dont see how he thinks the code you wrote was malicious...

**Comment by Fayreon** [comment]
I'd also like to hear the story. I've seen what Thaoky has posted on the CurseForge page, what's with the sketchy code? You obviously don't have to justify yourself to a rando on the internet, just don't want to support either really without a better understanding.

**Comment by srvanmeter87** [comment]
Two questions:

Why did you feel the need to include code resulting in `if AddOn_TotalRP3 then wipe(AddOn_TotalRP3) end` in the first place?

Why is it obfuscated in bytecode via a `loadstring` function?

**Comment by Angranelined** [comment]
как теперь скачать новую версию вашего творения?
Не понимаю как устроен этот сайт.
Возмущен тем что в CurseForge ваш addon убрали.

**Comment by teelolws** [comment]
> как теперь скачать новую версию вашего творения?

https://github.com/teelolws/Altoholic-Retail/releases
Altoholic-9.0.5-019.zip

**Comment by Waldkoenig** [comment]
@teelolws 
You probably missed the questions by @srvanmeter87 so I'll just repeat them here because they're very good questions:

Why did you feel the need to include code resulting in `if AddOn_TotalRP3 then wipe(AddOn_TotalRP3) end` in the first place?
Why is it obfuscated in bytecode and loaded via a loadstring function?

**Comment by Razertongue** [comment]
> @teelolws
> You probably missed the questions by @srvanmeter87 so I'll just repeat them here because they're very good questions:
> 
> Why did you feel the need to include code resulting in `if AddOn_TotalRP3 then wipe(AddOn_TotalRP3) end` in the first place?
> Why is it obfuscated in bytecode and loaded via a `loadstring` function?

Its dead. Him and the owner of RP3 are never going to reconcile the issue. He blew he chance at being a helpful content creator for Alto and maybe even WoW all together. Lets just move on to the next big thing. Clearly he has/had something to hide and doesnt want to talk to us about it. Damn introverted behavior if you ask me.

**Comment by teelolws** [comment]
I don't answer to any of you.
