### ISSUE TITLE
Grids not showing any alts' names

### ISSUE THREAD

**Issue by linda535** [teelolws/Altoholic-Retail#195]
**Describe the bug**
I use the Grids to keep track of my other alts, just like this addon is made for. Today, I tried to move my alts to organize by gear - cloth, leather, mail, plate.  There are no names at all when I mouse over a question mark or any of the alt's icons.

**Saved Variables**
Please upload your Altoholic and DataStore Saved Variables. For instructions: https://github.com/teelolws/Altoholic-Retail/wiki/Uploading-your-Saved-Variables
[altoholic variables.zip](https://github.com/teelolws/Altoholic-Retail/files/5890001/altoholic.variables.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/54631734/106199212-fa13e400-6169-11eb-90ab-14213758f051.png)

**Additional context**
I recently loaded "All the Things" and disabled that. The only other recent addon is Pepe Collection.
Thanks so much for taking over this awesome addon. 
Linda

**Comment by teelolws** [comment]
Hi, can you make sure you've got Lua errors enabled, then test it again and see if you get an error? Heres a good article about turning them on and off: https://www.wowace.com/projects/rarity/pages/faq/how-to-enable-and-disable-script-errors-lua-errors

When I test it using your variables it all seems to work: 
![image](https://user-images.githubusercontent.com/49792789/106200748-559eaa00-621c-11eb-8526-0f44ce88efaa.png)

**Comment by linda535** [comment]
I ran the command (in WoW chat) "/console scriptErrors 1", did /reload, and opened and closed Altoholic several times. No errors, but no names of alts. I disabled **every other addon** except the Altoholic and DataStore lines, reloaded and still no names and no errors. I checked on another character (same realm) and no luck.
I love that you are able to get them, but I have no idea why it's not working for me. I do have two merged accounts which is new, but it's the same on both accounts. Thanks for your quick reply.

**Comment by teelolws** [comment]
Are you logged in on that hunter when its happening?

**Comment by linda535** [comment]
I've actually logged in on several toons on 3 different realms and two different accounts (merged), but they all show the same thing.

**Comment by teelolws** [comment]
I've found some possible interference from the DataStore modules Thaoky has uploaded on Curseforge.

Please follow the following steps:

1. Disable updates to Altoholic and DataStore in whatever addon manager you use (Curseforge?).
2. Clear out your Altoholic and DataStore addon files by deleting all their folders under your WoW folder \ Interface \ AddOns \
3. Reinstall it from https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.2-017

**Comment by linda535** [comment]
I uninstalled all the files and deleted all the saved variables. I used your site to download the zipped files and extracted them to the Wow\Interface\Addons folder. Then I restarted my computer. Still no change.

**Comment by linda535** [comment]
I just changed to my other account and it worked. I had only one alt - the current one. Then switched to another one and yay, TWO. Names are showing again.
Thanks so much!

**Comment by linda535** [comment]
Thank you so much for all your attention and help today. I know you got the email that it's working, but I wanted to also post here. Your customer service is excellent!

**Comment by teelolws** [comment]
Np!

**Comment by linda535** [comment]
Apparently the error reporting is working now. Lucky because I don't have grid names again.

Message: ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:262: bad argument #1 to 'bAnd' (number expected, got table)
Time: Fri Jan 29 12:31:41 2021
Count: 1
Stack: ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:262: bad argument #1 to 'bAnd' (number expected, got table)
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua"]:262: in function <...AddOns\DataStore_Currencies\DataStore_Currencies.lua:258>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Altoholic_Grids\Grid_Currencies.lua"]:31: in function `GetUsedHeaders'
[string "@Interface\AddOns\Altoholic_Grids\Grid_Currencies.lua"]:218: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\Altoholic\Core.lua"]:386: in function <Interface\AddOns\Altoholic\Core.lua:384>
[string "@Interface\AddOns\Altoholic\Core.lua"]:430: in function `OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = <table> {
 isHeader = true
 index = 1
 count = 0
}
(*temporary) = 127
(*temporary) = "number expected, got table"

**Comment by teelolws** [comment]
Don't update Altohoic or DataStore from Curseforge. Thaoky has removed my access there and the version that remains is completely incompatible now. Everything you'll need is on the release section here, and I don't have any updates planned before 9.1!

**Comment by linda535** [comment]
Oh brother. That's exactly what happened. Thanks for the message and VERY QUICK HELP! Using your file to update right now!!
Any way I can report to Thaoky that that version of Altoholic isn't working, or leave the issue alone?

**Comment by teelolws** [comment]
Best to leave it alone as Thaoky doesn't want to cooperate with me. The choice is yours which version you want to use, and I fully intend to keep this one updated!

**Comment by linda535** [comment]
Sad that it's such a good addon and you've done so much for it. Thanks for all you've done and continue to do.

**Comment by linda535** [comment]
I read Thaoky's message and just wow... What this person doesn't address is that their version is extremely BUGGY.
Anyway, I hope you're still working on this. Is there something wrong with my version or is the cross-account info not working?
I have a sub account (yeah, definitely an altoholic) and when I choose All Realms All accounts it only shows the information for the account I'm on. Maybe I need to change or add something?
Thanks much, Linda

**Comment by teelolws** [comment]
The addon can't automatically see the data on your other accounts. This is a restriction placed by Blizzard. I have a guide here called "Account Sharing": https://github.com/teelolws/Altoholic-Retail/issues/73

**Comment by linda535** [comment]
Thanks so much, but I think it's more trouble than it's worth with 50 alts on my one account and 7 on the other... Unless I'm missing something.
Linda

**Comment by SpareSimian** [comment]
This would be a good candidate for a helper app that runs outside WoW and merges the WTF files for different accounts. Kind of like the Wowhead program that uploads your data to their website. Are there any good libraries in any language for manipulating LUA source files such as those in the WTF directories?

**Comment by linda535** [comment]
Um, did you just switch languages on me?  (That's a "no clue" reply.)
Lol, I used to build computers, write code and create games - before the 1TB sized HDs. My first had NO HD and my second computer had a 40MB HD, hehehe.
Sounds like a great idea, but I doubt there are that many people with multiple accounts for this to be a really viable application.
Thanks again!

**Comment by SpareSimian** [comment]
I'd consider writing it for myself and then sharing it. But I'd want a library that parses and writes the LUA used in the data files. I mostly code in C++ but could probably write it in any language. It might be a command line tool, though. ("We don't need no stinking GUI!")

BTW, please don't quote previous posts unless context is needed to know what you're replying to. You're posting your unsubscribe links and lots of other junk to the GitHub issue comments. I recommend going back and editing those in the web interface to eliminate all the junk, if only to protect yourself.

**Comment by linda535** [comment]
Whatever you want and thanks for the tip. I had thought these were just emails. I'd love the "easy" way.
Thanks much for all your help. Linda

**Comment by teelolws** [comment]
Some users have reported success by symbolic linking their SavedVariable folders together. It can be problematic if you have more than about 80 characters in total, though, as the number of names will make dropdowns scroll off the screen.
