### ISSUE TITLE
Datastore 

### ISSUE THREAD

**Issue by TheMaaster** [teelolws/Altoholic-Retail#197]
current version seems to be not compatible with latest external updates of data store

**Comment by teelolws** [comment]
You have two options:

1. Set your addon updater to ignore Curseforge and get the latest version here: https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.2-017

2. Complain to Thaoky for taking away my access to Curseforge and replacing the addon with a version that either doesn't work or is missing all the bug fixes and features I worked on for over a year.
