### ISSUE TITLE
No Currency sum

### ISSUE THREAD

**Issue by Wh15k3y-hun** [teelolws/Altoholic-Retail#198]
**Describe the bug**
after updated letest version, on character currency tab, altoholic does not show alts currency

**Comment by teelolws** [comment]
Are you getting the latest version from: https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.5-019

My updates are no longer on Curseforge.

**Comment by Wh15k3y-hun** [comment]
thank you for your fast respond.

of course, i have the latest version, downloaded from this site

**Comment by Wh15k3y-hun** [comment]
sorry, i did not realized, there are 2 versions of this addon.
