### ISSUE TITLE
Error when searching without a search term

### ISSUE THREAD

**Issue by fzarr** [teelolws/Altoholic-Retail#20]
When I do a search, select a item rarity, slot, etc. but without any text filter, I get the following lua error:

Message: Interface\AddOns\Altoholic\ItemFilters.lua:60: attempt to compare number with nil

**Comment by teelolws** [comment]
Simple enough fix. https://github.com/teelolws/Altoholic-Retail/commit/8a7c4ff7fd614f2c76334490f406145f16d32b02
