### ISSUE TITLE
Any chance this can be pushed to Curse/Twitch so it can be updated from the app?

### ISSUE THREAD

**Issue by TheMangoFuture** [teelolws/Altoholic-Retail#21]
Would sure make life a lot easier than having to come back to github and downloading lol.

**Comment by teelolws** [comment]
There are 21 people paying Thaoky every month to maintain the addon. If you want updates, ask the guy taking all the money.

**Comment by TheMangoFuture** [comment]
Lmao so that seems like a “no”? Name it Altoholic Continued or something. Just makes it a lot easier on end users.

**Comment by teelolws** [comment]
Curseforge/Twitch won't let me upload a separate project, because he has the licence as All Rights Reserved.
