### ISSUE TITLE
Feature Request: Add possibility to search on extended item properties, like bind type

### ISSUE THREAD

**Issue by fzarr** [teelolws/Altoholic-Retail#22]
Would be cool if you could search all your characters for Bind on Equip items, or even possibly text in the item tooltip, etc.

**Comment by teelolws** [comment]
I could probably squeeze an option for Binding here, but I wouldn't be able to fit both. 

![image](https://user-images.githubusercontent.com/49792789/80759002-ae0c2280-8b8a-11ea-8685-62cb4df19b24.png)

I might look at adding an option to search item text, and you can just chuck "equip" in the search field.

**Comment by teelolws** [comment]
Done! There is now an option to search inside item text.

![image](https://user-images.githubusercontent.com/49792789/82739890-c3462c80-9d97-11ea-96cb-5702e4eeb706.png)

Added in commit: https://github.com/teelolws/Altoholic-Retail/compare/ed132582d0ae...33cb0d9f6cd7

Will be released in a later update. If you want it now, grab the latest files off the main page here.

**Comment by fzarr** [comment]
Amazing, tyvm :)
