### ISSUE TITLE
Feature Request: Include guild bank gold value in main summary screen

### ISSUE THREAD

**Issue by cxmplex** [teelolws/Altoholic-Retail#23]
Where it shows currency for all the alts on the main summary (when you open Altoholic), it would be nice to include guild bank value as well, and include it in the "total" gold section. This is useful for bank alts and seems in the spirit of Altoholic. If there is a way to do this already, please let me know.

**Comment by teelolws** [comment]
I dont really agree with this. For most people, the guild bank gold isn't "theirs". I could maybe do it only if the character is the guild master?

**Comment by cxmplex** [comment]
That would work fine.

**Comment by cxmplex** [comment]
Also helpful for people who own multiple Gbanks across servers.

**Comment by teelolws** [comment]
Done. 

![image](https://user-images.githubusercontent.com/49792789/81749760-582b6900-9500-11ea-819b-65fc8970462a.png)
![image](https://user-images.githubusercontent.com/49792789/81749773-5feb0d80-9500-11ea-9826-fd4093505bf1.png)

Added in: https://github.com/teelolws/Altoholic-Retail/compare/65167b0d030c...cc22ac9185ff
