### ISSUE TITLE
Your license "restriction"?

### ISSUE THREAD

**Issue by Protuhj** [teelolws/Altoholic-Retail#24]
In your license modification, you added the following line:  

> The changes I have made use the following licence: My alterations and additions are not to be shared or distributed anywhere without my (Teelo) express permission.  

I would like to help keep Altoholic up to date, but not if your license includes that language. 

What is the intent behind that?

**Comment by teelolws** [comment]
I don't want my changes shared on the original Altoholic project page where Thaoky is keeping all the profits for himself despite no longer contributing to the project.

**Comment by Protuhj** [comment]
Alright, then I have no desire to contribute to your fork. Good luck!
