### ISSUE TITLE
Essences level overview

### ISSUE THREAD

**Issue by stamicvs** [teelolws/Altoholic-Retail#26]
Hi Teelo,

first of all thank you very much for taking over the maintenance of this great addon.
I have a feature request or I maybe just missed something.

As we can now buy our Essences for Echoes and I am currently try to keep up with Essence farming I would like to be able to see what Essences my Alts have and at what level to determine with what character I should continue to farm.
Is there already such an overview existing or would this be possible in the Grid overview somewhere?

Thank you very much in advance.

**Comment by teelolws** [comment]
You can see how many Echoes your alts have with the currencies section, but, no, I haven't made anything to track Essences. The main reason is it would be incredibly temporary. They're all going *poof* in shadowlands. It would be a lot of effort to write it all up only to have it become dead code in a couple of months. I'd rather just get access to the beta ASAP and make modules for Shadowlands instead.

**Comment by stamicvs** [comment]
Of course I fully understand that the effort is way too temporarily.
Thank you very much for your reply,
