### ISSUE TITLE
Reputations - Lua errors

### ISSUE THREAD

**Issue by TwoTailedFox** [teelolws/Altoholic-Retail#36]
When you view Reputations -> Alliance, it causes Lua errors to display, with mouseover not working on Uldum Accord. Same true for Horde tab. Other tab seems unaffected.

**Comment by teelolws** [comment]
Was this the same issue we discussed on discord, where it turns out there are nils in your Datastore saved variables from an older version of the addon?

**Comment by TwoTailedFox** [comment]
Different issue, the SV Lua file was recreated.

When you click in the Rep grid via the dropdown Batte for Azeroth -> Alliance, it generates a Lua error. 

Ignore my comment about Uldum Accord, that's mysteriously working fine.

**Comment by teelolws** [comment]
You deleted your Datastore_reputations saved variables file, right?

If you delete an individual datastore file but don't delete all the other saved variables, the addon gets... issues. The characters are still listed in the grids saved variables, so its trying to find reputation data that isn't in your saved variables anymore.

Four options to fix this:

1. Log into each of your characters to populate their reputation data
2. Delete the characters you don't play anymore from altoholic on the summary tab by right clicking them
![image](https://user-images.githubusercontent.com/49792789/83687976-bd2a3880-a640-11ea-9cc0-62031cbd75ee.png)
3. Change the characters to "none" on the grids menu:
![image](https://user-images.githubusercontent.com/49792789/83687919-a257c400-a640-11ea-8dc9-6713f32a7f98.png)
4. Delete all your saved variables and start over
