### ISSUE TITLE
Tooltip Error

### ISSUE THREAD

**Issue by Digawen** [teelolws/Altoholic-Retail#37]
Good afternoon.

When I talk to a trader and the window opens then I get this LUA error and the tooltip window is shown permanently until I do some mouseover in the Altoholic menu.

29x Altoholic\Tooltip.lua:258: invalid capture index
[string "=[C]"]: in function `match'
[string "@Altoholic\Tooltip.lua"]:258: in function <Altoholic\Tooltip.lua:233>
[string "@Altoholic\Tooltip.lua"]:469: in function `GetRecipeOwners'
[string "@Altoholic\Altoholic-8.3-010.lua"]:298: in function `MerchantFrame_UpdateMerchantInfo'
[string "@FrameXML\MerchantFrame.lua"]:135: in function `MerchantFrame_Update'
[string "@FrameXML\MerchantFrame.lua"]:64: in function <FrameXML\MerchantFrame.lua:60>

Locals:
(*temporary) = "Benötigt Abkommen von Uldum - Respektvoll"
(*temporary) = "Benötigt %1$s (%2$d)"

[https://i.imgur.com/HrKoS85.png](url)

It's also an extra tooltip. The normal one is the one on the right.

**Comment by teelolws** [comment]
Looks like in Deutsch, ITEM_MIN_SKILL (provided by Blizzard) has a different pattern to English. "Requires %s (%d)" vs "Benotigi %1$s (%2$d)".

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/d1c0c7018fcd391cc4bab7de51d1f2f3d2c84255
