### ISSUE TITLE
Emissary and Daily Vision not showing up completed correctly

### ISSUE THREAD

**Issue by Nickster76** [teelolws/Altoholic-Retail#39]
![WoWScrnShot_060620_043330](https://user-images.githubusercontent.com/66402804/83939972-01d3e200-a7af-11ea-83b5-7bf184b3842a.jpg)
![WoWScrnShot_060620_043322](https://user-images.githubusercontent.com/66402804/83939973-05ffff80-a7af-11ea-9f83-12d03e66ab24.jpg)

I meant to say my hunter have completed the daily vision, and my druid has completed the Storm's Wake Emissary since yesterday. It seems as if Altoholics doesn't save the emissary correctly info if you log out of the game for a bit...

**Comment by teelolws** [comment]
I'm still working on that Emmissary section, and I haven't uploaded my changes to Twitch yet. However, your Daily Vision IS showing! "A Dark, Glaring Reality" is your Daily Vision quest!

The changes I plan to make to the Emmissary Section should make it work like this:
- The Rustbolt Resistance daily quest will be listed there, whichever one of the three quests is up that day.
- The currently active Vale and Uldum assaults will be listed there.

I probably won't add the Legion and 8.1 "invasions" unless someone asks me to. I think they'll just be useless clutter nobody cares about.

**Comment by Nickster76** [comment]
Sorry I corrected what I wanted to say. I completed the Storm's Wake and Embers Emissaries on my druid yesterday and I've completed the Daily Vision on my hunter. Notice on the Emissay QuestS page for my druid instead of Check marks it just blank.

Thanks,
Nick A. Adams
Field Service Technician
(786) 457-6386
nadams@imagenet.com<mailto:nadams@imagenetconsulting.com>
+ IMAGENET - Orlando

________________________________
