### ISSUE TITLE
Problem with Localisation in AccountSummary

### ISSUE THREAD

**Issue by AmonFlorian** [teelolws/Altoholic-Retail#40]
The last couple of days I tried to fix a current problem with internationalisation of the AddOn.
DataStore-Crafts gets localized names perfectly fine but due to Blizzard being inconsistent there are problems here.
As Altoholic relies on spellIDs for names, etc. it can't find "Kräuterkunde" e.g. as the spellID 2366 refers to the spell "Kräutersammeln".
My workaround to show an icon in AccountSummary was this:
clone every function that relies on "spell id" to search for "skillline id" as used in C_TradeSkillUI.GetTradeSkillLineInfoByID() of the WoW-API
Do a localized version of it just as you do with the spellIDs.

I just use skillline-ids for Profession1 and Profession2 though as there seem to be problems fetching the id of non-cat "11" tradeskills (so it's cooking, fishing, etc.)
I added a table that defines symbol-ids (as seen on https://wow.tools/dbc/?dbc=skillline&build=9.0.1.34615) for the localized names (used localisation as in other tables).
I also added a _GetSkillIcon(SkillID) function to fetch the symbol-string out of the table by using the current skill name.

Left problem is sorting and filtering:
I can't manage (as my LUA-knowledge is not as good as it should be) to modify the "FILTER_PROFESSIONS" buttons to work with those changes.
They didn't work before either as "Kräutersammeln" is no known skill in the DataStore-Characters table e.g.

Hope you can understand the problem a little bit and are able to find out and/or fix it for everybody.

**Comment by teelolws** [comment]
Fixed it in: https://github.com/teelolws/Altoholic-Retail/commit/bac0a04c3cc4d49f6b154642f6152af1bdbfe5e8

I just manually added Kräuterkunde to the localization table in Datastore_Crafts.

![image](https://user-images.githubusercontent.com/49792789/84444282-8b931c00-ac95-11ea-96d9-50e17380d4f2.png)

So its fixed for Herbalism. Was it a problem with any other professions?

**Comment by AmonFlorian** [comment]
Thanks, pal.
And I can't think of anything.
Is sorting/filtering fixed then as well?

**Comment by teelolws** [comment]
Sorting worked when I tried it. I didn't try filtering.
