### ISSUE TITLE
Bug when hovering over items in bags.

### ISSUE THREAD

**Issue by DiscordGregory** [teelolws/Altoholic-Retail#41]
I'm not sure if this is an error on your end or an interoperability error but sometimes when I hover over an item in my bags I get this error. 

67x DataStore_Characters\DataStore_Characters-r45.lua:168: attempt to index field '?' (a nil value)
[string "@DataStore_Characters\DataStore_Characters-r45.lua"]:168: in function <DataStore_Characters\DataStore_Characters.lua:167>
[string "=(tail call)"]: ?
[string "@Altoholic\Tooltip.lua"]:341: in function <Altoholic\Tooltip.lua:328>
[string "@Altoholic\Tooltip.lua"]:378: in function <Altoholic\Tooltip.lua:372>
[string "@Altoholic\Tooltip.lua"]:396: in function <Altoholic\Tooltip.lua:389>
[string "@Altoholic\Tooltip.lua"]:700: in function <Altoholic\Tooltip.lua:658>
[string "@Altoholic\Tooltip.lua"]:789: in function <Altoholic\Tooltip.lua:774>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1413: in function `ContainerFrameItemButton_OnEnter'
[string "@ArkInventory\ArkInventory-30928.lua"]:9006: in function `Frame_Item_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
character = <table> {
 XPMax = 124400
 RestXP = 0
 playedThisLevel = 1815
 zone = "Westfall"
 lastUpdate = 1591608760
 subZone = "Longshore"
 XP = 98573
 played = 53504
 money = 327281
 lastLogoutTimestamp = 1591608760
 realm = "Dalaran"
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "|c%s%s"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

When I disable Altoholic and Datastore I stop getting the error.

**Comment by teelolws** [comment]
What item?

**Comment by teelolws** [comment]
Give this a try, report back: 
[AddOns.zip](https://github.com/teelolws/Altoholic-Retail/files/4745320/AddOns.zip)

**Comment by DiscordGregory** [comment]
For some reason I was expecting a notification on curseforge when you responded :| oops, won't make that mistake again lol. I installed what you linked and it's working great so far :D

**Comment by teelolws** [comment]
I haven't uploaded it to curseforge yet. Still working on some other issues before I do.
