### ISSUE TITLE
DataStore_Crafts screen stutter

### ISSUE THREAD

**Issue by Chilius** [teelolws/Altoholic-Retail#42]
Since i installed the Altoholic-Retail+8.3-012 version from CurseForge i'm having issues when i use my professions. The screen starts stuttering and the FPS goes down to 40-50 (normally 60 on my PC).

I removed all Altoholic and DataStore related folders from the previous version i had installed (WoW\_retail_\Interface\AddOns folder), and also all the data (WoW\_retail_\WTF\ folder), so everything installed is from the Altoholic-Retail+8.3-012 version and the collected data is also only created by this version.

When i turn off DataStore_Crafts everything runs fine.

Easy way to reproduce the issue is to use a profession that produces a lot of the same items in a row.
For example produce 100 "Bolt of Linen Cloth" from 200 "Linen Cloth" (to keep it cheap) with tailoring or cut a lot of the same type of gems with jewelcrafting.

**Comment by teelolws** [comment]
The addon wasn't updating profession levels and discoveries and such after crafting things, so I added the lines near the bottom of this update: https://github.com/teelolws/Altoholic-Retail/commit/3d0ea72346088e00fe3525a39613acbf6801bb49 to make it rescan the profession after crafting something.

I'll look for a better way to do that.

**Comment by Chilius** [comment]
I understand why you did it, but hopefully it will be something optional in a future update because i don't like this behaviour at all. I prefer to open my profession window once or twice after i've learned something new over this.
I just made 80 "Bolt of Windwool Cloth" and it's just terrible to look at.
Why should it update tailoring 80 times when i haven't even learned something new?
For the moment i'm gonna disable DataStore_Crafts completely.

**Comment by teelolws** [comment]
Give this a try:
[DataStore_Crafts.zip](https://github.com/teelolws/Altoholic-Retail/files/4777338/DataStore_Crafts.zip)

**Comment by Chilius** [comment]
Yesterday i replaced the "DataStore_Crafts" folder from Altoholic-Retail+8.3-012 with the one from Altoholic-Retail-8.3-004 and so far i haven't encountered a problem. It was an experiment, but i've no idea if it can give problems in combination with some of the the newer parts of the addon.

So i gladly installed the new DataStore_Crafts.lua file you uploaded above and so far it's looking great: No more stuttering during the production of 40 "Bolt of Windwool Cloth".

I just started playing today, so if i find anything strange that's related to DataStore_Crafts i will let you know here. But so far: Great, thank you very much Teelo!

WoW without Altoholic isn't WoW to me and my 22 characters.
Many thanks for keeping this giant addon alive!

**Comment by teelolws** [comment]
Thanks for your donation! Heres an invite link to my patreon supporter discord server if you'd like to join: https://discord.gg/3JpCxS
