### ISSUE TITLE
Bug when opening Grids.

### ISSUE THREAD

**Issue by DiscordGregory** [teelolws/Altoholic-Retail#44]
Tested with only Altoholic + Datastore enabled, using latest curse release. Clicking on the "Grids" tab gave this error.

1x Altoholic\Templates\ClassIcon.lua:93: attempt to index local 'tc' (a nil value)
[string "@Altoholic\Templates\ClassIcon.lua"]:93: in function `SetClass'
[string "@Altoholic\Templates\ClassIconsContainer.lua"]:60: in function `Update'
[string "@Altoholic_Grids\TabGrids.lua"]:46: in function `Update'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Altoholic\Core.lua"]:376: in function <Altoholic\Core.lua:373>
[string "@Altoholic\Core.lua"]:424: in function `OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
frame = <unnamed> {
 optionFormat = "Tabs.Grids.%s.%s.Column%d"
 SetClass = <function> defined @Altoholic\Templates\ClassIcon.lua:85
 OnBind = <function> defined @Altoholic\Templates\Button.lua:5
 SetIconSize = <function> defined @Altoholic\Templates\Button.lua:14
 SetIcon = <function> defined @Altoholic\Templates\Button.lua:9
 IconBorder = <unnamed> {
 }
 0 = <userdata>
 Icon_OnEnter = <function> defined @Altoholic\Templates\ClassIcon.lua:66
 Icon = <unnamed> {
 }
 DrawTooltip = <function> defined @Altoholic\Templates\ClassIcon.lua:120
}
class = ""
faction = ""
icon = <unnamed> {
 0 = <userdata>
}
border = <unnamed> {
 0 = <userdata>
}
tc = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "Glues\CharacterCreate\UI-CharacterCreate-Classes"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tc' (a nil value)"
ICON_PARTIAL = "RaidFrame\ReadyCheck-Waiting"

**Comment by teelolws** [comment]
Your Grids are trying to load a character you'd either deleted or has corrupt data. Reset your Grids columns:
![image](https://user-images.githubusercontent.com/49792789/84705649-d8396880-afaf-11ea-8172-17aa03fb2fdc.png)

**Comment by DiscordGregory** [comment]
You can't reset anything like that 

![Capture](https://user-images.githubusercontent.com/59945495/84711648-d3839e80-af34-11ea-9382-32e2c0bd7e1a.PNG)

but your comment about corrupt data led me to delete my Savedvariables which fixed it :)
