### ISSUE TITLE
Essence list (enhancement)

### ISSUE THREAD

**Issue by Fagerinfoco** [teelolws/Altoholic-Retail#45]
Thank you for taking over this wonderful addon. I would be so lost without it.  This is more a request than an issue. Would it be possible to put a grid in for the essences available for the heart of azeroth? Like the corruption grid, but showing which ones and at which rank have been obtained.  Thank you

**Comment by teelolws** [comment]
I could, but it would be a lot of effort for a feature that is being removed from the game in a couple of months. I'd rather focus on making modules that track things being added in Shadowlands.
