### ISSUE TITLE
Altoholic-Retail cross-server item count tooltip?

### ISSUE THREAD

**Issue by TinyTrbl** [teelolws/Altoholic-Retail#5]
Hello...

**Problem:**
- Cross-server/cross-realm item count tooltip does not work for me.

**Details:**
- I have chars on two servers Draenor (Horde) and Silvermoon (Alliance) - side note - i do not think that these servers are "connected".
- Item count tooltip is only active for characters from the server that i am currently on, but not from all my servers.
- I have enabled all these checkboxes in Altoholic tooltip options.
![Wow](https://user-images.githubusercontent.com/45721596/75025575-80c93700-54ac-11ea-9b30-4595accd194f.jpg)

**What i tried to do:**
- I have tried sending heirloom items to "link" these servers (found this old tip in google) and it havent worked for me.
- I also tried to edit config (old fix from https://www.mmo-champion.com/threads/1923146-Altoholic-problem ) with no avail.

Please, can you fix it if possible?
Thank you.

**Comment by teelolws** [comment]
I think the problem here is Thaoky never intended for the tooltips to show counters of items outside of your connected servers. I can kind of see the logic behind this: the tooltips are there to show you where you can get more of an item, you want, what use is it to show the item on servers you can't mail them from?

I can look at creating another option like "Also show counters for unconnected realms". It will take a fair bit of work to do this, so it won't be ready for a while.

**Comment by TinyTrbl** [comment]
> what use is it to show the item on servers you can't mail them from?

Well, it makes as much sense as showing item count for a different faction (as you cant transfer anything to another faction, so there is practically no difference between the faction on connected and  non-connected servers). This is useful to someone like me, as it can eliminate unnecessary item checks (BoE transmogs, leveling items, rare consumables, etc) and re-logins to/on "the other side".

Just my 2 altoholic cents, hehe. Thank you!

**Comment by teelolws** [comment]
While working on this, I discovered a related issue: its not actually showing search results for stuff on other realms in Altoholic_Search, so I'm going to move to fixing that bug first.

**Comment by teelolws** [comment]
Hi, can you test the build I just uploaded please. I've added an option for showing counters across all realms.

**Comment by TinyTrbl** [comment]
> Hi, can you test the build I just uploaded please. I've added an option for showing counters across all realms.

Hello! I am very sorry that i was unable to test it. I saw that you already pushed it into release version. So... yeah i am sad and happy at the same time. Thank you!
