### ISSUE TITLE
Delete Alt

### ISSUE THREAD

**Issue by Nancara** [teelolws/Altoholic-Retail#50]
On the summary page, the Alt I want to delete is not there, after I right clicked and deleted. However, the Character Tab still shows an Alt on a server I no longer play after the Alt was deleted. Also, Alts that were created then deleted on the servers I play still show in the list of Alts. I deleted the WTF files for the Alts but they still show on the list. This is annoying when you are trying to find the Alt you want. Thanks for looking into this issue.

**Comment by teelolws** [comment]
Is it showing like this for you, too?

![image](https://user-images.githubusercontent.com/49792789/85211497-0c40cf00-b39e-11ea-8b1e-1b448cbafa2b.png)

**Comment by teelolws** [comment]
The glitch has clearly happened to me before, but I can't get it to happen again. I remade the character, logged into it, logged back to my main, and tried deleting it from Altoholic and it deleted properly.

I tried a few different times with different combinations and they're all being removed from Altoholic the way they should.

So I'm not sure why its happening. There must be some setup thats making the character not get deleted properly, but I can't figure it out.

As a workaround, completely exit WoW, open up your DataStore saved variable file:
![image](https://user-images.githubusercontent.com/49792789/85211987-68a5ed80-b3a2-11ea-8392-35953cb76312.png)

Find the block underneath "Characters":
![image](https://user-images.githubusercontent.com/49792789/85211998-7fe4db00-b3a2-11ea-8e9b-8b68f45fed0a.png)
Delete that highlighted chunk of text, and save.

**Comment by Nancara** [comment]
Thank you, that got rid of them.
