### ISSUE TITLE
Problem with inventory

### ISSUE THREAD

**Issue by lovs2build** [teelolws/Altoholic-Retail#52]
When I mouse over an item it is showing an item on X toon when i go to look nothing there. When I remove item from guild vault and go to another toon and search it still shows items in guild vault I removed. Clearing the inventory.lua and rebuilding the data base doesn't work, completely removing addon and reinstalling does not fix, it is not keeping track of items.

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Retail/compare/b931cc65b836...5fee82e360a1

Uploading it to Twitch now as this is a pretty serious bug that needs to skip the testing phase.
