### ISSUE TITLE
Agenda Calendar

### ISSUE THREAD

**Issue by Nancara** [teelolws/Altoholic-Retail#54]
Is there a way to put the world bosses on the Calendar?  I forget which toons have done it and which still need to do it. The page for emissary quests reset each day so that is also hard to track. Thanks

**Comment by teelolws** [comment]
Added world bosses to the calendar, give it a try: [Altoholic-test.zip](https://github.com/teelolws/Altoholic-Retail/files/4915912/Altoholic-test.zip)


For the emissary quests stuff, not sure what you mean. Are you referring to Grids/Emissaries? I did this yesterday and it seems to be showing correctly:
![image](https://user-images.githubusercontent.com/49792789/87368453-ce684c80-c5d1-11ea-9702-07ba1321b68e.png)
