### ISSUE TITLE
Feature Request: Add Item Counter Ignore List

### ISSUE THREAD

**Issue by comiluv** [teelolws/Altoholic-Retail#55]
A built in feature that does something this(https://www.curseforge.com/wow/addons/altoholic-count-hider) does would be nice. Seeing that I have many number of Hearthstones, Dalaran Hearthstones, Darkmoon Book, etc. is very screen-cluttering everytime I mouse over those items.

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Retail/compare/c76cfc6c2e04...0c94b3f7e6b1
