### ISSUE TITLE
Feature Request: Browse faction reputations across alts

### ISSUE THREAD

**Issue by comiluv** [teelolws/Altoholic-Retail#56]
I think it would be convenient if the user can browse a specific faction's reputation across alts using this addon.
Just like item amount counter that remembers how many items an alt has in the bag or bank, mouse-overing faction reputation bar or something similar could show reputation numbers and status (exalted, revered, etc.) across alts.

**Comment by teelolws** [comment]
Grids -> Reputations.

![image](https://user-images.githubusercontent.com/49792789/87875549-0fbf8880-ca26-11ea-8a70-8105b347e552.png)
