### ISSUE TITLE
attempt to call global 'GetQuestLogSelection' (a nil value)

### ISSUE THREAD

**Issue by OmarMAbbasi** [teelolws/Altoholic-Retail#59]
```
Message: ...terface\AddOns\DataStore_Quests\DataStore_Quests.lua:327: attempt to call global 'GetQuestLogSelection' (a nil value)
Time: Tue Jul 21 06:33:19 2020
Count: 1
Stack: ...terface\AddOns\DataStore_Quests\DataStore_Quests.lua:327: attempt to call global 'GetQuestLogSelection' (a nil value)
[string "@Interface\AddOns\DataStore_Quests\DataStore_Quests.lua"]:327: in function <...terface\AddOns\DataStore_Quests\DataStore_Quests.lua:290>
[string "@Interface\AddOns\DataStore_Quests\DataStore_Quests.lua"]:413: in function <...terface\AddOns\DataStore_Quests\DataStore_Quests.lua:412>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```

**Comment by teelolws** [comment]
Can you hop on beta, open your Quest Log, run this, and show my what it outputs into your chatlog (use screenshots or a copy/paste addon to make it easier):

/run for k,v in pairs(C_QuestLog.GetInfo(1)) do print(k) end

You'll get a long text dump, something like
title
level
groupSize
isHeader
isCollapsed
etc

I need to get them all in the right order.

**Comment by OmarMAbbasi** [comment]
![image](https://user-images.githubusercontent.com/2753712/88109292-1867aa00-cb5f-11ea-964d-2dbe4a4a4582.png)

**Comment by OmarMAbbasi** [comment]
That was quick, so I did it during my coffee break, but I'm working for a few more hours. 

I have raid tonight, but if you DM me your discord or something we can figure out something and I can stream and help bash out some of these for you/test stuff you need me to.

**Comment by teelolws** [comment]
Sure! https://discord.gg/DKE8wU

**Comment by teelolws** [comment]
Allright got most of the quest API changes. Might be issues since I can't test it. https://github.com/teelolws/Altoholic-Retail/commit/d4ac44fb0b7139a911d008ed0529fbe4eb7984bf
