### ISSUE TITLE
Feature request: Make ignore list editable in-game

### ISSUE THREAD

**Issue by comiluv** [teelolws/Altoholic-Retail#69]
Regarding #55, I think it would be preferable to be able to add and delete items to ignore. Currently, for example, user needs to manually edit tooltip.lua to add [Flight Master's Whistle](https://www.wowhead.com/item=141605/flight-masters-whistle) to be ignored but in-game option would be preferred

**Comment by teelolws** [comment]
This should do it: 
![image](https://user-images.githubusercontent.com/49792789/88600938-86622300-d0c3-11ea-81c6-ec89545c56e9.png)

Added: https://github.com/teelolws/Altoholic-Retail/compare/cc5e02841449...85114c429c0f
