### ISSUE TITLE
PVP Conquest Points

### ISSUE THREAD

**Issue by Gnilrats** [teelolws/Altoholic-Retail#70]
This isn't actually a bug, but I couldn't find a place for feature requests.

Can you add the PVP Conquest tokens to the Currency Grid?

The Currency Index number is 1602 

If you don't play much pvp this is a BfA currency that caps at 500 each week and upon reaching the max it provides access to a war chest that rewards items.

What I would love, is to be able to use Altoholic to see the Conquest points of all of my characters (and possible the active war chest) without having to log in to each of my characters, flying to the pvp vendors to check on whether i earned the chest that week or not.

Hope this wasn't too confusing.

**Comment by teelolws** [comment]
1602 might be the currency ID, but the function for getting currency details isn't returning how much of that currency you actually have:

![image](https://user-images.githubusercontent.com/49792789/88729938-14eca800-d189-11ea-94fb-ae8c12f298f1.png)

My character has 175 but its returning actualAmount = 0.

**Comment by teelolws** [comment]
I can't add it to Grids - that strictly uses Blizzards Currency UI and Conquest Points aren't on that list (anymore).

I've added it to Summary: 

![image](https://user-images.githubusercontent.com/49792789/88730604-9133bb00-d18a-11ea-83d8-8ed23e4740d5.png)

https://github.com/teelolws/Altoholic-Retail/compare/85114c429c0f...e16ead61d9b6

Uploaded a beta, try it out.

**Comment by teelolws** [comment]
Fixed an Lua error caused by characters that haven't been logged into since that patch: https://github.com/teelolws/Altoholic-Retail/commit/baaa7b402549ba9fc2346f2bb7f49e99bdfa4f0b
