### ISSUE TITLE
Altoholic summary no longer shows any characters

### ISSUE THREAD

**Issue by VStormborn** [teelolws/Altoholic-Retail#71]
I've used Altoholic for years without any problems, but as of around a month ago, my character summary screen stopped showing all of my characters, no matter what options I selected. It would only show shamans and mages for some reason. Then, it switched to just mages. There didn't appear to be any rhyme or reason to it. I went through a previous issue that was submitted this year and tried following the steps you recommended to that person. I cut and pasted all my Saved Variables for Datastore into a folder on my desktop - a different drive than the one my main addons folder is on - and started fresh and I'm currently logging into all of my characters. (I'm at the maximum of 50 right now.) 
So far, it's still not working. When I view the summary section, there's nothing there. If I go to the Characters tab and hover over characters > Realm > ... my characters show up so it appears to just be the summary that's broken. I don't know what you need to confirm or diagnose this issue. I'm attaching a few screenshots to show the summary and the characters. 
Notice that now my mage is the only character showing up in the summary section, so the problem is still happening and it doesn't make any sense. 
![Altoholic screen Bellethiel](https://user-images.githubusercontent.com/69020678/88985996-5ff4e100-d297-11ea-8624-bb422457e1b2.jpg)
![Altoholic screen Bellethiel 2](https://user-images.githubusercontent.com/69020678/88985998-61260e00-d297-11ea-9358-65ef61f748e1.jpg)
![Altoholic screen Elentari](https://user-images.githubusercontent.com/69020678/88986002-6420fe80-d297-11ea-80a4-f1648e65981e.jpg)
![Altoholic screen Elentari 2](https://user-images.githubusercontent.com/69020678/88986007-65eac200-d297-11ea-81ba-92692eb018ca.jpg)

**Comment by teelolws** [comment]
Sorry, my addon isn't version 8.3.006.

**Comment by VStormborn** [comment]
I see. So I have to redownload your Teelo's fork version? 
Do I still need DataStore?

**Comment by VStormborn** [comment]
My summary section is still broken. I completely removed the old Altoholic and just have yours now. I guess I'll re-delete all of my saved variables.

**Comment by VStormborn** [comment]
Well, I'm pretty sure it was all user error. I think I had a filter turned on for specific professions that I never reset, so it was working and only showing me the characters that had those professions. I'm going through and checking to see if any of the DataStore modules are now defunct.
Thanks.

**Comment by teelolws** [comment]
>  Do I still need DataStore?

You need the Datastore that is provided with my fork. I've made fixes to it over the versions.
