### ISSUE TITLE
Auction visit not updating

### ISSUE THREAD

**Issue by Kurisu68** [teelolws/Altoholic-Retail#75]
Having checked to make sure all Datastore are turned on, it's not updating visits to the auctioneer on the activity tab (mailbox and bank are updating as expected).

**Comment by teelolws** [comment]
Thank Blizzard for this. It can't view your auctions on Retail anymore until you click into the "listings" tab. The natural one, not the auctioneer one. Theres no way around this, Blizzard locked it down.

**Comment by Kurisu68** [comment]
And than I have a request, under activities, can the BFA mission table be added?  I see the WoD and Legion one, would be helpful if I could see which toons have missions to collect in the current expansion.  Thank you for the prompt reply!!!!

**Comment by teelolws** [comment]
Allright I'll look into that tomorrow. I thought the garrisons section covered it but I'd never really checked.

**Comment by Kurisu68** [comment]
also.. recheck the update on auction.  Just uninstalled your new update, and reinstalled Thaoky's.. updated the auction visit as anticipated.

> Thank Blizzard for this. It can't view your auctions on Retail anymore until you click into the "listings" tab. The natural one, not the auctioneer one. Theres no way around this, Blizzard locked it down.

Check this.  Just uninstalled your update, and reinstalled Thaoky's... auction datastore updated as it should.

**Comment by teelolws** [comment]
When you open the auction house or are you clicking the tab for the auction listings?

**Comment by Kurisu68** [comment]
Yes.. in both versions

**Comment by Kurisu68** [comment]
Sorry, I'm no good at writing addon, so I can't be much more help than "it works here, it doesn't work there" :(

**Comment by teelolws** [comment]
But... Thaoky's version of Datastore_Altoholic has a bunch of code that doesn't make sense. He's using `C_AuctionHouse.GetNumReplicateItems` which is for the once-every-15-minutes scan of the entire auction house, not for getting your own listings.

**Comment by Kurisu68** [comment]
:( Sorry, can't comment on his code vs yours.  But his is seeing the auctions I posted from my banker, and registering when each toon visits the AH, and updating that a visit has been made.

**Comment by teelolws** [comment]
Are you using an AH addon?

**Comment by Kurisu68** [comment]
Yes, Auctioneer 8.3 Beta 4.4

**Comment by teelolws** [comment]
(Without running an AH addon) when I tested it with Thaoky's version just now, it updated the "visited" time to say "< an hour" as soon as I opened the AH, but its still listing zero auctions:
![image](https://user-images.githubusercontent.com/49792789/89733348-ffd91880-daa8-11ea-9d01-20009968e9af.png)

After I click into the Auctions tab, nothing changed. Still claims I have zero auctions when I actually have one: 
![image](https://user-images.githubusercontent.com/49792789/89733354-12ebe880-daa9-11ea-81ea-5b7e6f2c00b4.png)

Now, I switch back to version 030, clear out my data, and try again. As soon as I open the AH, no "visited" time, and no auctions listed:
![image](https://user-images.githubusercontent.com/49792789/89733424-842b9b80-daa9-11ea-9b14-96afcc40a055.png)

When I click into the Auctions tab, now it has my auction listed and says I've visited "<an hour" ago.
![image](https://user-images.githubusercontent.com/49792789/89733445-9efe1000-daa9-11ea-8a46-4b36708242db.png)

This is as I expect it to work. It can't see my auctions until I click into the Auctions tab.

**Comment by Kurisu68** [comment]
Hmm. okay... atm, I'm working with the old version, will be reinstalling in a minute or three.

**Comment by Kurisu68** [comment]
Ok.. just reinstalled your update.. you're right about the # of auctions not showing up with the old version, and showing up now.  Did that api change happen with the patch last Tuesday (aug 4), by chance?

**Comment by teelolws** [comment]
No its been broken ever since they remade the AH in 8.3. Addons simply can't see the list of what you have for sale until you actually click the Auctions tab at the AH:
![image](https://user-images.githubusercontent.com/49792789/89733921-ee920b00-daac-11ea-8cba-d14a718c7b2f.png)

There is code in the game that is _supposed_ to let us ask the server for a list of auctions, `C_AuctionHouse.QueryOwnedAuctions`, but it doesn't work. I call that and... nothing happens. It still thinks I have no auctions until I click that Auctions tab.

I have a workaround that isn't perfect, but is the best I can do: while you're selling items in the Sell tab, Altoholic (my version) will remember what you list while you list them. That Visited column won't be updated, but your Auctions counter will.

**Comment by Kurisu68** [comment]
Okay, that seems reasonable - and a huge thank you for your time looking into this with me... I used to know how to code (many moons ago), and I know the frustration it can be...  So from the bottom of my heart, thank you.

**Comment by teelolws** [comment]
All good. I'll look into the mission table stuff tomorrow.
