### ISSUE TITLE
Unable to select currencies in the currency tab

### ISSUE THREAD

**Issue by WoLf-** [teelolws/Altoholic-Retail#78]
Hello! I switched to this fork as soon as I saw the ability to customize which currency to show in the main tab. Thanks for having picked this up and improving the addon!

I'm having a problem with that tho.. I can right click and see a list of all the currencies I can pick, but clicking any doesn't do anything. I don't receive errors, no messages, it just closes the menu and doesn't change the selected currency.

I tried on a completely blank database with no other addons, to the same result.

Gif of the issue: https://i.imgur.com/rx99f7a.gif

**Comment by teelolws** [comment]
Whoops. Fixed in https://github.com/teelolws/Altoholic-Retail/commit/159134f608918eca378f2ef202ee8cf89fe65ca6
