### ISSUE TITLE
Heartstones opt out

### ISSUE THREAD

**Issue by pbjelly468** [teelolws/Altoholic-Retail#8]
Would appreciate if you could have an opt-out for all heartstones.  I have so many toons and when I mouse over the heartstones, the list is so long.  I know all my alts have them so would like to not see the list, if possible. Many thanks for the awesome add-on.

**Comment by teelolws** [comment]
Hah. I'll add this to my TODO list. Its never been a problem for me because I use toys for hearthstones, so that I'm not taking up a bag slot.

**Comment by teelolws** [comment]
Would disabling the new option solve this issue for you?

![image](https://user-images.githubusercontent.com/49792789/75843584-61c98e00-5e38-11ea-83c2-72eb5f57c367.png)

Do you want to see tooltip counts for other servers for all items except your Hearthstone?
