### ISSUE TITLE
Error getting currency

### ISSUE THREAD

**Issue by Kurisu68** [teelolws/Altoholic-Retail#83]
This looks to be a Blizzard issue, I'm guessing.  But, when I go to get currency info for alts, I get the following error:

Date: 2020-08-15 01:25:37
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\DataStore_Currencies\DataStore_Currencies.lua line 200:
   attempt to index local 'currency' (a number value)
Debug:
   [string "@DataStore_Currencies\DataStore_Currencies.lua"]:200:
      ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:196
   [string "@DataStore_Currencies\DataStore_Currencies.lua"]:215:
      ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:210
   [string "=(tail call)"]: ?
   [string "@Altoholic\Tooltip.lua"]:675:
      Altoholic\Tooltip.lua:665
   [string "@Altoholic\Tooltip.lua"]:717: SetCurrencyToken()
   [string "*:OnEnter"]:2:
      [string "*:OnEnter"]:1
Locals:
character = <table> {
 CurrencyInfo = <table> {
 }
 lastUpdate = 1596980917
 Conquest = 0
 Archeology = <table> {
 }
 Currencies = <table> {
 }
}
index = 1
ref = <table> {
 Currencies = <table> {
 }
 CurrencyTextRev = <table> {
 }
 HeadersRev = <table> {
 }
 Headers = <table> {
 }
}
currency = 3
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'currency' (a number value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 Printf = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "DataStore_Currencies"
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 Characters = <table> {
 }
 IsModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 ThisCharacter = <table> {
 }
 baseName = "DataStore_Currencies"
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnDisable = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:382
 enabledState = true
 OnEnable = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:368
 RegisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnInitialize = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:332
 UnregisterAllEvents = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 UnregisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  Altoholic, v8.3-006
  AstralKeys, v3.25
  CanIMogIt, v8.3.0v1.25
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreKeystones, vv8.3-008
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  MountJournalEnhanced, v2.7.2
  MountSpy, v8.3.0-01
  MoveAnything, v17.1.0
  Postal, vv3.6.2
  Stubby, v8.3.BETA-4-4 (NzothsFolly)
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=30e)

**Comment by teelolws** [comment]
Your addon is out of date.

**Comment by Kurisu68** [comment]
There was an update on twitch today, which I installed.  The problem persists...

Date: 2020-08-15 12:01:12
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\DataStore_Currencies\DataStore_Currencies.lua line 200:
   attempt to index local 'currency' (a number value)
Debug:
   [string "@DataStore_Currencies\DataStore_Currencies.lua"]:200:
      ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:196
   [string "@DataStore_Currencies\DataStore_Currencies.lua"]:215:
      ...AddOns\DataStore_Currencies\DataStore_Currencies.lua:210
   [string "=(tail call)"]: ?
   [string "@Altoholic\Tooltip.lua"]:675:
      Altoholic\Tooltip.lua:665
   [string "@Altoholic\Tooltip.lua"]:717: SetCurrencyToken()
   [string "*:OnEnter"]:2:
      [string "*:OnEnter"]:1
Locals:
character = <table> {
 CurrencyInfo = <table> {
 }
 lastUpdate = 1596980917
 Conquest = 0
 Archeology = <table> {
 }
 Currencies = <table> {
 }
}
index = 1
ref = <table> {
 Currencies = <table> {
 }
 CurrencyTextRev = <table> {
 }
 HeadersRev = <table> {
 }
 Headers = <table> {
 }
}
currency = 3
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'currency' (a number value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 Printf = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "DataStore_Currencies"
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 Characters = <table> {
 }
 IsModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 ThisCharacter = <table> {
 }
 baseName = "DataStore_Currencies"
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnDisable = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:382
 enabledState = true
 OnEnable = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:368
 RegisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnInitialize = <function> defined @Interface\AddOns\DataStore_Currencies\DataStore_Currencies.lua:332
 UnregisterAllEvents = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 UnregisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  Altoholic, v8.3-006
  AstralKeys, v3.25
  CanIMogIt, v8.3.0v1.25
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreKeystones, vv8.3-008
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  MountJournalEnhanced, v2.7.2
  MountSpy, v8.3.0-01
  MoveAnything, v17.1.0
  Postal, vv3.6.2
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=2e8)

**Comment by teelolws** [comment]
Your DataStore is out of date. Your Twitch client mustn't be updating it.

**Comment by Kurisu68** [comment]
[https://prnt.sc/u007kt](url)

**Comment by Kurisu68** [comment]
Can you give me a d/l link to the current version, and I'll install it manually.

**Comment by teelolws** [comment]
Delete the one by Thaoky. Only install mine.

**Comment by Kurisu68** [comment]
ah, my bad, sorry.  I was under the mistaken impression you were just patching the old version, not a complete redo. :( 🥇
