### ISSUE TITLE
Suggestion: Attunements??

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/Altoholic-Retail#84]
If you're ever in the mood to add functionality, it would be nifty to have an option to look at a char's "attunements" for an expansion. Something like what wowhead does with it's Legion/BfA Attunement tools.

**Comment by teelolws** [comment]
Uhh. How would that work. Maybe I could make something for Classic to track raid attunements, but... Retail? Attunement for what?

**Comment by nancikennedy** [comment]
It not attunements in the classic sense. It's a questline progression thing, where it only checks for the completion of things that lock further progression in the world. For example, you accepted to quest for the Vindicaar did a few things but didn't do "Into the Night" which means the portal to Argus isn't present at Krasus Landing in New Dalaran in Broken Isles. Now you don't know why the portal isn't there...wowhead's tracker (attunements is their word for it) just lists this as:

Getting to Argus
Quest: Assault on Broken Shore -> Complete
Quest: Into the Night -> Incomplete

It's essentially just a pretty GUI list of important bottleneck isQuestComplete flags.

[Wowhead version](https://www.wowhead.com/attunement/) that I was referring to for Legion. Just use that to look up your own char and you'll see the concept I'm talking about.

Implementing into Altoholic
You could add an icon to the Characters tab header, with a submenu for the various expansion "attunement" lists. Or, add a new section to the Grid tab. Since it's quest-based, rather than item-based, it might not be worth the hassle in the long run. Just an idea for the future. :)

**Comment by teelolws** [comment]
Interesting. Can you give me the right wowhead link? 
![image](https://user-images.githubusercontent.com/49792789/90375203-bc923180-e0c8-11ea-80cf-05bcad454930.png)

**Comment by nancikennedy** [comment]
Whoops! Truncated that. It should be https://www.wowhead.com/attunement/legion

**Comment by teelolws** [comment]
Interesting idea. I'll add it to my list.

**Comment by teelolws** [comment]
I've decided I'm not going to do this. Theres a lot of account-wide stuff to the attunements, and a lot of complexity that makes it outside of the scope of Altoholic.
