### ISSUE TITLE
Minimap button location not properly flexible.

### ISSUE THREAD

**Issue by mjbrowns** [teelolws/Altoholic-Retail#85]
Minimap button location seems to be bound only to original blizzard UI scale and minimap frame.  

Anyone using Altoholic with a UI that changes the map frame (e.g. square) or scales the entire frame will find that the Altoholic icon must be put in the top left corner, otherwise it ends up somewhere in the middle of the minimap.

I'm using LUI for example.  Most addons that use LibDataBroker for their minimaps seem to be able to capture the active minimap frame boundaries and allow dragging of the icon wherever it needs to be.

**Comment by teelolws** [comment]
Try messing with the Minimap Icon Radius slider:

![image](https://user-images.githubusercontent.com/49792789/90443861-044ca380-e131-11ea-97a2-a4dac6b65f19.png)

I was able to get the icon to sit at a spot that would probably be the corner of a square minimap:

![image](https://user-images.githubusercontent.com/49792789/90443933-2514f900-e131-11ea-9d22-2732cc8c2f09.png)

If you can't get it to line up where you want, let me know what minimap addon you're using and I'll take a look.
