### ISSUE TITLE
Grid problem 

### ISSUE THREAD

**Issue by SFFCorgi** [teelolws/Altoholic-Retail#86]
I do beg your pardon if this is just me being utterly dense, but I have been trying to update my notes on my characters' Timewalking badges; I cannot recall how to scroll right on the Currency grid in specific so I can check the 2nd half of the alphabet (I have 22 toons on Wyrmrest Accord).  They all have assigned columns, I can see that when I mouse over the character-assignment row -- but I can't get TO them.  Please advise/instruct?

**Comment by teelolws** [comment]
I don't understand. Can you show a screenshot or two? You can just copy/paste pictures in here.

**Comment by SFFCorgi** [comment]
Perfect timing, I checked this just before logging out.

![image](https://user-images.githubusercontent.com/41975713/90477152-bf4c5100-e0df-11ea-8e14-01a8a02bccdd.png)

**Comment by SFFCorgi** [comment]
You can see that the cursor is over the furthest-right character, Minionne, but there's nine more I can't see!

**Comment by teelolws** [comment]
Your addon is out of date. Uninstall the one you have, switch to this one: https://www.curseforge.com/wow/addons/altoholic-retail/

**Comment by SFFCorgi** [comment]
That's an easy fix!  Thank you - I'd been updating via Twitch.

**Comment by teelolws** [comment]
You still can, just update with that project instead.
