### ISSUE TITLE
Datastore not storing empty guild tabs?

### ISSUE THREAD

**Issue by cxmplex** [teelolws/Altoholic-Retail#88]
https://github.com/teelolws/Altoholic-Retail/blob/777af0ce31a6f5ee2fedf13258b652c22b947d12/Altoholic_Guild/Frames/GuildBank.lua#L64

**tab** here is `nil`, causing `if not tab.name` to throw a lua error. 

The preceding call is:

`local tab = DataStore:GetGuildBankTab(currentGuildKey, currentGuildBankTab)`

I believe the issue is that DataStore is not storing tabs that do not contain items, however I haven't looked into DataStore that much so I'm not sure.

**Comment by teelolws** [comment]
I didn't write that code, and chances are it was never tested on an empty gbank tab! I'll take a look tomorrow.

**Comment by teelolws** [comment]
Can't replicate your issue. Tested with an empty gbank and it worked just fine:
![image](https://user-images.githubusercontent.com/49792789/91223175-5c5c5900-e774-11ea-9731-6e0999d97d1a.png)
