### ISSUE TITLE
Shadowlands: possible things to track

### ISSUE THREAD

**Issue by teelolws** [teelolws/Altoholic-Retail#90]
Callings. Like Emissary quests, but have to pick them up from Covenant sanctum.

Sanctum upgrades? Like Garrison buildings?

Renouned upgrades? whatever that is.

I understand there is a new mission table. Does it use the same API as previous expansions? C_Garrison.GetAvailableMissions
Does it have followers? Do they also use C_Garrison.GetFollowers?

What is anima? How does it work? Anything I'd want to track there?

Investigate this Abominable Stitching UI. Could it just be treated as a Crafting Profession? Maybe even make a section for weird crafting things like this such as the Rustbolt vendor.

Runecarver legendaries. Track which ones the character has so far? And what rank.

**Comment by jscharnitzke** [comment]
## General Bugs
- `NUM_LE_TRANSMOG_COLLECTION_TYPES` and `LE_TRANSMOG_COLLECTION_TYPE_*` variables removed in favor of `Enum.TransmogCollectionType`

## Callings
![image](https://user-images.githubusercontent.com/2000659/91646340-e9b4dd00-ea02-11ea-8fce-8b82337c35f6.png)

**Global API Calls:**
- `C_CovenantCallings.AreCallingsUnlocked`
- `C_CovenantCallings.RequestCallings`
- `C_QuestLog.IsQuestCalling`

## Sanctum Upgrades
## Renown Upgrades
## Mission Table
### Adventures (Missions)
![image](https://user-images.githubusercontent.com/2000659/91646293-7b701a80-ea02-11ea-9ee6-fd78070b1ee2.png)
![image](https://user-images.githubusercontent.com/2000659/91646310-a35f7e00-ea02-11ea-9ec7-73bec9c7ee92.png)

- [ ] Add 9.0 constants, functions, and initializers for all of the missions and active missions in `DataStore_Garrisons`.
### Adventurers (Followers)
![image](https://user-images.githubusercontent.com/2000659/91646330-c4c06a00-ea02-11ea-8001-dc14d269ec66.png)

- Get Covenant followers: `C_Garrsion.GetFollowers(Enum.GarrisonFollowerType.FollowerType_9_0)`
- Covenant followers start at ilvl 800

**Comment by teelolws** [comment]
Covenant callings:

Hook event COVENANT_CALLINGS_UPDATED

Blizzard processes the event with 
![image](https://user-images.githubusercontent.com/49792789/91647026-ffc9a880-eaa9-11ea-8cad-0d76a402ecd6.png)

and 

![image](https://user-images.githubusercontent.com/49792789/91647035-0d7f2e00-eaaa-11ea-8337-96080c1f4378.png)

**Comment by teelolws** [comment]
Shelve Sanctum Upgrades. Track renown level. int 1-40.

C_CovenantSanctumUI.GetRenownLevel()

watch event: COVENANT_SANCTUM_INTERACTION_STARTED

**Comment by teelolws** [comment]
Followers continue to use garrison functions.

![image](https://user-images.githubusercontent.com/49792789/91647261-c9d9f380-eaac-11ea-8569-fe1d1abb75f4.png)

**Comment by teelolws** [comment]
Missions unchanged:

![image](https://user-images.githubusercontent.com/49792789/91647291-597fa200-eaad-11ea-9c41-561f51ef4ce6.png)

**Comment by jscharnitzke** [comment]
`C_LegendaryCrafting.GetRuneforgePowers()` to get a list of known legendary powers.
![image](https://user-images.githubusercontent.com/2000659/91648741-1c210300-ea20-11ea-88a8-7d968d489738.png)

`C_LegendaryCrafting.GetRuneforgePowerInfo(powerID)` to get details for a specific power.
![image](https://user-images.githubusercontent.com/2000659/91648758-3a86fe80-ea20-11ea-9360-86ba582e0c8a.png)

**Comment by teelolws** [comment]
Callings inserted into Grids alongside Emissaries.
![image](https://user-images.githubusercontent.com/49792789/91649041-76bf6b00-eac3-11ea-9b52-6ab77f90f0c7.png)


Renown placed into Summary in the Misc section.

![image](https://user-images.githubusercontent.com/49792789/91649044-7d4de280-eac3-11ea-9b6e-a49f345830ad.png)

**Comment by teelolws** [comment]
9.0 followers added to grids
![image](https://user-images.githubusercontent.com/49792789/91649202-76c06a80-eac5-11ea-9de1-c9266767dd7b.png)

**Comment by teelolws** [comment]
And missions added to Characters:
![image](https://user-images.githubusercontent.com/49792789/91649261-1847bc00-eac6-11ea-917c-b7c9fbae2935.png)

**Comment by jscharnitzke** [comment]
Callings grid doesn't seem to be populating:

![image](https://user-images.githubusercontent.com/2000659/91650276-47ace900-ea32-11ea-9001-e89792129c0a.png)
![image](https://user-images.githubusercontent.com/2000659/91650280-509dba80-ea32-11ea-9f76-6ba3810cc604.png)

Adventurers grid also isn't showing anything:
![image](https://user-images.githubusercontent.com/2000659/91650322-df123c00-ea32-11ea-8db7-c888c236ed08.png)
![image](https://user-images.githubusercontent.com/2000659/91650323-e6d1e080-ea32-11ea-99cb-6c73adab054e.png)

**Comment by teelolws** [comment]
TODO: Add some code to "expire" calling quests when they hit their time limit, removing them from the characters arraw.

**Comment by teelolws** [comment]
Somethings up with the code to collect Calling quests, and I probably won't be able to fix it until I get beta access myself and can figure it out:
![image](https://user-images.githubusercontent.com/49792789/91784675-8f608a00-ec57-11ea-9b87-0b83a0d8405d.png)

Either the payload isn't matching what I expect, or its not saving properly.

**Comment by teelolws** [comment]
Well, I think the Shadowlands tab is in a "good enough" state for now. I'll update the Sanctum Features bit over time when I have characters in Kyrian and Necrolords to check out how they work.
