### ISSUE TITLE
Cannot mix characters from multiple connected realms in grid views

### ISSUE THREAD

**Issue by nzall** [teelolws/Altoholic-Retail#91]
I play across multiple connected realms: I originally started on Kor'Gall, then after some server transfers I have a handful of characters on Executus, including what's likely to be my Shadowlands main. However, I cannot have both my Kor'Gall and my Executus characters on the same grid view, even though they're pretty much the same server for all intents and purposes.

I had a similar problem with ElvUI, and after I recommended them to use the player GUID, they found a solution: https://git.tukui.org/elvui/elvui/-/commit/d4e12265af339bf309789a2764e410acc97c8e8d

Do you think you could look into allowing the realm-limited sections to work across connected realms?

**Comment by teelolws** [comment]
Yeah now that I've made it 50 characters I guess I can remove the realm restriction.

**Comment by teelolws** [comment]
Changed in https://github.com/teelolws/Altoholic-Retail/releases/tag/8.3.037

**Comment by nanaki-13** [comment]
While I generally welcome the change to compare character over multiple realms (esp. for rep etc), I ran into a little problem here:

I have 5 licences on one account, so the 50 characters limit does not really apply in this case. Basically the char selection list in the Grid view is too long to fully display (over 10 years of playing can do that to you :)), even with dragging the window around to make more space ( I have this issue with several addons using full char lists, like Postal, but I can mostly work around that). 

Would it be possible to have a filter selection in Grid view like in the Summary view, like "This realm (This account)", "This realm (All accounts)" etc.? That would help me out greatly. Thanks in advance, and thanks for keeping the addon updated!

**Comment by teelolws** [comment]
It shouldn't be showing characters on your other accounts.

**Comment by teelolws** [comment]
If you're seeing more than 50 characters on that list then you either:
1. Have deleted characters on there, you should just delete them off the addon, or
2. You've been messing with the Saved Variables to group all your characters together, but have them all grouped under the "Default" account. The built-in Account Sharing system prompts you to provide account names to avoid this problem. If this is whats happening, you should change your variable script. Characters on other accounts shouldn't be listed under the Default account.
