### ISSUE TITLE
Mismatch in which version you get?

### ISSUE THREAD

**Issue by casperstorm** [teelolws/Altoholic-Retail#92]
Hello,

I am currently creating a [Addon Manager](https://github.com/casperstorm/ajour/) and while parsing the `.toc` files I've noticed that [Altoholic 8.3.001](https://www.curseforge.com/wow/addons/altoholic/files/2878102) on curse  has a strange version tag: `## Version: r191`. Looking at this [toc file in here](https://github.com/teelolws/Altoholic-Retail/blob/master/Altoholic/Altoholic.toc#L12) makes more sense: `## Version: 837038` – so why does it differ?

It creates a problem in my application because it parses my local version to `r191` and the remote version from curse to `Altoholic 8.3.001` - but my application have no idea of knowing that.

<img width="937" alt="Screenshot 2020-08-31 at 21 25 10" src="https://user-images.githubusercontent.com/2248455/91758606-909aa400-ebd0-11ea-88ea-f07accf96109.png">

**Comment by teelolws** [comment]
Neither of those are my addon. Mine is https://www.curseforge.com/wow/addons/altoholic-retail

**Comment by casperstorm** [comment]
I see!
I'll redirect the issue to the correct repo.

Thank you!

**Comment by teelolws** [comment]
The ## version line should now match the version displayed on curseforge for both retail and classic.
