### ISSUE TITLE
Grids reset

### ISSUE THREAD

**Issue by lovs2build** [teelolws/Altoholic-Retail#93]
Grids characters reset and is now showing all characters on all realms. I have 12 120's that I use to keep track of rep, emissions etc now after latest update I have bunch of toons I don't play. I don't know how to remove them. I tried going back a couple releases but problem remains.

Here is screen shot showing other toons.
https://prnt.sc/uac8vf

**Comment by teelolws** [comment]
Use the arrows at the bottom to scroll left/right, and mouseover the class icons at the top to change that column to a different character.

**Comment by lovs2build** [comment]
I can scroll yes but I can't change anything, or add / remove classes or change character.

**Comment by teelolws** [comment]
Upload your saved variables.

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Retail/wiki/Uploading-your-Saved-Variables

**Comment by lovs2build** [comment]
where do I find saved variables?

**Comment by lovs2build** [comment]
says something went really wrong and we can't process that file

**Comment by teelolws** [comment]
Hop on my discord server and upload them there: https://discord.gg/Uq99qw

**Comment by lovs2build** [comment]
https://www.dropbox.com/s/icjydzui8f6z0wd/SavedVariables.zip?dl=0

**Comment by lovs2build** [comment]
can you send another discord link it says it is expired, thanks.

**Comment by teelolws** [comment]
It says you joined:
 
![image](https://user-images.githubusercontent.com/49792789/92063119-750ce480-edee-11ea-83ec-469e9db1789e.png)

**Comment by teelolws** [comment]
https://discord.gg/EUSSGS
