### ISSUE TITLE
Cloak level is just a blank square again for all toons

### ISSUE THREAD

**Issue by raysmith59** [teelolws/Altoholic-Retail#96]
This was fixed but seems to have been re-broken at some point, been a while since I checked that grid so it may not be a particularly new issue.

**Comment by teelolws** [comment]
I haven't touched that code lately, I don't see why it wouldn't.

![image](https://user-images.githubusercontent.com/49792789/92326907-bf6dba00-f0a9-11ea-98c0-e1361e009b7d.png)

Any altoholic or datastore modules disabled/missing?

I recently changed the way Grids works, by removing the Realm lock. Mousing over the class icon should now give you a menu of all your characters on that account. In doing this, the list had to be reset. Checked you've got the right characters on those columns?

**Comment by raysmith59** [comment]
Yeah, my toons are listed on the icons, I hadn't realized that the class icons weren't representing actual toons.  Could you use some sort of generic placeholder icon instead of a class icon when a toon isn't selected to make this more obvious?

**Comment by teelolws** [comment]
There IS a placeholder when a character isn't selected. They're a green question mark. You must have had _something_ selected, just not what you expected.

The default, which it was reset to in the recent update, is to list each of your characters on your Default account alphabetically.
