### ISSUE TITLE
Realm filter v.8.3.7.040

### ISSUE THREAD

**Issue by Addonman** [teelolws/Altoholic-Retail#97]
Can you re add realm filters like in summary pane  to achivements and grids pane? Now this version only has account filter and shows all chars on account which is really unusable if you got lots of alts.

**Comment by teelolws** [comment]
Okay. https://github.com/teelolws/Altoholic-Retail/commit/8d0b726087862ae1830c7a307217c7b4931ee8a3

**Comment by Ruffz** [comment]
Hi,

Default filter should be "current realm" or, at least, remember user choice (like Thaoky's version)
