### ISSUE TITLE
[Suggestion] Ability to "ignore" specific server gold totals in Summary view

### ISSUE THREAD

**Issue by penguinsane** [teelolws/Altoholic-Retail#98]
I have characters across 6 realms, but would like to be able to set some realms to "ignore" when it comes to viewing totals in Summary view. I don't want to delete their data entirely, just be able to hide them when I don't want to include them in calculated totals.

If this is already a feature, I apologize, please point me in the right direction!

**Comment by Addonman** [comment]
Just look at realms filter.Its first icon in like top bar of icons.

**Comment by teelolws** [comment]
He wants to hide *some* realm, not all other realms but the one hes currrently playing on. Probably because of connected server stuff. I'll consider it.

**Comment by penguinsane** [comment]
Yes! That's exactly it. Thanks so much for the consideration.

**Comment by teelolws** [comment]
Allright. Its coming in the version for Shadowlands. 

![image](https://user-images.githubusercontent.com/49792789/92814962-e0227080-f417-11ea-852b-5a03359d9b49.png)
